maproulette/maproulette-backend

- README.md
- conf/application.conf
This PR:
* adds some detail and fixes some small errors in the readme.
* adds automatic applying of downward migrations in the DB to ensure a smooth CI flow
> Improvements to readme and add automatic down migrations

- app/assets/javascripts/app.js
- app/assets/javascripts/mapping.js
- app/assets/stylesheets/mapping.less
- app/controllers/MappingController.scala
- app/org/maproulette/models/Lock.scala
- app/org/maproulette/models/Task.scala
- app/org/maproulette/models/dal/BaseDAL.scala
- app/org/maproulette/models/dal/TaskDAL.scala
- app/views/admin/forms/taskForm.scala.html
- app/views/main.scala.html
- app/views/user/sidebar.scala.html
There are still quite a few little things to fix and update, however the base functionality will work.
> Base Functionality complete

- app/assets/javascripts/mapping.js
- app/controllers/AuthController.scala
- app/controllers/FormEditController.scala
- app/org/maproulette/controllers/ControllerHelper.scala
- app/org/maproulette/models/Challenge.scala
- app/org/maproulette/models/dal/ChallengeDAL.scala
- app/views/admin/challenge.scala.html
- app/views/user/userInfo.scala.html
- conf/evolutions/default/1.sql
Previously we were just redirecting the user to the main index page after they signed in, this could be annoying if looking at a specific task, you would basically lose it. This checkin will have the user redirect to the page or task they are currently looking at.
> Redirect correctly after signin

- conf/application.conf
- project/plugins.sbt
Reverting to Play 2.5.0, apparently 2.5.3 introduced an interesting issue in our code.
> Changing typesafe repo's.

- app/assets/javascripts/main.js
- app/controllers/Application.scala
- app/controllers/AuthController.scala
- app/controllers/MappingController.scala
- app/org/maproulette/jobs/JobModule.scala
- app/org/maproulette/jobs/Scheduler.scala
- app/org/maproulette/jobs/SchedulerActor.scala
- app/org/maproulette/models/Lock.scala
- app/org/maproulette/models/dal/BaseDAL.scala
- app/org/maproulette/models/dal/ParentDAL.scala
- app/org/maproulette/models/dal/ProjectDAL.scala
- app/org/maproulette/models/dal/TaskDAL.scala
- app/org/maproulette/models/utils/DALHelper.scala
- app/org/maproulette/session/SessionManager.scala
- app/org/maproulette/session/User.scala
- app/org/maproulette/session/dal/UserDAL.scala
- app/views/admin/users/users.scala.html
- conf/application.conf
- conf/evolutions/default/1.sql
- conf/routes
Various fixes that were related to user permissions. See commits for more details.
> Fixes related to User Permissions

- app/org/maproulette/cache/CacheManager.scala
- app/org/maproulette/models/dal/BaseDAL.scala
- app/org/maproulette/session/dal/UserDAL.scala
- test/org/maproulette/models/ChallengeSpec.scala
- test/org/maproulette/models/ProjectSpec.scala
- test/org/maproulette/models/SurveySpec.scala
- test/org/maproulette/models/TagSpec.scala
- test/org/maproulette/models/TaskSpec.scala
#54 will now fail with NotFound exception if try to delete a non-existent object.
> Fixing issue with deletion

- conf/evolutions/default/1.sql
- docs/admin/challenges.md
- docs/admin/tasks.md
Two things in here: 
1) A typo in the schema SQL prevented it from running
2) small docs updates
> typo in schema SQL, and small docs updates

- app/org/maproulette/controllers/ParentController.scala
- app/org/maproulette/models/dal/BaseDAL.scala
- app/org/maproulette/models/dal/ChallengeDAL.scala
- app/org/maproulette/models/dal/ProjectDAL.scala
- app/org/maproulette/models/dal/SurveyDAL.scala
- app/org/maproulette/models/utils/DALHelper.scala
- app/org/maproulette/session/SessionManager.scala
- app/org/maproulette/session/dal/UserDAL.scala
- app/views/admin/project.scala.html
This allows any user that is logged in to create their own challenges in their own custom space. The project will be disabled by default and only can be enabled by a super user. The challenges will be shareable through the permalink and people can work on them, however they will be hidden from the main page, search functionality and latest/featured/hot challenges.
> Adding default project space for all users

- conf/routes
> #73 fixing issues limiting user list to 10 users.

- app/assets/javascripts/mapping.js
- app/controllers/FormEditController.scala
- app/controllers/MappingController.scala
- app/org/maproulette/models/dal/TaskDAL.scala
- app/org/maproulette/services/ChallengeService.scala
- app/org/maproulette/session/SearchParameters.scala
- app/views/admin/forms/challengeForm.scala.html
- app/views/admin/forms/elements/challengeCreation.scala.html
- conf/routes
A couple of very small issues addressed with the overpass query challenge creation, which should make things smoother.
> Fixes related to the overpass query.

- README.md
Just started running this locally, these instructions follow what I did to get it running
> Install instructions for Linux (Ubuntu 14.04)

- app/assets/javascripts/mapping.js
- app/views/index.scala.html
#90 Fixed, and fixed issue where you could not update the search text in the search bar.
> Very minor updates

- app/assets/javascripts/main.js
- app/assets/javascripts/mapping.js
- app/controllers/MappingController.scala
- app/org/maproulette/models/dal/ChallengeDAL.scala
- app/org/maproulette/models/dal/TaskDAL.scala
- app/org/maproulette/session/SearchParameters.scala
- app/views/admin/forms/challengeForm.scala.html
- app/views/admin/forms/projectForm.scala.html
- app/views/includes/jsIncludes.scala.html
- build.sbt
- conf/routes
So to make the management of search parameters easier and more consistent through a session, I changed the storage of those parameters in a cookie instead of relying on the query string parameters.
#111 fixed some typo's in the SQL
> Search parameters through cookies instead of Query string

- README.md
> Update Documentation for Ubuntu Install

- app/assets/javascripts/mapping.js
- app/controllers/FormEditController.scala
- app/org/maproulette/exception/MPExceptionUtil.scala
- app/org/maproulette/models/dal/ProjectDAL.scala
- app/views/admin/forms/projectForm.scala.html
- app/views/admin/project.scala.html
- app/views/user/rightSidebar.scala.html
> Admins of projects can now make their projects visible

- app/assets/javascripts/main.js
- app/assets/javascripts/mapping.js
- app/assets/javascripts/metrics.js
- app/assets/stylesheets/mapping.less
- app/controllers/Application.scala
- app/org/maproulette/models/ClusteredPoint.scala
- app/org/maproulette/models/dal/ChallengeDAL.scala
- app/org/maproulette/models/dal/ProjectDAL.scala
- app/org/maproulette/session/SearchParameters.scala
- app/views/includes/jsIncludes.scala.html
- app/views/main.scala.html
- build.sbt
- conf/messages
- conf/routes
Integrating internationalization messages into the javascript files.
> Internationalization

- app/assets/javascripts/mapping.js
> #163 Fixed issue where JOSM was always opening with new layer

- README.md
> Update readme to change slack link

- app/org/maproulette/models/dal/ProjectDAL.scala
- app/org/maproulette/models/dal/TaskDAL.scala
- conf/evolutions/default/1.sql
This is primarily related to some performance improvements. A couple of changes related to an upcoming feature (suggested fixes) slipped in, but has no impact on actual functionality.
> Performance Improvements

- app/assets/javascripts/main.js
- app/assets/javascripts/mapping.js
- app/controllers/MappingController.scala
- app/org/maproulette/models/dal/TaskDAL.scala
- app/org/maproulette/session/SearchParameters.scala
- conf/messages
Added ability to go through tasks in debug mode filtered by a set of task status'
To modify the current TaskStatus filter add the following query string parameters:
?debug=true&taskStatus=<STATUS_SET>
Where <STATUS_SET> is a comma separated list of valid status id's.
0 - Created
1 - Fixed
2 - False Positive
3 - Skipped
4 - Deleted
5 - Already Fixed
6 - Too Hard
Example:
taskStatus=1,2
> Added last user who modified task in instructions

- README.md
Link the github wiki pages which seem to have some 'creating challenges' tutorial info
> Link creating challenges tutorial

- app/org/maproulette/models/dal/ChallengeDAL.scala
- app/org/maproulette/session/SearchParameters.scala
2 fixes:
Modify challenges parser such that the checkin_comment uses optional, as it is a optional null column so requires optional string.
Update query string parameter for location in extendedFind. Should be "tbb" instead of "ttb"
> Fixing issue related to the Challenge parser.

- app/controllers/Application.scala
- app/org/maproulette/controllers/api/TaskController.scala
- app/org/maproulette/models/dal/ChallengeDAL.scala
- app/org/maproulette/models/dal/TaskDAL.scala
- app/org/maproulette/models/utils/DALHelper.scala
- conf/apiv2.routes
The new function will retrieve all the tasks regardless of Challenge or Project within a given bounding box.
The API allows you to use the standard search operations, like fuzzy search, tag searching and limits based on priority and status.
> Adding new API to retrieve tasks from within a bounding box.

- app/org/maproulette/models/dal/ProjectDAL.scala
Was passing in the id of the User object instead of the osm id of the user.
> Was passing in the incorrect owner_id

- app/assets/javascripts/main.js
- app/assets/javascripts/mapping.js
- app/controllers/Application.scala
- app/controllers/MappingController.scala
- app/org/maproulette/Config.scala
- app/org/maproulette/actions/Actions.scala
- app/org/maproulette/controllers/api/ChallengeController.scala
- app/org/maproulette/controllers/api/VirtualChallengeController.scala
- app/org/maproulette/jobs/Scheduler.scala
- app/org/maproulette/jobs/SchedulerActor.scala
- app/org/maproulette/models/VirtualChallenge.scala
- app/org/maproulette/models/dal/BaseDAL.scala
- app/org/maproulette/models/dal/ChallengeDAL.scala
- app/org/maproulette/models/dal/DALManager.scala
- app/org/maproulette/models/dal/Locking.scala
- app/org/maproulette/models/dal/TaskDAL.scala
- app/org/maproulette/models/dal/VirtualChallengeDAL.scala
- app/org/maproulette/models/utils/ChallengeFormatters.scala
- app/org/maproulette/models/utils/DALHelper.scala
- app/org/maproulette/services/ChallengeService.scala
- app/org/maproulette/utils/Utils.scala
- app/views/mr3.scala.html
- conf/apiv2.routes
- conf/evolutions/default/12.sql
- conf/routes
- conf/swagger.yml
- postman/maproulette2.postman_collection.json
Ordinarily this should be the other way around, as all PR's should be merged to dev first. But initially there was a mixup. So now getting the branches even.
> Merging into dev

- app/org/maproulette/services/ChallengeService.scala
This is a minor fix that handles individual line failures in line by line geojson.
> Making line by line geojson task creation more robust

- app/org/maproulette/controllers/api/ChallengeController.scala
- app/org/maproulette/models/dal/ChallengeDAL.scala
- app/org/maproulette/models/dal/TaskDAL.scala
- conf/evolutions/default/15.sql
This also fixes an issue related to adding comments.
> Including LineByLine GeoJSON in Challenge extract

- app/org/maproulette/controllers/api/DataController.scala
- app/org/maproulette/data/DataManager.scala
- conf/apiv2.routes
Support in leaderboard and top-challenges APIs for user filters, project
filters, challenge filters, and onlyEnabled filter.
> Add filters to leaderboard and top-challenges APIs

- app/org/maproulette/models/dal/ProjectDAL.scala
In addition to checking for group membership, also include projects with
matching owner_id in results of listManagedProjects.
> Include owned projects in listManagedProjects.

- app/assets/javascripts/mapping.js
- app/controllers/Application.scala
- app/org/maproulette/exception/MPExceptionUtil.scala
- app/views/admin/challenge.scala.html
- app/views/controls/rightSidebar.scala.html
- app/views/index.scala.html
- conf/routes
This will just default to the new UI.
> Forcing root path to deliver new UI by default.

- app/org/maproulette/controllers/api/UserController.scala
- app/org/maproulette/models/dal/TaskDAL.scala
- app/org/maproulette/session/SessionManager.scala
- app/org/maproulette/session/dal/UserDAL.scala
- conf/apiv2.routes
- conf/evolutions/default/17.sql
Fixes/Updates include:
- Added API to delete and optimally anonymize a users data
- Copied API to generate API Key for user to the user api controller, still in the auth controller.
- Fixed 2 SQL bugs in the TaskCluster APIs
- Double checked that all project groups have been created prior to trying to add users to project groups.
- Fixed security issue with the API Key, and how it was being stored.
> Added API to delete and anonymize user

- app/org/maproulette/models/dal/ChallengeDAL.scala
Add missed comma after checkinSource in challenge insert query.
> Missed comma in challenge insert SQL. Fixes #445

- app/org/maproulette/models/dal/ProjectDAL.scala
* Override find method in ProjectDAL to also search by display_name
in addition to name.
> Changed project find to also search by display_name

- app/org/maproulette/controllers/api/ProjectController.scala
- app/org/maproulette/models/dal/ProjectDAL.scala
- conf/apiv2.routes
Add optional sort parameter to method that fetches managed projects
default is "display_name"
> Add optional sort param to listManagedProjects

- app/org/maproulette/jobs/SchedulerActor.scala
Change SchedulerActor.updateLocations to run each challenge update in its own
transaction so that if one fails due to bad data the rest will continue
to be processed.
Fixes osmlab/maproulette3#567
> Update location of each challenge individually

- app/org/maproulette/data/DataManager.scala
- app/org/maproulette/jobs/SchedulerActor.scala
- app/org/maproulette/utils/BoundingBoxFinder.scala
* Fetching the country-code-bounding-box.json not working
in staging as it's put in the build jar. Changed
BoundingBoxFinder to fetch with resourceAsStream instead.
* Changed BoundingBoxFinder from Object to Singleton class.
> Change country code file fetch to work on staging

- README.md
- app/org/maproulette/cache/CacheManager.scala
- app/org/maproulette/cache/CacheObject.scala
- app/org/maproulette/cache/CacheStorage.scala
- app/org/maproulette/controllers/OSMChangesetController.scala
- app/org/maproulette/exception/MPExceptionUtil.scala
- app/org/maproulette/exception/MPExceptions.scala
- app/org/maproulette/models/BaseObject.scala
- app/org/maproulette/models/Task.scala
- app/org/maproulette/models/dal/ChallengeDAL.scala
- app/org/maproulette/models/dal/TaskDAL.scala
- app/org/maproulette/services/osm/ChangeObjects.scala
- app/org/maproulette/services/osm/ChangesetService.scala
- app/org/maproulette/services/osm/object/NodeService.scala
- app/org/maproulette/services/osm/object/ObjectService.scala
- app/org/maproulette/services/osm/object/RelationService.scala
- app/org/maproulette/services/osm/object/VersionedObjects.scala
- app/org/maproulette/services/osm/object/WayService.scala
- app/org/maproulette/utils/Utils.scala
- conf/apiv2.routes
- conf/dev.conf
- docs/tag_changes.md
This commit introduces API for Suggested Fixes for Tags only. It adds two new API's, one to test changes and the other to submit changes. It handles creation and closing of Changesets in the background and users focus entirely on tag delta changes that are submitted to the server.
> Phase 1 commit for Suggested Fixes.

- app/org/maproulette/models/dal/ChallengeDAL.scala
Fixes bug osmlab/maproulette#625
> Fix FINISHED status check on challenges with no status

- app/org/maproulette/session/dal/UserDAL.scala
When updating the user score, the most recent user score would not be passed back to the client as the user object is cached. Change update user score method to also update the user in the cache.
> Update user cache when updating user score.

- app/org/maproulette/models/dal/TaskDAL.scala
- app/org/maproulette/session/dal/UserDAL.scala
- conf/evolutions/default/29.sql
* Fix bug where new users (since user_metrics table created) would
not have their metrics updated as they did not have initial entry in table
* New columns to user_metrics and user_metrics_history
* On setTaskReviewStatus update metrics
> Add review status metrics to user_metrics

- app/org/maproulette/Config.scala
- app/org/maproulette/models/dal/TaskDAL.scala
- app/org/maproulette/session/User.scala
- app/org/maproulette/session/dal/UserDAL.scala
- conf/application.conf
- conf/evolutions/default/30.sql
- conf/evolutions/default/31.sql
* Change users.needs_review to be an integer
* Add constants for
1. Review Not Needed,
2. Review Needed (review but user can change this)
3. Review Mandatory (review always, user cannot change)
* Add environment configuration setting for default behavior when not set
> Change type of user 'needsReview' setting

- app/org/maproulette/jobs/SchedulerActor.scala
Additional columns were added by prior PR.
> Fix user metrics history snapshot sql

- app/org/maproulette/session/dal/UserDAL.scala
Add override of BaseDal retrieveById so that score can also be retrieved.
> Add override UserDal.retrieveById to return score in query

- app/org/maproulette/models/dal/TaskDAL.scala
Fix sql for cancel task review introduced when splitting off task_review table.
> Fix minor cancel task review bug

- app/org/maproulette/controllers/api/ChallengeController.scala
- app/org/maproulette/models/dal/TaskDAL.scala
* Add comments column to task summary csv in format:
myName: Some comment 
---
otherUser: more comments
* Also add columns mappedOn, reviewStatus, mapper, reviewedBy, reviewedAt
> Add comments to task summary csv

- app/org/maproulette/data/DataManager.scala
- app/org/maproulette/jobs/SchedulerActor.scala
- app/org/maproulette/jobs/utils/LeaderboardHelper.scala
* Add cache building to build 'all time' and store results as monthDuration = -1 (column is required in database)
* Add support for "all time" results from cache to be returned in api
> Add support 'ALL TIME' leaderboard

- app/org/maproulette/models/dal/TaskDAL.scala
* Cache was not updating reviewedBy and reviewRequestedBy fields
so it was throwing errors when setTaskReview was called later
> Fix caching bug with setTaskReview

- app/org/maproulette/jobs/SchedulerActor.scala
- app/org/maproulette/models/dal/TaskDAL.scala
In preparation for a point release.
> Merge dev to master

- app/org/maproulette/controllers/api/DataController.scala
- app/org/maproulette/controllers/api/UserController.scala
- app/org/maproulette/session/dal/UserDAL.scala
- conf/apiv2.routes
* Make leaderboard able to fetch even if not logged in
* Add API getUserMetrics
* Change getUser (and by osm username) to allow a user not
logged in (also not super user) to fetch some basic user
information like name, avatar, etc.
> Add user metrics support

- app/org/maproulette/controllers/api/VirtualProjectController.scala
- app/org/maproulette/data/DataManager.scala
- app/org/maproulette/models/Challenge.scala
- app/org/maproulette/models/Project.scala
- app/org/maproulette/models/dal/ChallengeDAL.scala
- app/org/maproulette/models/dal/ProjectDAL.scala
- app/org/maproulette/models/dal/TaskDAL.scala
- app/org/maproulette/models/dal/VirtualProjectDAL.scala
- conf/apiv2.routes
- conf/evolutions/default/35.sql
- postman/maproulette2.postman_collection.json
* Create evolution to add virtual project_challenge join table
and project.is_virtual column
* Create virtual project controller/dal to handle add/remove challenges
* Modify project and challenge queries to use new join table
> Support for Virtual Projects

- app/org/maproulette/controllers/api/VirtualProjectController.scala
- app/org/maproulette/data/DataManager.scala
- app/org/maproulette/models/Challenge.scala
- app/org/maproulette/models/Project.scala
- app/org/maproulette/models/dal/ChallengeDAL.scala
- app/org/maproulette/models/dal/ProjectDAL.scala
- app/org/maproulette/models/dal/TaskDAL.scala
- app/org/maproulette/models/dal/VirtualProjectDAL.scala
- conf/apiv2.routes
- conf/evolutions/default/35.sql
- postman/maproulette2.postman_collection.json
The Virtual Project PR was accidentally merged directly into master, so just merging master down to merge to make sure that we pick up the changes.
> Push from Master

- app/org/maproulette/controllers/api/DataController.scala
- app/org/maproulette/data/DataManager.scala
- conf/apiv2.routes
- postman/maproulette2.postman_collection.json
* Add Postman tests for virtual projects to ensure methods
run without errors.
* Deprecated method getChallengeSummaries as it is not used
and does not support virtual projects.
> Add additional support for virtual projects in data methods

- app/org/maproulette/controllers/api/ChallengeController.scala
- app/org/maproulette/models/dal/ChallengeDAL.scala
- conf/apiv2.routes
* Add additional geoJSON properties field "maproulette"
which includes additional MR related task info
* Fixed query when using status filter
* Add additional filters 'reviewStatus' and 'priority'
> Change getChallengeGeometry to inclue task info.

- app/org/maproulette/controllers/api/ChallengeController.scala
- app/org/maproulette/models/dal/ChallengeDAL.scala
- app/org/maproulette/models/dal/TaskDAL.scala
- conf/apiv2.routes
- Add status, priority, reviewStatus filters to export CSV
(extractTaskSummaries)
- Change export geoJSON (getChallengeSummary) to return correct mime type
- Change export geoJSON to honor '-1' in review status as tasks without a review status
> Add filters to export CSV

- app/org/maproulette/controllers/api/ChallengeController.scala
- app/org/maproulette/controllers/api/TagController.scala
- app/org/maproulette/controllers/api/TagsMixin.scala
- app/org/maproulette/controllers/api/TaskController.scala
- app/org/maproulette/models/Tag.scala
- app/org/maproulette/models/dal/ChallengeDAL.scala
- app/org/maproulette/models/dal/TagDAL.scala
- app/org/maproulette/models/dal/TagDALMixin.scala
- app/org/maproulette/models/dal/TaskDAL.scala
- conf/apiv2.routes
- conf/evolutions/default/37.sql
* Support adding tags when setTaskStatus
* Support adding tags when setTaskReviewStatus
* Add tagType to Tag to distinguish between challenge and task tags
* In API for searching for tags allow filter by tagType
> More tags on task support

- app/org/maproulette/models/dal/TaskDAL.scala
* Override retrieveByName in TaskDAL to ensure that the task_review
table is joined in
* This fixes the 500 error encountered when using the GET
`challenge/:id/task/:name` API endpoint
> Fix task retrieval by name

- app/org/maproulette/models/dal/ChallengeDAL.scala
* Moved geojson export properties from under 'maproulette' to top
level properties mr-* so that they work in JOSM
* Added translation from task status int to text
> Changed geojson export to list maproulette props as mr-*

- app/org/maproulette/models/dal/TagDAL.scala
- conf/evolutions/default/38.sql
Task tags and challenge tags should be able to have the
same name -- so change unique constraint to be within a
tag_type.
> Change unique index on tags name to include tag_type

- app/org/maproulette/controllers/api/DataController.scala
- app/org/maproulette/controllers/api/TaskReviewController.scala
- app/org/maproulette/data/DataManager.scala
- app/org/maproulette/models/dal/TaskReviewDal.scala
- conf/apiv2.routes
* support for taskStatus, reviewStatus and priority list filters for fetch challenge summary
* support for priority search when getting review Metrics
> Add support for filtering for challenge summary

- app/org/maproulette/models/Challenge.scala
* Allow priority rules to contain nested rules so that AND and OR
logic can be combined when creating a rule set
> Support nested priority rules

- app/org/maproulette/models/dal/ChallengeDAL.scala
- app/org/maproulette/provider/ChallengeProvider.scala
- conf/evolutions/default/39.sql
Fixing bugs with latest deployment
> Fixing bugs related to latest deployment (#596)

- app/org/maproulette/models/dal/TaskDAL.scala
PR gives a slight performance and efficiency improvement on setting the task priority. It also makes sure that it happens when the task is updated/inserted instead of after the fact.
> Task priority updates

- app/org/maproulette/controllers/CRUDController.scala
- app/org/maproulette/models/Task.scala
- app/org/maproulette/provider/ChallengeProvider.scala
- app/org/maproulette/utils/Utils.scala
- conf/evolutions/default/40.sql
- Geometry properties were not being parsed correctly
- An ambiguous variable name was being used in the task create/update functions
> Fixing a couple issue with task update/create

- app/org/maproulette/Config.scala
- app/org/maproulette/models/dal/TaskDAL.scala
- app/org/maproulette/models/dal/VirtualChallengeDAL.scala
- conf/application.conf
- Add configuration flag skipTooHard to not return too hard
tasks when asking for the next random task.
> Add flag to not return too hard tasks

- app/org/maproulette/controllers/api/ChallengeController.scala
- app/org/maproulette/models/Challenge.scala
- app/org/maproulette/models/utils/DALHelper.scala
* When searching by project name also search for matching
virtual projects.
* Return same extra json for virtual projects that is
returned for projects.
> Support virtual project search in extendedFind

- app/org/maproulette/controllers/api/ChallengeController.scala
- app/org/maproulette/models/dal/TaskDAL.scala
Add bundleId and isBundlePrimary columns to CSV export of task summaries.
> Add bundle id to CSV task export

- app/org/maproulette/models/dal/TaskDAL.scala
Fix bug with excludeLocked flag in getTasksInBoundingBox.
> Fix bug with excludeLocked in getTasksInBoundingBox

- app/org/maproulette/models/dal/TaskDAL.scala
- app/org/maproulette/utils/Utils.scala
* Ensure suggested-fix JSON added as a feature property is converted to
string form (as all feature properties are)
* Handle unescaping/reconversion back to JSON of stringified
suggested-fix data during task creation
> Handle suggested fixes added as feature properties

- app/controllers/Application.scala
- app/org/maproulette/controllers/api/TagsMixin.scala
- conf/routes
This is a very basic endpoint that can be used to check if the server is up of not. It does not check specific health of server, simply if it is running.
> Server Check Endpoint

- README.md
Mainly to make it clearer what the separation is between the front-end and back-end repos. Also shortening a bit for clarity.
> Minor fix to the README

- app/org/maproulette/models/dal/TaskDAL.scala
It is possible for kmeans cluster to return clusters with empty
coordinates -- so we need to filter out these clusters.
> Add check to prevent error when cluster has invalid coordinates

- app/org/maproulette/models/dal/TaskDAL.scala
- app/org/maproulette/models/dal/VirtualChallengeDAL.scala
- app/org/maproulette/session/SearchParameters.scala
- postman/maproulette2.postman_collection.json
* Add support for boundingGeometries in SearchParameters
* Allow virtual challenges to be created with boundingGeometries
* Modify getTaskInBoundingBox to use new boundingGeometries
> Allow for creating Virtual Challenges from cluster data

- app/org/maproulette/models/dal/ChallengeDAL.scala
* Only send challenge-completion notifications if the challenge is
actually updated with a FINISHED status in the database
> Only send completion notifications when finished

- app/org/maproulette/models/dal/ProjectDAL.scala
* Honor "enabled" setting at project creation time for non-superusers
* Previously, only superusers could enable a project at creation, while
normal users would have to subsequently update their projects after
creation to enable them
> Allow all users to enable projects at creation

- app/org/maproulette/provider/ChallengeProvider.scala
Should fix https://github.com/osmlab/maproulette3/issues/954: when using `out center` in an overpass query, it would pick up these centers.
Untested locally, since I don't have scala and I have no idea how to get the entire thing running. Sorry for that, fell free to close the PR if that's a burden to the maintainers.
> Parse center property of the overpass output

- app/org/maproulette/models/dal/TagDALMixin.scala
* Fix query in `TagDALMixin.getItemsBasedOnTags` so that it works for
both tasks and challenges
* Fixes osmlab/maproulette3#1069
> Fix retrieval of challenges and tasks by tags

- app/org/maproulette/models/dal/TaskDAL.scala
If calling setTaskStatus with skipped, don't actually update the task status to skipped if it's in a different status than created. (ie. If someone else has already marked task as 'tooHard' then it should remain as 'tooHard' and not get marked as 'skipped' -- but we still need to note that the user skipped the task so that it doesn't get served up to them again.)
> When setTaskStatus to skipped selectively update task status

- app/org/maproulette/controllers/api/SnapshotController.scala
Had errorneous 'comments' in name. New name is "challenge_$id_snapshots.csv'
> Rename challenge snapshot csv download.

- app/org/maproulette/controllers/api/ProjectController.scala
- app/org/maproulette/models/Project.scala
- app/org/maproulette/models/dal/ChallengeDAL.scala
- app/org/maproulette/models/dal/ProjectDAL.scala
- conf/apiv2.routes
- conf/evolutions/default/54.sql
* Add `featured` column to projects
* Add `projects/featured` API endpoint for retrieving featured projects
> Note: featuring a project does **not** feature its challenges
> Allow projects to be featured

- app/org/maproulette/models/Challenge.scala
- app/org/maproulette/models/dal/ChallengeDAL.scala
- app/org/maproulette/models/utils/ChallengeFormatters.scala
- conf/evolutions/default/55.sql
* Add 'task_styles' column to challenges
* Allow setting and returning as json
> Support taskStyles on Challenges

- app/org/maproulette/models/dal/TagDAL.scala
updateTagList returns any tags with matching names regardless
of tagType so if a tag was added to a task that had both
'challenges' and 'tasks' tag types it would appear twice.
> Fix duplicate task tags

- app/org/maproulette/controllers/api/ChallengeController.scala
- app/org/maproulette/controllers/api/DataController.scala
- app/org/maproulette/controllers/api/TaskController.scala
- app/org/maproulette/data/DataManager.scala
- app/org/maproulette/data/SnapshotManager.scala
- app/org/maproulette/jobs/SchedulerActor.scala
- app/org/maproulette/models/ClusteredPoint.scala
- app/org/maproulette/models/Task.scala
- app/org/maproulette/models/TaskReview.scala
- app/org/maproulette/models/dal/ChallengeDAL.scala
- app/org/maproulette/models/dal/ProjectDAL.scala
- app/org/maproulette/models/dal/TaskClusterDAL.scala
- app/org/maproulette/models/dal/TaskDAL.scala
- app/org/maproulette/models/dal/TaskReviewDAL.scala
- app/org/maproulette/models/dal/VirtualChallengeDAL.scala
- app/org/maproulette/models/dal/mixin/SearchParametersMixin.scala
- app/org/maproulette/session/SearchParameters.scala
- app/org/maproulette/session/dal/UserDAL.scala
- conf/evolutions/default/56.sql
* Add 'completedTimeSpent' and 'completedBy' on task
* Changed export csv to use completedBy column for mapper instead
of reviewRequestedBy
* Add new searchParameter 'm' for mapper that will search the
completedBy column for a user with a matching name
* Add ability to sort by reviewDuration 
* Fix not all tasks in bundle getting review_claimed_by when one task in bundle was startTaskReview
> Add support for time spent on a task.

- app/org/maproulette/controllers/api/ChallengeController.scala
- app/org/maproulette/models/dal/mixin/SearchParametersMixin.scala
* Change extractAllTaskSummaries to include all task statuses
* Add ability to include -1 as a task status to indicate all statues.
> Fix project csv download to not limit to created/skipped/too_hard

- app/org/maproulette/models/dal/TaskDAL.scala
> Merging to Master

- app/org/maproulette/controllers/api/ChallengeController.scala
'requiresLocal' should not have to be included when creating a
new challenge.
> Make 'requiresLocal' not have to be included in challenge json

- app/org/maproulette/controllers/api/DataController.scala
- app/org/maproulette/data/DataManager.scala
- app/org/maproulette/framework/repository/ProjectRepository.scala
- app/org/maproulette/models/dal/ChallengeDAL.scala
- build.sbt
- conf/evolutions/default/60.sql
- conf/route/data.api
- conf/route/v2.api
- scripts/readme.md
- scripts/v4_play_evolutions.csv
- test/org/maproulette/framework/util/TestDatabase.scala
This PR removes all the references to Survey, including creating a new 60.sql evolution script that removes the references out of the database as well.
> Remove references to Survey

- README.md
- app/org/maproulette/Config.scala
- app/org/maproulette/exception/MPExceptionUtil.scala
- app/org/maproulette/exception/MPExceptions.scala
- app/org/maproulette/framework/controller/GraphQLController.scala
- app/org/maproulette/framework/controller/UserController.scala
- app/org/maproulette/framework/graphql/GraphQL.scala
- app/org/maproulette/framework/graphql/UserContext.scala
- app/org/maproulette/framework/graphql/schemas/ChallengeSchema.scala
- app/org/maproulette/framework/graphql/schemas/CommentSchema.scala
- app/org/maproulette/framework/graphql/schemas/GroupSchema.scala
- app/org/maproulette/framework/graphql/schemas/MRSchema.scala
- app/org/maproulette/framework/graphql/schemas/MRSchemaTypes.scala
- app/org/maproulette/framework/graphql/schemas/ProjectSchema.scala
- app/org/maproulette/framework/graphql/schemas/TaskSchema.scala
- app/org/maproulette/framework/graphql/schemas/UserSchema.scala
- app/org/maproulette/framework/model/Challenge.scala
- app/org/maproulette/framework/model/User.scala
- app/org/maproulette/framework/repository/UserRepository.scala
- app/org/maproulette/framework/service/UserService.scala
- app/org/maproulette/models/dal/ChallengeDAL.scala
- app/org/maproulette/session/SessionManager.scala
- app/views/graphiql.scala.html
- build.sbt
- conf/routes
- docs/graphql.md
- docs/testing.md
- test/org/maproulette/framework/UserSpec.scala
This is an experimental GraphQL server that leverages that changes made for the new MR framework. The idea is to get a sense of it's usefulness and whether it would be wise to build it out.
You can access the graphQL server here: https://<SERVER>:<HOST>/graphql
and there is a nice UI here: https://<SERVER>:<HOST>/graphql/ide
> Experimental GraphQL server

- app/org/maproulette/controllers/api/TaskReviewController.scala
- app/org/maproulette/models/dal/TaskReviewDAL.scala
Also add back tags fix that got lost in merge
And remove project owner check in review permissions
> Fix review table grantee error

- conf/swagger.yml
Fixing issue: https://github.com/maproulette/maproulette2/issues/779
> Fixing issue that was not setting the swagger host correctly

- app/org/maproulette/data/DataManager.scala
- app/org/maproulette/models/dal/TaskReviewDAL.scala
- app/org/maproulette/models/dal/mixin/SearchParametersMixin.scala
- app/org/maproulette/models/utils/DALHelper.scala
- app/org/maproulette/session/SearchParameters.scala
- postman/maproulette2.postman_collection.json
* add new 'invf' SearchParmeter that can include a list of search
fields that will be inverted (eg. where priority NOT in list)
* rename method "paramsChallengeIds" to "paramsTaskProps"
* changed DataManager.getChallengeSummary to use the
SearchParametersMixin whenever possible in prepartion
for conversion to new framework.
* add to DataManager.getChallengeSummary filter by completed_by
> Support inverting search parameters

- app/org/maproulette/framework/model/Challenge.scala
- app/org/maproulette/models/Task.scala
- app/org/maproulette/utils/Utils.scala
- test/org/maproulette/models/ChallengeSpec.scala
* Add support for supplying a priorityRule of valueType "bounds",
which will match if the task's location is within the bounding box
(MinX,MinY,MaxX,MaxY).
> Add ability to prioritze tasks by bounds

- app/org/maproulette/provider/ChallengeProvider.scala
* Allow line-by-line formatted GeoJSON to contain a single task (line)
> Allow single task with line-by-line format GeoJSON

- app/org/maproulette/framework/controller/TaskReviewController.scala
* Add additional column percentage reviewed in mapper metrics
* Add additional columns for task statuses in mapper metrics
> Add additional columns to mapper review metrics

- app/org/maproulette/framework/graphql/GraphQL.scala
- app/org/maproulette/framework/graphql/fetchers/ChallengeFetchers.scala
- app/org/maproulette/framework/graphql/fetchers/ProjectFetchers.scala
- app/org/maproulette/framework/graphql/schemas/MRSchemaTypes.scala
- app/org/maproulette/framework/model/Challenge.scala
- app/org/maproulette/framework/model/Project.scala
- app/org/maproulette/framework/service/ChallengeService.scala
* Add challenge object to ActionItem graphql
* Add project object for challenge graphql parent
* Add Sangria fetchers for challenges and projects
> Enhance ActionItem graphql support

- app/org/maproulette/framework/controller/TaskReviewController.scala
In mapper review export metrics add breakdown for each user
by review status with percentage covered.
> Add to mapper review export metrics breakdown by review status

- app/org/maproulette/session/SearchParameters.scala
Reverted prior date parameter change in Search Mixin and fixed correct leaderboard one.
> Changed wrong date parameter in prior PR to fix custom dates

- app/org/maproulette/controllers/api/ChallengeController.scala
- app/org/maproulette/framework/controller/LeaderboardController.scala
- app/org/maproulette/framework/mixins/LeaderboardMixin.scala
- app/org/maproulette/framework/repository/LeaderboardRepository.scala
- app/org/maproulette/framework/service/LeaderboardService.scala
- app/org/maproulette/models/utils/ChallengeFormatters.scala
- conf/v2_route/leaderboard.api
- test/org/maproulette/framework/repository/LeaderboardRepositorySpec.scala
- test/org/maproulette/framework/service/LeaderboardServiceSpec.scala
* Add new api to fetch top reviewers for a given challenge/project:
/data/reviewer/leaderboard
> Add support for fetching top reviewers

- app/org/maproulette/framework/controller/TaskReviewController.scala
- app/org/maproulette/framework/mixins/ReviewSearchMixin.scala
- app/org/maproulette/framework/mixins/SearchParametersMixin.scala
- app/org/maproulette/framework/service/TaskReviewService.scala
- test/org/maproulette/framework/mixins/SearchParametersMixinSpec.scala
* Add project and/or challenge name to mapper review export CSV
* Add support for building mapper review export from a virtual
project id
> Add project/challenge name to mapper review export

- conf/evolutions/default/71.sql
* Add evolution ensuring that GIST index is created on tasks `location` column
> Create GIST index on tasks location column

- conf/evolutions/default/75.sql
Evolution 75 down was not throwing a sql error
> Fix evolution 75 down

- app/org/maproulette/data/DataManager.scala
- app/org/maproulette/framework/repository/TaskClusterRepository.scala
- app/org/maproulette/framework/repository/TaskReviewMetricsRepository.scala
Also fix other cases where similiar error could occur.
> Fix sql error when doing project summary on empty project

- app/org/maproulette/framework/model/Challenge.scala
- app/org/maproulette/models/dal/ChallengeDAL.scala
- conf/evolutions/default/79.sql
- postman/maproulette2.postman_collection.json
* Add table "challenge_presets" with challenge_id and preset string
* Return "presets" as an optional array of strings on challenge
* Insert/Update array of strings from "presets" on challenge json
> Add support for "presets" on challenges

- app/org/maproulette/framework/model/Challenge.scala
- app/org/maproulette/framework/repository/ChallengeRepository.scala
- app/org/maproulette/models/dal/ChallengeDAL.scala
- conf/evolutions/default/81.sql
resolves https://github.com/osmlab/maproulette3/issues/178 along with this PR: https://github.com/osmlab/maproulette3/pull/1609
> Add changeset_url to challenge schema

- app/org/maproulette/Config.scala
- app/org/maproulette/framework/controller/TaskBundleController.scala
- app/org/maproulette/framework/model/UserNotification.scala
- app/org/maproulette/framework/repository/NotificationRepository.scala
- app/org/maproulette/framework/repository/NotificationSubscriptionRepository.scala
- app/org/maproulette/framework/service/NotificationService.scala
- app/org/maproulette/jobs/Scheduler.scala
- app/org/maproulette/jobs/SchedulerActor.scala
- app/org/maproulette/provider/EmailProvider.scala
- conf/application.conf
- conf/evolutions/default/82.sql
- test/org/maproulette/framework/repository/NotificationSubscriptionRepositorySpec.scala
- test/org/maproulette/framework/service/NotificationServiceSpec.scala
Add two notification settings that allow users to set up email notices of review or revision work still pending.
Requires https://github.com/osmlab/maproulette3/pull/1625
> Review and Revision Count Notifications

- app/org/maproulette/framework/model/UserNotification.scala
- app/org/maproulette/jobs/SchedulerActor.scala
- app/org/maproulette/provider/EmailProvider.scala
This is a minor revision of https://github.com/maproulette/maproulette2/pull/900.  I'm adding constants for the taskTypes to ensure proper referencing.
> Review and Revision Count Notifications Rev1

- app/org/maproulette/Config.scala
- app/org/maproulette/framework/model/Challenge.scala
- app/org/maproulette/framework/repository/ChallengeRepository.scala
- app/org/maproulette/framework/service/ChallengeService.scala
- app/org/maproulette/jobs/Scheduler.scala
- app/org/maproulette/jobs/SchedulerActor.scala
- conf/application.conf
This scheduler will find challenges with tasks not updated over the past six months and archive them.
Resolves https://github.com/osmlab/maproulette3/issues/1580
Will roll out with https://github.com/osmlab/maproulette3/pull/1636
> Scheduler for Archiving Stale Challenges

- app/org/maproulette/controllers/api/ChallengeController.scala
- app/org/maproulette/framework/controller/CommentController.scala
- app/org/maproulette/framework/model/Challenge.scala
- app/org/maproulette/framework/repository/ChallengeCommentRepository.scala
- app/org/maproulette/framework/repository/ChallengeRepository.scala
- app/org/maproulette/framework/service/ChallengeService.scala
- app/org/maproulette/framework/service/CommentService.scala
- app/org/maproulette/framework/service/NotificationService.scala
- app/org/maproulette/jobs/SchedulerActor.scala
- app/org/maproulette/models/dal/ChallengeDAL.scala
- conf/evolutions/default/84.sql
- conf/v2_route/challenge.api
users need an indicator that their challenge when and why their challenge was archived if the system did it for them.  This column also needs to be cleared if the user unarchives the challenge.
> integrate systemArchivedAt to challenge table

- app/org/maproulette/Config.scala
- app/org/maproulette/controllers/CRUDController.scala
- app/org/maproulette/controllers/api/ChallengeController.scala
- app/org/maproulette/framework/mixins/SearchParametersMixin.scala
- app/org/maproulette/models/dal/BaseDAL.scala
- app/org/maproulette/models/dal/ChallengeDAL.scala
- app/org/maproulette/provider/ChallengeProvider.scala
- conf/application.conf
Resolves https://github.com/osmlab/maproulette3/issues/1535
> Limit challenge tasks

- app/org/maproulette/jobs/SchedulerActor.scala
- conf/application.conf
for more visible logging capture, adding beginning and ending logs to each job, with total time spent completing the job.
> add job time logs and decrease leaderboard freq

- app/org/maproulette/Config.scala
- app/org/maproulette/jobs/SchedulerActor.scala
- conf/application.conf
For ease of configuration, a staleDate variable is being added to the Archive Challenge job
> add stale date configurability to archiveChallenges job

- conf/evolutions/default/88.sql
These indexes were added manually to staging/prod during this week's performance updates and we need to account for them in an evolution file
> add evolution file for missing indexes

- app/org/maproulette/framework/mixins/ReviewSearchMixin.scala
- app/org/maproulette/framework/mixins/SearchParametersMixin.scala
- app/org/maproulette/framework/model/Task.scala
- app/org/maproulette/jobs/SchedulerActor.scala
- app/org/maproulette/models/dal/mixin/SearchParametersMixin.scala
- app/org/maproulette/session/SearchParameters.scala
on the task review table, this will add capability to filter by "mapped_on" date.
To be released with https://github.com/osmlab/maproulette3/pull/1692
> add mapped_on filter

- .github/workflows/scala.yml
Create a GitHub action to compile the project for all commits to main and dev, and all pull requests.
> Github action to compile the project

- app/controllers/AuthController.scala
- build.sbt
- project/build.properties
- project/plugins.sbt
After seeing the update to the [docker repo](https://github.com/maproulette/maproulette2-docker/commit/d385a5e60ecef54a6393ccdebb74fae7e7dc9a04) I had some issues getting maproulette compiled. 
These changes get the application compiled and running.
> update sbt and play plus its dependents; fix compile error in controller

- .github/workflows/scala.yml
This will incorporate the task batchUpload tests in https://github.com/osmlab/maproulette-java-client anytime a PR is generated in MR2
Requires https://github.com/osmlab/maproulette-java-client/pull/81 in order to pass
> add github actions for java-client CI

- app/org/maproulette/framework/model/TaskLogEntry.scala
- app/org/maproulette/framework/repository/TaskHistoryRepository.scala
add error tags to the task history models for task review history
To be released with https://github.com/osmlab/maproulette3/pull/1749
> add error tags to task history models

- app/org/maproulette/framework/mixins/SearchParametersMixin.scala
- app/org/maproulette/session/SearchParameters.scala
resolves https://github.com/osmlab/maproulette3/issues/1752
> make archive prop optional

- .github/workflows/scala.yml
- project/plugins.sbt
- test/org/maproulette/framework/repository/CommentRepositorySpec.scala
- test/org/maproulette/framework/service/CommentServiceSpec.scala
During CI run the `sbt dependencyTree` and `sbt test`. Note that 8 tests were failing and have been marked to `cancel`.
> Run sbt tests and dependencyTree during CI

- .gitignore
- build.sbt
- project/plugins.sbt
- scala 2.13.10
- sbt-plugin 2.8.18
- swagger-ui 4.14.3
- postgresql 42.5.0
- joda-time 2.12.0
- akka-* 2.6.20
> Update a few dependencies

- app/controllers/AuthController.scala
- app/org/maproulette/Config.scala
- conf/dev.conf.example
resolves https://github.com/osmlab/maproulette3/issues/1745
> store api key in OSM

- build.sbt
Update from jackson 2.11.4 to 2.13.4, fixing some CVEs found in the older version. See https://github.com/orgs/playframework/discussions/11222
> Update to jackson 2.13.4

- app/org/maproulette/framework/controller/UserController.scala
- app/org/maproulette/framework/service/UserService.scala
- conf/v2_route/user.api
This is needed for the super admin metrics project. https://github.com/maproulette/maproulette3/pull/1874
> create users findAll service for superusers

- app/org/maproulette/framework/model/Challenge.scala
- app/org/maproulette/framework/repository/ChallengeRepository.scala
- app/org/maproulette/models/dal/ChallengeDAL.scala
- conf/evolutions/default/90.sql
As part of the changes for https://github.com/maproulette/maproulette3/issues/1823 and https://github.com/maproulette/maproulette3/issues/1849
To be released with https://github.com/maproulette/maproulette3/pull/1909
> remove changeset_url column from challenge db and api

- app/org/maproulette/framework/service/TaskReviewService.scala
to be released with https://github.com/maproulette/maproulette3/pull/1926
> use reviewStartedAt when there's no reviewClaimedAt

- build.sbt
- Set the route files being read/written use UTF-8 encoding
- Create the `format` alias to make it easier for devs to apply auto formatting
- Ensure that reader/writer streams are closed
- Sbt tasks log via the teask stream mechanism
> Improve the sbt swagger routes file generation

- app/org/maproulette/framework/service/TaskReviewService.scala
In the history widget, reviews don't show up on non-primary bundled tasks.  This should fix that.
> apply review_started_at to all tasks in a bundle

- app/org/maproulette/framework/controller/TaskHistoryController.scala
remove mandatory valid session check.
> remove user check for task history

- app/org/maproulette/framework/service/CommentService.scala
- app/org/maproulette/models/dal/ChallengeDAL.scala
- app/org/maproulette/models/dal/TaskDAL.scala
- app/org/maproulette/provider/ChallengeProvider.scala
resolves https://github.com/maproulette/maproulette3/issues/1614
> prevent duplicate notifications of challenge ccompletion

- conf/evolutions/default/48.sql
Related to https://github.com/maproulette/maproulette-backend/issues/1019
> remove concurrently statement

- app/org/maproulette/data/ActionManager.scala
Resolves https://github.com/maproulette/maproulette3/issues/1882
> fix sql to account for commas in c.name

- app/org/maproulette/controllers/CRUDController.scala
Need to check in the CrudController if the element is a Task before checking task count of its parent.
> check class type in internalCreate before checking task count

- app/org/maproulette/framework/controller/CommentController.scala
- app/org/maproulette/framework/model/ChallengeComment.scala
- app/org/maproulette/framework/model/Comment.scala
- app/org/maproulette/framework/repository/ChallengeCommentRepository.scala
- app/org/maproulette/framework/repository/CommentRepository.scala
- app/org/maproulette/framework/service/CommentService.scala
- conf/v2_route/comment.api
Add api endpoints for retrieving sent task and challenge comments for a single user
To be released with https://github.com/maproulette/maproulette3/pull/1997
Resolves https://github.com/maproulette/maproulette3/issues/1789
> Sent comments

- app/org/maproulette/framework/mixins/TaskFilterMixin.scala
- app/org/maproulette/framework/service/TaskClusterService.scala
> filter out deleted/undiscoverable parents for /tasks/box

- app/org/maproulette/framework/repository/ChallengeCommentRepository.scala
- app/org/maproulette/framework/repository/CommentRepository.scala
Switching to more stable scala native SQL prepared queries to prevent sql injections
> revise comment api to use prepared queries

- build.sbt
This commit introduces a dynamic generation mechanism for the routes file in the sbt project. The routes file is now generated only when necessary, i.e., if any of the dependent files have been modified.
The `generateRoutesFile` task has been updated to track the last modified times of the dependent files and the generated routes file. If the routes file doesn't exist or any of the dependent files have been modified since the last build, the routes file is regenerated. Otherwise, if none of the dependent files have changed, the task reports that the Swagger routes file is up to date.
> Generate routes file dynamically based on file modification

- app/org/maproulette/jobs/SchedulerActor.scala
The log messages were inconsistent for scheduled job start/end, which compilicated debugging the service. Switch to a simple log format and apply it to the entry and exist of those tasks.
> Standardize scheduled task start and end log messages

- app/org/maproulette/framework/controller/TaskReviewController.scala
- build.sbt
Formatting fixes, and library implementations to fix issues with commas in the csv
> Tweaks to CollinBeczak/ReviewTableCSV

- app/org/maproulette/framework/service/NotificationService.scala
Changed notifications service to notify all "admin" role managers of a project when comments are made on project challenges.
> Send notifications to all "admin" status users of project when a "get in touch" challenge comment is added

- conf/v2_route/bundle.api
- postman/maproulette2.postman_collection.json
Backend fix for: https://github.com/maproulette/maproulette3/pull/2163
> change unbundleTasks to POST from GET

- app/org/maproulette/framework/controller/TaskHistoryController.scala
- app/org/maproulette/framework/model/TaskLogEntry.scala
- app/org/maproulette/framework/repository/TaskHistoryRepository.scala
- app/org/maproulette/framework/service/TaskReviewService.scala
to be released with https://github.com/maproulette/maproulette3/pull/2242
> add metaReviewedBy object to task history log

- app/org/maproulette/framework/repository/TaskBundleRepository.scala
Issue: Tasks would not unlock when unbundled.
Solution: Move tasks variable above sql conditions that remove tasks from bundle.
> simplify bundling endpoints and fix variable ordering

- app/org/maproulette/provider/ChallengeProvider.scala
- test/org/maproulette/provider/ChallengeProviderSpec.scala
Resolves: https://github.com/maproulette/maproulette3/issues/1761
Also added test for confirmation and to prevent regressions:
Test results before the change:
Key takeaways:
> add test and prevent null values on task name setup

- app/org/maproulette/data/DataManager.scala
Resolves: https://github.com/maproulette/maproulette3/issues/2415
> fix remaining task total in challenges

- CODE_OF_CONDUCT.md
See maproulette/maproulette3#2458.
> Add link to OSM US Code of Conduct

- .github/workflows/docker-publish.yml
Like https://github.com/maproulette/maproulette3/pull/2479, but for the backend.
> Add GH Actions workflow to publish container image to GHCR

- app/org/maproulette/framework/controller/CommentController.scala
- app/org/maproulette/framework/model/Comment.scala
- app/org/maproulette/framework/repository/ChallengeCommentRepository.scala
- app/org/maproulette/framework/repository/CommentRepository.scala
- app/org/maproulette/framework/service/CommentService.scala
- conf/v2_route/comment.api
Quality of life enhancements for Sent Page
- resizable columns
- search filtering
- sort by task status
- sort by task review status
To be released with: https://github.com/maproulette/maproulette3/pull/2582
> Sent box enhancements

- conf/application.conf
resolves: https://github.com/maproulette/maproulette3/issues/2660
> add MR_PUBLIC_ORIGIN environment variable
