app/controllers/Application.scala
app/org/maproulette/Config.scala
app/org/maproulette/controllers/CRUDController.scala
app/org/maproulette/models/dal/BaseDAL.scala
app/org/maproulette/models/dal/ChallengeDAL.scala
app/org/maproulette/models/dal/ProjectDAL.scala
app/org/maproulette/models/dal/SurveyDAL.scala
app/org/maproulette/models/dal/TagDAL.scala
app/org/maproulette/models/dal/TaskDAL.scala
app/org/maproulette/session/SessionManager.scala
conf/application.conf
conf/evolutions/default/1.sql

Primarily performance improvements, on initial tests will import 2000 tasks in 2 seconds, which is down from 2000 tasks in roughly 15 seconds. 
Added some configuration for task reset and session timeout.
Added a task reset functionality that will reset the task status (back to created) if a task is uploaded (with currently the same status) after a set period.

Performance Improvements

---

app/org/maproulette/controllers/api/ChallengeController.scala
app/views/controls/rightSidebar.scala.html
build.sbt
conf/apiv2.routes

There was an issue with deployment that was caused when the MapRouletteV2 distribution package's name was changed due to a version change. I updated the build file to always create the same distribution package name for consistency.
Also added an API call to update all the task priorities.

Changed name of distribution package

---

app/assets/javascripts/mapping.js

This works in both iD and JOSM from in-browser testing. It's possible that it'd be better to urlencode the whole return value instead, but I'm not sure about the particular edge cases there.

#161 url-encode the # in getCommentHashtags

---

README.md

- Add instructions for registering app with OSM to get consumer and secret keys.
- Update the documented environment variable names (which now start with MR_) in Mac and Linux sections, and mention the MR_OSM_SERVER variable for those who wish to connect to a development OSM server. However, there is a `start.sh` script that already exports the appropriate environment variables and runs the server, so I wonder if it'd be better to provide an example script and suggest devs copy it to a (gitignored) file that they customize?
- Include the commands for installing postgresql and postgis via homebrew in Mac section, just for completeness.
- Include sample dev.conf configuration in Using dev.conf section.

Update dev setup instructions in README.

---

app/assets/javascripts/mapping.js
app/assets/stylesheets/mapping.less
app/views/index.scala.html
conf/messages

- Enable hotkeys.
- Add cheat sheet popover that displays available keyboard shortcuts.

Enable hotkeys and add cheat sheet

---

.travis.yml
README.md

The tests are broken, and the Travis build fails. It makes no sense to have Travis CI set up until we fix the tests.

disable travis until we fix the tests

---

app/assets/javascripts/mapping.js

This should address the problem of hot keys interfering with search box input.

Disable hotkeys in input/textarea/select fields.

---

app/views/user/settings.scala.html

It seems that the German translation cannot be selected in the user settings. Probably this settings entry was missing. Please note that I have not tested this addition, but it seems easy enough.

add german to locale settings select

---

app/views/user/settings.scala.html

Fixes compilation error resulting from missed comma in settings
file when the fr translation was added.

Add missed comma in settings file. Fixes #324

---

app/org/maproulette/controllers/api/APIController.scala
app/org/maproulette/session/dal/UserDAL.scala
conf/apiv2.routes

There is currently an API option to save challenges to a user's profile. However there was no unsave option, so a user could only add more and more challenges to it's challenge list. This new API will allow the user to remove challenges from it's saved challenge list. This will not delete any challenges or any data, just remove the reference to that user.

Adding unsave API for users saved challenges

---

conf/evolutions/default/11.sql

There seems to be a bug in Postgis that cannot handle transforming points close to the poles. This will happen very rarely, but in that particular case we will handle the exception and continue on. Otherwise we wouldn't be able to update all the other valid challenges.

Handling exceptions for points around the poles.

---

app/org/maproulette/controllers/api/ChallengeController.scala
app/org/maproulette/controllers/api/TaskController.scala
app/org/maproulette/jobs/Bootstrap.scala
app/org/maproulette/jobs/JobModule.scala
app/org/maproulette/models/dal/TaskDAL.scala
conf/application.conf

Adding job on startup of server that will check that will remove any user except the default super user from the super user group. This makes sure that if the super user accounts are modified between restarts that it will respect the list and not allow users who previously were super users to continue to be super users even when there osm user id was removed from the super user list.
Elevated access to super user when creating tags. Although you don't need the elevated access to associate the tags with the challenges, if you are creating new tags in the process you will need the elevated access.

Fixing some permissions bugs.

---

app/controllers/Application.scala
app/org/maproulette/Config.scala
conf/application.conf
conf/dev.conf
conf/routes

This update will allow for handling the new MR3 frontend. The new frontend can be served in a multitude of ways. Firstly the new frontend is completely separated from the backend and as such can be served to users in a couple of ways. These updates attempt to make it easy to handle it.
The new configuration gives you the following options:
```
mr3 {
devMode=false
host=""
manifest="asset-manifest.json"
manifest=${?MR3_MANIFEST_URI}
staticPath=""
staticPath=${?MR3_STATIC_PATH}
}
```
- devMode - This mode is used when you are developing the frontend and have not packaged the frontend at all.
- host - If you are serving the new frontend outside of the Play framework you would input the host here. You can use this in conjunction with devMode to and set the value to `localhost:3000` which will …

Updates in preparation for handling new MR3 frontend

---

app/controllers/Application.scala
app/org/maproulette/Config.scala
app/org/maproulette/actions/Actions.scala
app/org/maproulette/controllers/api/VirtualChallengeController.scala
app/org/maproulette/jobs/Scheduler.scala
app/org/maproulette/jobs/SchedulerActor.scala
app/org/maproulette/models/VirtualChallenge.scala
app/org/maproulette/models/dal/BaseDAL.scala
app/org/maproulette/models/dal/Locking.scala
app/org/maproulette/models/dal/TaskDAL.scala
app/org/maproulette/models/dal/VirtualChallengeDAL.scala
app/org/maproulette/services/ChallengeService.scala
conf/apiv2.routes
conf/evolutions/default/12.sql
conf/routes
conf/swagger.yml
postman/maproulette2.postman_collection.json

New Object Type included in MapRoulette, the Virtual Challenge (VC).
A VC is a challenge that is created on a temporary basis. It has no project parent and the tasks are made up of tasks from other challenges. Any parameters from the SearchParameter object can be used to filter tasks that make up the VC, however a bounding box is required that is used from the "location" field in the SearchParameters object. Tasks can be retrieved at random like a normal challenge and once retrieved through the random API it will lock the task exactly the same way that it happens for a normal challenge.
As mentioned VC's are temporary, and they will automatically expire and then be deleted from the system. The underlying tasks will remain as children of their parents as per usual. By default the expiry …

Virtual Challenges

---

app/controllers/Application.scala

When interacting with a front-end development server (mr3.devMode=true), the `public/` portion of the asset paths should be left off.

Fix asset paths used in mr3.devMode

---

app/assets/javascripts/main.js
app/assets/javascripts/mapping.js
app/controllers/MappingController.scala
app/org/maproulette/controllers/api/ChallengeController.scala
app/org/maproulette/controllers/api/VirtualChallengeController.scala
app/org/maproulette/jobs/SchedulerActor.scala
app/org/maproulette/models/dal/ChallengeDAL.scala
app/org/maproulette/models/dal/DALManager.scala
app/org/maproulette/models/dal/Locking.scala
app/org/maproulette/models/dal/VirtualChallengeDAL.scala
app/org/maproulette/models/utils/ChallengeFormatters.scala
app/org/maproulette/models/utils/DALHelper.scala
app/org/maproulette/utils/Utils.scala
app/views/mr3.scala.html
conf/apiv2.routes
conf/routes
postman/maproulette2.postman_collection.json

Updating API to handle the proximity option when retrieving random next task that takes proximity into account. There can be unintended side effects with this option that may need to be addressed later. Currently not connected to the UI, purely API call, so use with caution.
Also fixing a bug where the extendedFind API was not honoring the visibility of projects.
This PR now also includes the following:
- New next and previous task API functions for challenges and virtual challenges.
- Updated Postman to test new API functions
- Fixed bug causing location and bounding keys on challenges to be double keyed, so would look like 
```json
"location":{
"location":{
...
}
}
```

Updating proximity API and fixing bug

---

app/org/maproulette/controllers/api/ChallengeController.scala
app/org/maproulette/models/dal/ChallengeDAL.scala
conf/apiv2.routes
conf/application.conf
conf/evolutions/default/13.sql

If a challenge had 10,000+ tasks in it the response would become incredibly slow as it would require all 10,000+ tasks to be serialized to json and respond which just takes a lot of time and can cause issues on the client side as well. So this includes a limit that defaults to 2500 which remains fairly quick but user can increase if so desired. It seems at around 10,000 tasks it takes around 20 seconds to process, whereas 2500 will take just about 2 seconds.
This PR also includes a fix to a typo in the sql script.

Minor bug fixes

---

app/assets/javascripts/mapping.js
app/controllers/FormEditController.scala
app/org/maproulette/controllers/api/ChallengeController.scala
app/org/maproulette/controllers/api/VirtualChallengeController.scala
app/org/maproulette/models/VirtualChallenge.scala
app/org/maproulette/models/dal/VirtualChallengeDAL.scala
app/org/maproulette/services/ChallengeService.scala
conf/apiv2.routes

This PR includes various methods updates the way that geojson is handled to build the tasks for a challenge and virtual challenges. This includes the following:
- Adds API that allows user to create a VirtualChallenge based on specific task ID's instead of search parameters
- Adds new API to allow user to add new tasks to an existing challenge
- Updates the ChallengeService so that when uploading local or remote JSON files it will check if the file is a line by line GeoJSON file. If it is, then it will read each line and create a task for each separate line.
This also fixes an issue in the old UI that messed up the mapping for a challenge URL, and so would never find tasks for that specific challenge. or by very random chance could. This is issue #385

Adding new functionality around building Challenge Tasks.

---

app/org/maproulette/models/Challenge.scala
app/org/maproulette/models/dal/ChallengeDAL.scala
app/org/maproulette/models/utils/ChallengeFormatters.scala
app/org/maproulette/services/ChallengeService.scala
app/views/index.scala.html
conf/evolutions/default/14.sql

So that during failures there is a message included that will explain why the building tasks failed. The object will return with the key "statusMessage" that will always include the last failure. If the current status of the challenge is Failed, then the statusMessage will reflect the reasoning why.
This also includes a banner link in the footer to allow users to try out the new MR3 Beta.

Added status_message for building challenge tasks.

---

app/org/maproulette/Config.scala
app/org/maproulette/controllers/api/DataController.scala
app/org/maproulette/data/DataManager.scala
conf/apiv2.routes

User leaderboard API retrieves the top scoring users based on task
completion over a specified timeframe. The number of points awarded for
each completed task varies depending on the completion status. Each
user's top challenges, based on activity, are also included in the
response.
User top-challenges API retrieves the top challenges, based on user's
activity, over a specified timeframe.

Add user leaderboard and top-challenges APIs

---

app/org/maproulette/jobs/Bootstrap.scala

Log a console warning if the `maproulette.super.accounts` configuration is commented out (or set to ""), rather than attempting to move forward with insertion that results in bad SQL.

Log console warning if no super user configured.

---

app/org/maproulette/data/DataManager.scala

Don't score actions for the leaderboard if the status on the task didn't
change.

No leaderboard credit if no task status change.

---

app/org/maproulette/controllers/api/DataController.scala
app/org/maproulette/data/DataManager.scala
conf/apiv2.routes

New API endpoint retrieves the most recent activity entries for each
challenge regardless of activity date. Useful for supporting a "latest
activity" metric for challenges without having to worry about how far
back to go with a start date.

Add `data/status/latestActivity` API endpoint.

---

app/org/maproulette/models/dal/ChallengeDAL.scala
app/org/maproulette/session/SearchParameters.scala
conf/apiv2.routes

Add support for `cd` query parameter to challenges/extendedFind API for
limiting challenge results by difficulty. Defaults to any difficulty,
preserving existing search behavior in absence of new parameter.

Support challenge difficulty in extendedFind API.

---

app/org/maproulette/session/dal/UserDAL.scala

When adding or removing users to/from a project, fetch user groups as
superuser to avoid security error after the project manager has already
been checked for proper permissions.

Allow project managers to add users to project.

---

app/org/maproulette/controllers/api/ChallengeController.scala
app/org/maproulette/models/Challenge.scala
app/org/maproulette/models/dal/TaskDAL.scala
conf/apiv2.routes

Add `/challenge/:id/tasks/extract` API endpoint that exports summaries
of the tasks in the given challenge as a CSV file, including: task id, challenge id,
task name, status, priority, and username of user who completed the task
(if completed).

Add API for csv export of challenge task summaries

---

app/org/maproulette/models/dal/TaskDAL.scala

Allow challenge owners to set status of their tasks to any value,
ignoring status progression checks.

Ignore task status progression check for managers.

---

app/org/maproulette/controllers/api/UserController.scala
app/org/maproulette/session/User.scala
app/org/maproulette/session/dal/UserDAL.scala
conf/apiv2.routes

Additions and modifications to APIs to help support administration of
project managers:
* Add GET `user/project/:projectId` API for retrieving the managers of a
project.
* Add GET `users/find/:username` API for looking up users by OSM
username. Results are limited to just a few public OSM profile fields.
* Change PUT `/user/project/{projectId}/{groupType}` -- which **adds** a
group type -- to use POST instead.
* Add new PUT `/user/project/{projectId}/{groupType}` that **replaces**
any existing group type with the given group type.
* Modify DELETE `/user/project/{projectId}/{groupType}` to support -1
value for groupType to indicate that all group types should be removed
from the user.

project-manager administration API enhancements.

---

app/org/maproulette/controllers/api/UserController.scala
conf/apiv2.routes

New `user/whoami` API endpoint retrieves information on the currently
logged-in user or generates a 401 if no user is logged in. This can be
useful for determining if the user has logged-out behind the back of a
client front-end (or logged-in as a different user) using an alternative
front-end.

Add `user/whoami` API endpoint

---

app/org/maproulette/session/dal/UserDAL.scala

In the new setUserProjectGroup method, add call to verify that the
project's groups are setup correctly before proceeding.

Verify project groups in new setUserProjectGroup.

---

app/org/maproulette/models/dal/ProjectDAL.scala
app/org/maproulette/session/dal/UserDAL.scala

When verifying a project's groups to ensure they exist, first remove
that project from the cache to avoid an attempt to duplicate the groups
as a result of stale project data.

Remove project from cache before verifying groups.

---

app/org/maproulette/controllers/api/ChallengeController.scala
app/org/maproulette/models/Challenge.scala
app/org/maproulette/models/dal/ChallengeDAL.scala
conf/evolutions/default/18.sql

Add new checkinSource field to challenges for tracking a default
changeset source. This is to support osmlab/maproulette3#361

Add default changeset source field to challenges.

---

app/org/maproulette/exception/MPExceptionUtil.scala

Use alternate form of Redirect that accepts query parameters as a Map to
ensure that error messages are properly url-encoded when redirecting to
`/mr3/error` page. This addresses the "Invalid header value character"
error that could occur during signin as a result of an error message
containing a newline being added to the Location header unencoded
during the redirect.

Urlencode error messages sent to mr3 error page.

---

app/org/maproulette/models/dal/ProjectDAL.scala
app/org/maproulette/session/dal/UserDAL.scala
app/org/maproulette/session/dal/UserGroupDAL.scala
conf/dev.conf
conf/evolutions/default/19.sql

There was a very minor edge case discovered where group names were being duplicated causing the group to not be created because of the unique index on the name column. The name of a group is not required to be unique and has no bearing on the group or the creation of it. So the index was removed. The name of the group that was being created was also moved to the base function, instead of allowing the higher level function to name the group.

Updating group handling

---

app/org/maproulette/models/dal/TagDAL.scala

Fix issue where new tags created with a challenge update weren't being
added to the challenge because they were being retrieved using a
different connection and therefore outside of the transaction with no
visibility of the new tags.

Use same tag-creation connection to retrieve tags.

---

app/org/maproulette/controllers/api/UserController.scala
app/org/maproulette/session/SessionManager.scala
app/org/maproulette/session/User.scala
app/org/maproulette/session/dal/UserDAL.scala

* Store encrypted form of user apiKey (as it appears in database) in cache instead of decrypted form, alleviating the need to explicitly decrypt the apiKey in queries that pull back user data
* Do not allow apiKey to be updated as part of a generic user update; API keys must instead be explicitly reset
* Fixes osmlab/maproulette3#442

Store encrypted form of user apiKey in cache

---

app/org/maproulette/models/Challenge.scala
app/org/maproulette/models/dal/ChallengeDAL.scala
app/org/maproulette/session/User.scala
app/org/maproulette/session/dal/UserDAL.scala
conf/evolutions/default/20.sql

Add `default_basemap_id` to challenges and users that can be used to provide (string) layer identifiers to support additional default basemap layers such as those from the [OSM Editor Layer Index](https://github.com/osmlab/editor-layer-index) project.

Add optional identifier for default basemaps

---

app/org/maproulette/models/Challenge.scala
app/org/maproulette/models/dal/ChallengeDAL.scala
app/org/maproulette/models/utils/ChallengeFormatters.scala
app/org/maproulette/services/ChallengeService.scala
conf/evolutions/default/21.sql

* This is the backend work to address osmlab/maproulette3#468
* Add `last_task_refresh` column to challenges that tracks the date when task data is added to the challenge, and is updated when task data is refreshed from an Overpass query
* The evolution initially sets `last_task_refresh` on existing challenges (that have at least 1 task) to the challenge's `created` date

Add last_task_refresh column to challenges

---

app/org/maproulette/controllers/api/ChallengeController.scala
app/org/maproulette/models/Challenge.scala
app/org/maproulette/models/dal/ChallengeDAL.scala
conf/apiv2.routes

Add `challenges/listing` API endpoint that can be used to retrieve a lightweight listing of challenges across projects, with each challenge entry containing a minimal set of fields (id, parent, name, enabled).
This is to support better administrative visibility into challenges under management, while trying keeping overhead reasonable for users managing a large number of challenges.

Add GET challenges/listing API endpoint

---

app/org/maproulette/controllers/api/ChallengeController.scala
app/org/maproulette/models/Challenge.scala
app/org/maproulette/models/dal/ChallengeDAL.scala
app/org/maproulette/models/dal/TaskDAL.scala
conf/apiv2.routes
conf/evolutions/default/22.sql

* Back-end work to address osmlab/maproulette3#447
* Add migration that adds new popularity column to challenges table and
retroactively computes popularity scores for existing challenges based
on historical task completion activity
* Add `challenges/hot` API endpoint that retrieves the hottest
challenges at present
> Note that the migration takes a little while to run, depending on the number of rows in the status_actions table (I would estimate around 15 minutes per million rows on modern consumer hardware).

Add hotness/popularity scoring to challenges

---

app/org/maproulette/models/Challenge.scala
app/org/maproulette/models/dal/ChallengeDAL.scala
app/org/maproulette/models/dal/TaskDAL.scala
app/org/maproulette/services/ChallengeService.scala
app/views/admin/challenge.scala.html
conf/evolutions/default/23.sql

* Rename STATUS_COMPLETE to STATUS_READY to avoid potential confusion
* setTaskStatus sets challenge status to STATUS_FINISHED if no more tasks
remain with CREATED status
* Add evolution that sets existing challenges to STATUS_FINISHED if their tasks
are all complete

New STATUS_FINISHED for challenges with no more incomplete tasks

---

app/org/maproulette/models/dal/ProjectDAL.scala

Change when finding projects by name to use fuzzySearch for the display_name part of the query.

Change project find to use fuzzySearch for display_name

---

app/org/maproulette/controllers/api/ChallengeController.scala
app/org/maproulette/models/dal/ChallengeDAL.scala
app/org/maproulette/services/ChallengeService.scala
conf/apiv2.routes

* Support new removeUnmatched option in rebuild and upload APIs that,
when set to true, deletes tasks in CREATED or SKIPPED status prior to
performing the rebuild
* Attempt to use feature ids for task names (versus randomly generated
UUIDs) in more situations to better support task rebuilding from various
sources
* Add support for additional feature id fields, such as `@id` and `osmid`

Add option to remove incomplete tasks on rebuild

---

app/org/maproulette/session/dal/UserDAL.scala

When a user logs in the insert method is called on UserDAL
with the OSM xml data. The OSM xml data does not include
any kind of properties so consequently the properties field
was always overwritten to empty in the DB. Since we only
need to store the OSM data with this method we do not need
to insert/update the properties field and can ignore it.

Remove properties from user insert on login. Fixes #481

---

app/org/maproulette/controllers/api/ProjectController.scala
app/org/maproulette/models/dal/ProjectDAL.scala

Fuzzy search was not correctly matching display_names that
fully contained the search query greater than 4 characters.
ie. for a query 'project' the display_name 'kelli project'
was not matching.
Also, added display_name as an order by column when finding
projects.

Fix fuzzy searching on project name

---

app/org/maproulette/controllers/api/ChallengeController.scala
app/org/maproulette/controllers/api/ProjectController.scala
app/org/maproulette/models/dal/BaseDAL.scala
app/org/maproulette/models/dal/ChallengeDAL.scala
app/org/maproulette/models/dal/ProjectDAL.scala
app/org/maproulette/models/utils/DALHelper.scala
app/org/maproulette/session/SearchParameters.scala
conf/apiv2.routes

* Add challenge status as a search parameter for extendedFind. If
a status of -1 is included then it will also return any challenges
with a NULL status.
* Add new parameter to extendedFind for sort order. Before sort
order was included in sort (ie. "name ASC"), now there is a
separate field for order so that we can add a LOWER() around
the name field to make sorting case insensitive

Add Challenge Status search parameter for extendedFind

---

app/org/maproulette/Config.scala
app/org/maproulette/controllers/api/ChallengeController.scala
app/org/maproulette/controllers/api/SurveyController.scala
conf/apiv2.routes
conf/application.conf

* Add column headers to challenge tasks and comments CSV extracts
* Specify CSV extracts as attachments with filenames that include
challenge id
* Add new `publicOrigin` config field that can be used to specify
the public origin of the server for use in generating absolute URLs in
CSV exports
* Make use of new `publicOrigin` config field in challenge comments CSV
export for links to tasks, falling back to prior behavior of using
request host if publicOrigin isn't specified

Add column headers and filename to CSV extracts

---

app/controllers/AuthController.scala

Follow OAuth redirect URL as-is if `mr3.devMode` configuration field is
set to true, allowing decoupling of the front-end and back-end servers
running on different ports. The normal redirection behavior is preserved
outside of dev mode

Allow OAuth redirect to anywhere in mr3 dev mode

---

app/org/maproulette/models/dal/TaskDAL.scala
app/org/maproulette/session/dal/UserDAL.scala

Found bug where user data would not be returned if the user had no score (as is the case with brand new users or users who have not done any work yet.)

Fix new users throw error due to no user score

---

app/org/maproulette/controllers/api/ChallengeController.scala
conf/apiv2.routes

Add method to fetch a consolidated list of preferred challenges. Preferred challenges are most popular, newest and featured.

Add api method to consolidate fetch of preferred challenges

---

app/org/maproulette/controllers/api/ChallengeController.scala
app/org/maproulette/models/dal/ChallengeDAL.scala
app/org/maproulette/models/utils/DALHelper.scala

* Need project data (not just parent id) when calling
fetchPreferredChallenges
* Also, fix order by bug where 'desc' was not working 
(example. fetchNewestChallenges)
* Exclude unusable statuses from find (popular, newest, featured)

Inject project data into new method fetchPreferredChallenges

---

app/org/maproulette/models/dal/Locking.scala

Fixes query that updates lock time -- it was using non-existent 'date' column instead of 'locked_time'.

Fix lock update query

---

conf/apiv2.routes

Add `/challenge/:cid/tasks/prioritizedTasks` API endpoint that delegates
to existing `getRandomTasksWithPriority` to return matching tasks based
on priority, instead of purely by random, with higher-priority tasks being
returned ahead of lower priority tasks

Add prioritizedTasks API endpoint

---

app/org/maproulette/models/Challenge.scala

Fix priority rules using double type by allowing decimals in the
priority rule values (e.g. 99.9)

Allow decimals in priority rule values

---

app/org/maproulette/controllers/api/ChallengeController.scala

When calling "extractComments" or "extractTaskSummaries" a new line was being placed in the middle of the csv data line due to the string interpolation.

Fix weird extract csv newlines

---

conf/evolutions/default/31.sql

Migration sql was not correctly converting the needsReview
flag from boolean to integer as expected

Change migration sql on needsReview default bug

---

app/org/maproulette/controllers/api/TaskController.scala
app/org/maproulette/models/dal/TaskDAL.scala
conf/apiv2.routes

* Add startDate and endDate to search by reviewedAt for getReviewNeeded and getReviewedTasks
* Refactored some of the common review search clauses into a shared private method 
* Fix other minor bugs introduced when task_review table was split off
* Make owner/reviewer search case insensitive

Add to review search methods ability to search by dates

---

app/org/maproulette/models/dal/TaskDAL.scala

When trying to 'modify task' and the SQL function 'create_update_task' was being called, it was throwing a sql error as two of the types were mismatched. Add cast to make these types match as expected. (Fixes #731)

Fix 'modify task' sql error by casting correct type

---

app/org/maproulette/jobs/SchedulerActor.scala

To ensure the user score is accurate over time, add an additional refresh of the user metrics table before taking the user metrics history snapshot.

Add refresh of user metrics before taking history snapshot

---

app/org/maproulette/controllers/api/TaskReviewController.scala
app/org/maproulette/models/dal/TaskDAL.scala
app/org/maproulette/models/dal/TaskReviewDal.scala
conf/apiv2.routes

* Add project search by display_name (ps) to review methods
* Add only saved challenges returned by review needed
* Fix setTaskStatus not updating cache field reviewRequestedBy

Add project search and saved challenges search to review

---

app/org/maproulette/models/dal/TaskReviewDal.scala

After adding project filter, the inner join was joining on projects twice in some cases.

Fix review requested tasks query 

---

app/org/maproulette/models/dal/TaskDAL.scala
conf/evolutions/default/33.sql

* Add unique constraint to task_review table to ensure only one entry
per task_id
* Remove task entry from task_review table when review status is
reset (e.g. because task status is set back to 'created')

Avoid duplicate task_review entries for a task

---

app/org/maproulette/models/dal/ChallengeDAL.scala
conf/evolutions/default/34.sql

* Update project_id on status_actions entries when a challenge is moved to a different project
* Add evolution that ensures existing status_action rows have a current project_id for their challenges

Update project id on status actions when challenge moved

---

app/org/maproulette/controllers/api/DataController.scala
app/org/maproulette/data/DataManager.scala
conf/apiv2.routes

Add ability to return a full project summary that includes both
enabled and not enabled challenges & projects. Default remains
as onlyEnabled so this should not change current behavior.

Add onlyEnabled flag to project summary API

---

app/org/maproulette/data/DataManager.scala
conf/evolutions/default/36.sql

* Add timestamp column 'created' to user_leaderboard so that we can tell when the user leaderboard was last updated.
* In api for leaderboard return created field in json

Add timestamp column to user_leaderboard

---

app/org/maproulette/models/dal/TaskDAL.scala

* Allow users to contest their rejected tasks even if they aren't a reviewer

Bug where only reviewers can contest their rejected tasks

---

app/org/maproulette/models/dal/TaskDAL.scala

When a user is not set to review required then the review status was not being updated in the cache in setTaskStatus.

Fix review status not updating in cache in setTaskStatus

---

app/org/maproulette/models/dal/TaskDAL.scala

* Always perform check to prevent randomly serving up tasks that the
user has recently worked on, rather than only performing the check when
requesting proximate tasks, as the same sort of task loop can occur when
a user is skipping the last task at a priority level

Prevent task loop at priority boundary

---

app/org/maproulette/controllers/api/TaskReviewController.scala
app/org/maproulette/models/dal/TaskReviewDal.scala
conf/apiv2.routes

Add API support for fetching all reviewed tasks. This changed existing review methods by:
- removing 'asReviewer' flag which only fetched as reviewer or as mapper
- adding support for providing ids of mappers and reviewers to filter by
- adding security checks so that only permissible tasks would come back

Add support for all reviewed tasks

---

app/org/maproulette/controllers/api/ChallengeController.scala

When exporting CSV the 'reviewer' column was erroneously showing the 'mapper'

CSV export bug -- reviewer column was wrong

---

app/org/maproulette/models/dal/ChallengeDAL.scala
app/org/maproulette/models/utils/DALHelper.scala

* Support project name (`ps`) in extendedFind challenge searches to
allow further narrowing down of challenge results
* Change `ps` search to use project's display_name instead of name
* Fix missing space if `ps` query clause was added to an existing
WHERE clause

Allow project name in extendedFind search

---

app/org/maproulette/data/DataManager.scala

If a leaderboard request is not using pre-built values in the user_leaderboard table, then it should just return the current timestamp since the data is fresh.

Fix created column for non-prebuilt leaderboard queries

---

app/org/maproulette/controllers/api/ChallengeController.scala
app/org/maproulette/models/Challenge.scala
app/org/maproulette/models/dal/ChallengeDAL.scala

> Note: while making these changes, I discovered that there was a missing parenthesee that caused bad SQL to be generated if a status filter was given, so I suspect that this API endpoint isn't getting much (if any) use at the moment. Also, given the current webserver configuration, any attempt to delete more than a trivial number of tasks would likely result in a gateway timeout.
* Add new DELETING_TASKS challenge status
* Change the `DELETE /challenge/:id/tasks` API endpoint to delete tasks
asynchronously and to change the challenge status to DELETING_TASKS
while the delete operation is ongoing
* Change `ChallengeDal.deleteTasks` to work in small batches
* Add guard conditions to ChallengeController to prevent bulk task
deletion or challenge rebuilds while a deletion or rebuild is …

Delete tasks asynchronously and in batches

---

app/org/maproulette/controllers/api/ChallengeController.scala
app/org/maproulette/controllers/api/DataController.scala
app/org/maproulette/controllers/api/TaskReviewController.scala
app/org/maproulette/data/DataManager.scala
app/org/maproulette/models/Challenge.scala
app/org/maproulette/models/dal/ChallengeDAL.scala
app/org/maproulette/models/dal/TaskDAL.scala
app/org/maproulette/models/dal/TaskReviewDal.scala
app/org/maproulette/models/utils/DALHelper.scala
conf/apiv2.routes
conf/evolutions/default/36.sql
postman/maproulette2.postman_collection.json

* Support for Virtual Projects (#550) (#551)
* Create evolution to add virtual project_challenge join table
and project.is_virtual column
* Create virtual project controller/dal to handle add/remove challenges
* Modify project and challenge queries to use new join table
* Add timestamp column to user_leaderboard (#558)
* Add timestamp column 'created' to user_leaderboard
* In api return created field in json
* Bug where only reviewers can contest their rejected tasks (#557)
* Allow users to contest their rejected tasks even if they
aren't a reviewer
* Fix review status not updating in cache in setTaskStatus (#556)
* Add virtual projects to challenges listing project filter (#555)
* Prevent task loop at priority boundary (#554)
* Always include check to prevent randomly serving up tasks …

merge to dev

---

app/org/maproulette/controllers/api/ChallengeController.scala
conf/apiv2.routes

* Support optional proximityId parameter in GET
`challenge/:cid/tasks/prioritizedTasks` API endpoint so that nearby tasks
can be retrieved while honoring task priority

Support proximityId in prioritizedTasks API

---

app/org/maproulette/session/dal/UserDAL.scala

Add count for tasks awaiting review in a "requested" state in the fetch for user metrics. With this count the returned fields add up to the total.

Add count for reviews in requested state to user metrics.

---

app/org/maproulette/models/dal/TaskDAL.scala

Modified date does get updated during setTaskStatus but the new timestamp isn't updated in the cache so a subsequent call to get the task details does not correctly show an updated modified time.

Update modified date in cache in setTaskStatus

---

app/org/maproulette/controllers/api/TagsMixin.scala
app/org/maproulette/models/dal/TagDAL.scala
app/org/maproulette/models/dal/TagDALMixin.scala
conf/apiv2.routes
postman/maproulette2.postman_collection.json

Normal users need to be able to add/modify task tags. Add api to only modify tags (not full task or challenge)

Add API for normal user to update task tags

---

app/org/maproulette/models/dal/ChallengeDAL.scala

Missed FalsePositive status when adding the translation in SQL from Integer to text status.

Add FalsePositive status to geoJSON status translations

---

app/org/maproulette/controllers/api/TagsMixin.scala
app/org/maproulette/models/dal/TagDAL.scala

Changing the unique constraints introduced a bug which caused the postman tests to fail. Fix tag creation insert sql statement.

Fix tag creation postman tests failing.

---

app/org/maproulette/models/dal/ChallengeDAL.scala
app/org/maproulette/models/dal/TaskDAL.scala
conf/evolutions/default/39.sql
scripts/39_upgrade.py
scripts/39_upgrade.sql
test/org/maproulette/cache/CacheSpec.scala

For the 3.6.0 release we are migrating geometry data from the task_geometries table to the tasks table. This turns out to be quite a long process, so to alleviate the pain of a major migration I had added lazy migration into the code. This will then migrate the geometry data as it is requested. Which for an individual task only takes a couple 100 milliseconds and only has to happen once. Even for challenges when requesting challenge geometry it will update the whole challenge in the background. This could potentially cause momentary performance degradation, but again it only has to happen once.

Adding Lazy Load Migration

---

app/org/maproulette/controllers/api/ChallengeController.scala

* When adding an LxL file to a challenge, handle missing challenge
status in guard checks

Handle missing challenge status on LxL upload

---

app/org/maproulette/models/Task.scala
app/org/maproulette/models/dal/ChallengeDAL.scala
app/org/maproulette/models/dal/TaskDAL.scala

New 'Disabled' status mimics delete but are for those tasks that are not to be worked on right now but may be relevant in the future.

Add new task status 'disabled'

---

app/org/maproulette/controllers/api/ChallengeController.scala
app/org/maproulette/controllers/api/TaskController.scala
app/org/maproulette/models/Challenge.scala
app/org/maproulette/models/Task.scala
app/org/maproulette/models/dal/ChallengeDAL.scala
app/org/maproulette/models/dal/TaskDAL.scala
conf/apiv2.routes
conf/evolutions/default/42.sql

Add support for addtional response data on completion.
* Add additional column to database to store "completion_responses"
* When setTaskStatus is called allow json key/value pairs to be passed in body and stored in new field
* Return completionResponses when asking for task data
* Exporting CSV and geojson to also include this new property
Add support for exportableProperties in CSV
* Add column for 'exportable_properties' as a comma separated list
* Any task feature properties that match will be exported in the CSV

Add completion responses in instructions and exportable feature properties in CSV

---

app/org/maproulette/controllers/api/ChallengeController.scala
app/org/maproulette/controllers/api/TaskController.scala
app/org/maproulette/controllers/api/TaskReviewController.scala
app/org/maproulette/data/Actions.scala
app/org/maproulette/models/Bundle.scala
app/org/maproulette/models/ClusteredPoint.scala
app/org/maproulette/models/Task.scala
app/org/maproulette/models/dal/ChallengeDAL.scala
app/org/maproulette/models/dal/ProjectDAL.scala
app/org/maproulette/models/dal/TaskDAL.scala
app/org/maproulette/models/dal/TaskReviewDal.scala
app/org/maproulette/models/dal/VirtualChallengeDAL.scala
app/org/maproulette/permissions/Permission.scala
conf/apiv2.routes
conf/evolutions/default/43.sql
postman/maproulette2.postman_collection.json

* Add createTaskBundle
* Add setTaskBundleStatus which takes in bundleId and primaryId and
runs through all tasks in bundle to setTaskStatus
* Add getTaskBundle returns a TaskBundle with associated tasks
* Task now returns bundldId and isBundlePrimary properties
* Add setBundleTaskReview which will loop through each task and
call setTaskReview
* Review queries will only return the primary task in a bundle
* addCommentToBundleTasks - adds comments to each task
in bundle
* deleteTaskBundle - will delete task bundle and unlock
all tasks but primary task id
* unbundleTasks - removes and unlocks tasks from bundle
* Support a new optional flag allowing tasks locked by the requesting
user to be excluded from the results of the nearby-tasks API (tasks
locked by others are always excluded)
* …

Add support for task bundles (Mulit-task Completion)

---

app/org/maproulette/models/dal/TaskDAL.scala
postman/maproulette2.postman_collection.json

* Disallow tasks with suggested fixes to be bundled
* Disallow tasks from separate challenges to be bundled
* Disallow tasks already assigned a bundleId to be added to
a different bundle
* In setTaskStatus also disallow suggested fix tasks to be
assigned a bundle id and assigned a status if already part
of a different bundle

Add task checks when creating task bundles.

---

app/org/maproulette/models/dal/TaskDAL.scala

When fetching next tasks to work on, we only return tasks that
the user has not worked on in the last hour. If the task's
status is reset back to created this limit still applies. Do
not require an hour wait limit if the task is in a created
status so it can be worked on right away in this instance.

Remove hour wait for tasks in created status when fetching next

---

app/org/maproulette/models/dal/TaskDAL.scala

If doing a bulk update of task statuses then remove from
any bundles that the tasks are a part of and also other
tasks in the bundle.

On bulk status update remove tasks from affected bundles

---

app/org/maproulette/controllers/api/ChallengeController.scala
app/org/maproulette/controllers/api/TaskController.scala
app/org/maproulette/models/dal/ChallengeDAL.scala
app/org/maproulette/models/dal/TaskDAL.scala
app/org/maproulette/models/dal/VirtualChallengeDAL.scala
conf/apiv2.routes

Change challenge/getClusteredPoints and getTasksInBoundingBox to accept an option excludeLocked parameter that will exclude locked tasks from the tasks returned. By default
the flag is set to false thereby preserving current behavior.

Add flag to exclude locked tasks from cluster methods

---

app/org/maproulette/data/DataManager.scala

In getChallengeSummary it is possible to have no results and get a divide by 0 error in the SQL.

Add check to SQL to prevent divide by 0 error

---

app/org/maproulette/controllers/api/TaskController.scala
app/org/maproulette/controllers/api/TaskHistoryController.scala
app/org/maproulette/controllers/api/TaskReviewController.scala
app/org/maproulette/models/dal/TaskDAL.scala
app/org/maproulette/provider/websockets/README.md
app/org/maproulette/provider/websockets/WebSocketActor.scala
app/org/maproulette/provider/websockets/WebSocketMessages.scala
app/org/maproulette/provider/websockets/WebSocketProvider.scala

* Support new websocket messages for notifying subscribed clients when
tasks are claimed, released, or completed
* Clients can subscribe to messages for all tasks or to just tasks in a
specified challenge
* Enhance websocket system to allow multiple messages to be emitted
simultaneously from a single event, useful for supporting multiple
levels of client subscription granularity (e.g. all tasks plus tasks
specific to a challenge)
* Update websocket README with basic outline for adding a new message
type

Emit websocket messages for task actions

---

app/org/maproulette/models/Task.scala
app/org/maproulette/models/dal/ChallengeDAL.scala
app/org/maproulette/provider/ChallengeProvider.scala

Error was reported that some challenges were throwing an exception when fetching the clustered tasks. This was caused by bad data. Fixed by 1. filtering out these bad tasks and 2. when a challenge is created skipping creating tasks that have empty coordinates.

Filter out clustered points with no coordinates to prevent exception.

---

app/org/maproulette/models/Challenge.scala
app/org/maproulette/models/dal/ChallengeDAL.scala
app/org/maproulette/models/utils/ChallengeFormatters.scala
conf/evolutions/default/44.sql

* Add new column on challenge data_origin_date
* When creating a challenge, this field can be include to indicate when the data was sourced
* LastTaskRefresh is now always updated when tasks are rebuilt

Add support for a challenge data origin date.

---

app/org/maproulette/models/Task.scala
app/org/maproulette/models/dal/ChallengeDAL.scala
app/org/maproulette/provider/ChallengeProvider.scala

* Recently-added check for empty task geometry was too aggressive, causing creation of some valid challenges to fail, so simply `git revert` that commit for now -- we can revisit the missing-geometry checks at another time
* This reverts commit f98aebae400d31eb973f81233eabf3f130f72541

Revert "Filter out clustered points with no coordinates"

---

app/org/maproulette/controllers/api/ChallengeController.scala

* Escape all quotes so the CSV isn't confused in fields:
Comments, properties and response data.

Escape quotes and commas in csv export

---

app/org/maproulette/models/dal/ChallengeDAL.scala
app/org/maproulette/models/dal/TaskDAL.scala
conf/evolutions/default/45.sql

* Set challenge to FINISHED status if it has tasks and no tasks are left
remaining in CREATED or SKIPPED statuses
* No longer require that challenge is in READY status to transition to
FINISHED, as many challenges created solely through the API never enter
READY status
* No longer allow challenge to be marked FINISHED if it contains SKIPPED
tasks
* No longer allow a challenge to be marked FINISHED if it contains no
tasks at all
* Add evolution that applies the new criteria to existing challenges

Adjust rules for setting a challenge to FINISHED

---

app/org/maproulette/controllers/api/ChallengeController.scala

When exporting task properties in the csv, the JSValues
were always being wrapped in quotes which would cause
problems if the value itself had \"value\".

Fix csv export with quoted export properties

---

app/org/maproulette/controllers/api/ChallengeController.scala
app/org/maproulette/controllers/api/DataController.scala
app/org/maproulette/controllers/api/TaskController.scala
app/org/maproulette/controllers/api/VirtualChallengeController.scala
app/org/maproulette/data/DataManager.scala
app/org/maproulette/models/TaskCluster.scala
app/org/maproulette/models/dal/ChallengeDAL.scala
app/org/maproulette/models/dal/ProjectDAL.scala
app/org/maproulette/models/dal/TaskDAL.scala
app/org/maproulette/models/dal/TaskReviewDal.scala
app/org/maproulette/models/dal/VirtualChallengeDAL.scala
app/org/maproulette/models/utils/DALHelper.scala
app/org/maproulette/session/SearchParameters.scala
app/org/maproulette/utils/Utils.scala
conf/apiv2.routes
postman/maproulette2.postman_collection.json

* Modify getTaskClusters to search by parameters
* Modify getTasksInBoundingBox to search by parameters
* Add new search property taskProperties which will search
by the geojson task properties. Note: Since SearchParameters
was reaching the Scala 22 parameter limit, challenge parameters
were moved into their own subclass.
* Add API to get list of valid task proeprties for a challenge

Add taskProperty search and make cluster fetch use parameters

---

app/org/maproulette/models/dal/TaskDAL.scala
app/org/maproulette/session/SearchParameters.scala

Add support for 'equals', 'not_equals', 'contains' when searching
task properties (default is equals). New url search parameters is:
tPropsSearchType

Add task property search type when property searching

---

app/org/maproulette/controllers/api/ChallengeController.scala
app/org/maproulette/models/dal/ChallengeDAL.scala
conf/apiv2.routes

* When uploading file tasks, allow an optional dataOriginDate
that will be updated on the Challenge.

Add optional dataOriginDate to upload file tasks

---

app/org/maproulette/controllers/api/ChallengeController.scala
app/org/maproulette/models/dal/TaskDAL.scala

Improve performance of retrieveTaskSummary query by performing comments fetch as a separate query with comments returned as a separate map instead of as part of the TaskSummary object.
(Sample query on 6k tasks went from 38s to 2s by removing comments)
This should address issue: https://github.com/osmlab/maproulette3/issues/970

Improve performance of retrieveTaskSummary query

---

app/org/maproulette/models/TaskCluster.scala
app/org/maproulette/models/dal/TaskDAL.scala
app/org/maproulette/models/dal/TaskReviewDal.scala
app/org/maproulette/models/utils/DALHelper.scala

* Support searching by challenge difficulty, challenge status,
project/challenge enabled and deleted.
* Return in task clusters challengeIds for the tasks represented
by the points in the cluster.

Support additional search parameters when fetching task clusters

---

app/org/maproulette/controllers/api/TagsMixin.scala
app/org/maproulette/controllers/api/TaskController.scala
postman/maproulette2.postman_collection.json

* Task tags are now included in JSON response when fetching tasks
* When updating a task, if no tags are specified then the existing tags will be
left as-is instead of being deleted
* When updating a task, if tags are explicitly specified then those tags will
overwrite existing tags
* When updating a task, if empty tags are explicitly specified (as opposed to
omitted entirely from the JSON body) then any existing tags will be removed
* When updating a task, tags can now be provided as either an array of strings
or as a single string of comma-separated tags
* Add additional postman tests

Adjust handling of task tags in API

---

app/org/maproulette/models/dal/TaskReviewDal.scala

Restrict review task clusters to not include any bundled tasks that are not the primary in the bundle.

Review Task Clusters should not include non-primary bundle tasks

---

app/org/maproulette/controllers/api/ChallengeController.scala
app/org/maproulette/controllers/api/TaskController.scala
app/org/maproulette/models/ClusteredPoint.scala
app/org/maproulette/models/dal/ChallengeDAL.scala
app/org/maproulette/models/dal/TaskDAL.scala
app/org/maproulette/models/dal/VirtualChallengeDAL.scala

* Change ClusteredPoint PointReview to use longs for reviewedBy
and reviewRequestedBy (these should have been longs before)
* When fetching getTasksInBoundingBox insert extra username info
into the ClusterPoint.pointReview field for reviewedBy and
reviewRequestedBy

Change getTasksInBoundingBox to return review info usernames

---

app/org/maproulette/Config.scala
app/org/maproulette/controllers/api/TaskController.scala
app/org/maproulette/jobs/SchedulerActor.scala
app/org/maproulette/models/dal/Locking.scala
conf/apiv2.routes
conf/evolutions/default/46.sql
postman/maproulette2.postman_collection.json

* Add `task/:id/refreshLock` API endpoint for refreshing an active
task lock, thereby extending its allowed duration
* Add `refreshItemLock` method to Locking trait that updates the lock's
`locked_time` to the current time
* Add evolution that adds `created` column to `locked` table for
tracking the creation time of the lock, allowing the total lock duration
to be tracked even if a lock is refreshed multiple times
* Add basic Postman tests for starting a task, refreshing the task lock,
and releasing the task lock

Add API for refreshing task locks

---

app/org/maproulette/session/SearchParameters.scala
app/org/maproulette/utils/Utils.scala

As the separator for property filter keys/values is a ':' and
property key names can contain ':'s -- now require these values
to be Base64 encoded.

Decode task property filter keys/values

---

app/org/maproulette/models/dal/ChallengeDAL.scala

* Fix incorrect offset calculation and termination condition when
iterating over challenge children during application of updated priority
rules, which were causing only the first 1000 tasks in a challenge to be
reprioritized
* Fixes osmlab/maproulette3#999

Ensure priority rule changes applied to all tasks

---

app/org/maproulette/models/dal/TaskDAL.scala

When fetching tasks in bounding box, the sort columns needed to be translated for review columns to the actual column names in the query.

Fix sorting by review columns when fetching tasks in bbox

---

app/org/maproulette/models/NotificationDAL.scala
app/org/maproulette/models/UserNotification.scala
app/org/maproulette/models/dal/ChallengeDAL.scala
app/org/maproulette/models/dal/SurveyDAL.scala
app/org/maproulette/session/User.scala
app/org/maproulette/session/dal/UserDAL.scala
conf/evolutions/default/47.sql

* Add new challenge_completed notification type and generate the
notification for all subscribed managers of a challenge when the
challenge is completed
* Enhance ProjectManager to include a userId in addition to the osmId

Notify challenge managers when challenge completed

---

app/org/maproulette/models/dal/VirtualProjectDAL.scala
conf/evolutions/default/48.sql

* Add unique constraint to virtual_project_challenges so that
the same challenge can't be added to the same virtual project
more than once.
* Remove existing duplicate entries.
* In the addChallenge method, don't do the sql insert if the
challenge has already been added.

Add unique constraint to table virtual_project_challenges

---

app/org/maproulette/controllers/api/ChallengeController.scala
app/org/maproulette/models/dal/TaskDAL.scala
conf/apiv2.routes

* Add new api to download all tasks from a project with optional list of challengeIds to include. (Functions the same as downloading all challenge tasks but let's an admin download all (or select) challenges from a project.)

Add ability to download all project tasks in CSV

---

app/org/maproulette/controllers/api/VirtualChallengeController.scala
app/org/maproulette/models/dal/TaskDAL.scala
app/org/maproulette/session/SearchParameters.scala
app/org/maproulette/session/TaskPropertySearch.scala
conf/apiv2.routes
postman/maproulette2.postman_collection.json

* Add search parameter for json taskPropertySearch to do complex
task property searches
* Add PUT methods for taskCluster and tasksInBoundingBox to support
providing a JSON body.
* Example taskPropertySearch format:
`
{
"taskPropertySearch": {
"operationType": "or",
"left": {
"key": "id",
"value": "test1''",
"valueType": "string",
"searchType": "equals"
},
"right": {
"operationType": "and",
"left": {
"key": "id",
"value": "test",
"valueType": "string",
"searchType": "contains"
},
"right": {
"key": "version",
"value": "0",
"valueType": "number",
"searchType": "greater_than"
}
}
}
}
`
will produce SQL like:
`("id" = "test1") OR ("id" LIKE "%test%" AND "version" > 0)`

Add support for nested task property searches

---

app/org/maproulette/controllers/api/TaskReviewController.scala
app/org/maproulette/models/dal/TaskReviewDal.scala
conf/apiv2.routes

When requesting nextTaskReview add support for providing the
last task seen so that the task following that one will be
served up next. (Thus allowing for 'skipping')

Add support for 'lastTaskId' on nextTaskReview

---

app/org/maproulette/models/NotificationDAL.scala
app/org/maproulette/models/UserNotification.scala
app/org/maproulette/provider/EmailProvider.scala

* Include data from "extra" notification field in emails sent to
notification recipients
* Add name of challenge and parent project to "extra" portion of
challenge-completion notifications so that they'll be included in
notification emails

Include extra details in notification emails

---

app/org/maproulette/controllers/api/TaskReviewController.scala
app/org/maproulette/models/dal/TaskReviewDal.scala
conf/apiv2.routes

* Add excludeOtherReviewers flag when fetching reviewRequestedTasks (default is false). This
include: metrics, clusters, getReviewRequested, and nextTaskReview
* Fix duplicating of review tasks in results when not a super user
but project contains multiple administrators.

Add flag to exclude tasks done by other reviewers from review requested tasks

---

app/org/maproulette/controllers/api/UserController.scala
app/org/maproulette/models/dal/TaskDAL.scala
app/org/maproulette/session/dal/UserDAL.scala
conf/apiv2.routes

* for fetchUserMetrics also return a break down of reviewed
tasks where the user is the reviewer in new field "asReviewerTask"
* add new reviewerDuration to indicate what timeframe to fetch
for the reviewer stats
* fixed when a task was disputed a record was not being entered in the
task_review_history.

Fetch as reviewer metrics when fetching user metrics

---

app/org/maproulette/models/TaskCluster.scala
app/org/maproulette/models/dal/TaskDAL.scala
app/org/maproulette/models/dal/TaskReviewDal.scala

* Include task geometry in task clusters that represent a single task
* Support task geometries in results of getReviewTaskClusters
* Refactor TaskDal.getTaskClusters and
TaskReviewDal.getReviewTaskClusters to share query and parser

Include task geometry in task clusters of 1 task

---

app/org/maproulette/controllers/api/DataController.scala
conf/apiv2.routes

* Add new flag to getProjectSummary called getChallengeSummary
'includeByPriority' which will return a field 'priorityActions'
that maps priority to the summarized actions just for that priority.
Example return:
[{"name":"Winthrop Challenge",
"id":4070,
"actions": 
{"total":110,
"available":82,
"fixed":8, etc.},
"priorityActions": 
{"2":
{"total":0,
"available":0,
"fixed":0, etc.},
"1":
{"total":108,
"available":81,
"fixed":8, etc.},
"0":
{"total":2,
"available":1, etc.}
}
}]

Add support for including progress by priority.

---

app/org/maproulette/controllers/api/ChallengeController.scala
app/org/maproulette/provider/ChallengeProvider.scala
conf/evolutions/default/49.sql

This fixes a recently introduced bug (not released) that would cause a match failure in the ChallengeController. 
It also refactors the name resolution code for tasks in geojson and adds a new name field "osm_id". With the refactor it allows an easier way to add new name fields, although there shouldn't be a huge requirement to add this a lot.
Updates the reset mechanism for Tasks so that tasks in the state DISABLED and FALSE_POSITIVE (or "not an issue" as it is displayed in the UI) will not be reset to CREATED if the reset interval criteria is met.

Minor code updates and fixes.

---

app/org/maproulette/session/dal/UserDAL.scala

When requesting user metrics for current month (or 0) the correct
start date was not being calculated.

Fix current-month not correct for user metrics.

---

app/org/maproulette/models/Challenge.scala
app/org/maproulette/models/dal/ChallengeDAL.scala
app/org/maproulette/provider/ChallengeProvider.scala
conf/evolutions/default/50.sql

* Add a new `osmIdProperty` field to challenges that allow challenge
managers to specify which property to inspect when determining the id of
the task
* Use the specified property (if given) when determining the task name

Allow OSM id task property to be specified

---

app/org/maproulette/controllers/api/UserController.scala
conf/apiv2.routes

> Note: this represents a breaking change to the API that will require
clients who currently pass OSM user ids to the project manager APIs to
update their code to include a new `isOSMUserId=true` query parameter.
Clients that are exclusively passing MapRoulette user ids are unaffected.
* Add new `isOSMUserId` boolean parameter to project manager API
endpoints that must now be explicitly provided for the given user id(s) to
be treated as an OSM user id(s)
* If `isOSMUserId` is not expicitly set to true in request, treat given
user id(s) as internal MapRoulette ids only
* This new requirement eliminates the potential of erroneously acting on
the wrong target user in the case where a given id matches both internal
and OSM user ids

Add isOSMUserId param to project manager APIs

---

app/org/maproulette/models/Challenge.scala
app/org/maproulette/models/dal/ChallengeDAL.scala
conf/evolutions/default/52.sql

Add field to Challenge to support a comma separated string
of 'preferredTags' on the challenge that the challenge owner
would like the user to use on task completion.
Requires evolution.

Add support for preferred task tags on challenge

---

app/org/maproulette/data/DataManager.scala
app/org/maproulette/models/dal/TaskDAL.scala
app/org/maproulette/models/dal/TaskReviewDal.scala
app/org/maproulette/session/SearchParameters.scala

* When fetching task clusters and tasks in bounding box support
searching by a task id, reviewed by, and review requested by
* When fetching metrics support searching by reviewed by and
review requested by and task id
* When doing a review search support searching by task id

Additional support for searching by task id, review requested by and reviewer 

---

app/org/maproulette/controllers/api/ChallengeController.scala
app/org/maproulette/models/dal/ChallengeDAL.scala
app/org/maproulette/models/dal/TaskDAL.scala
app/org/maproulette/session/SearchParameters.scala
conf/apiv2.routes

* When exporting CSV (tasks/extract) support additional
filters: taskPropertySearch, taskId, reviewer, owner
* When exporting challenge geojson support additional
filters: taskPropertySearch, taskId, reviwewer, owner
Since taskPropertySearch is a json object, added
api for POST of this data so it can be downloaded with
an HTML Form ```<form>```.

Add support for additional filters when exporting

---

app/org/maproulette/controllers/api/ChallengeController.scala
conf/apiv2.routes

* Add additional query parameter 'exportProperties' to include
when generating the csv (in addition to ones already defined
on challenge)
* Also fix params parameter passed into retrieveTaskSummaries

Add 'exportProperties' to be specified when exporting csv

---

app/org/maproulette/models/dal/TaskDAL.scala
conf/evolutions/default/53.sql

When setting a task status back to created delete any corresponding task_review entries. This is applicable when rebuildTasks, setStatus, update task.

Delete task_review entry when task set back to created

---

app/org/maproulette/controllers/api/TaskReviewController.scala
app/org/maproulette/models/dal/TaskReviewDal.scala
conf/apiv2.routes

* Add optional flag "includeByPriority" to fetch review metrics
to also include results broken down by priority. When false,
results will be as before. When true, it will look as follows:
```
{reviewActions:{total:X,reviewRequested:X,....}
priorityReviewActions:{
0: {total:X,reviewRequested:X....},
1: {total:X,reviewRequested:X....},
2: {total:X,reviewRequested:X....}}
}
```

Include by priority when fetching review stats.

---

app/org/maproulette/provider/ChallengeProvider.scala

When uploading tasks and determining the name from the json, numeric values were not being recognized even when provided on the "id", "@id", "osmid", etc. fields.

Recognize numeric values when determining task name from json

---

app/org/maproulette/models/dal/ProjectDAL.scala

* Switch to using inner join to speed up query that fetches projects
that a user can manage
On my local machine this speeds up the query from 4221.132 ms to 7.266 ms.
Before:
```
QUERY PLAN
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Limit  (cost=335409.54..335411.29 rows=50 width=156) (actual time=4196.722..4214.281 rows=4 loops=1)
->  Unique  (cost=335409.54..335554.30 rows=4136 width=156) (actual time=4196.722..4214.280 rows=4 loops=1)
->  Sort  (cost=335409.54..335419.88 rows=4136 width=156) (actual time=4196.721..4202.973 rows=16636 loops=1)
Sort Key: (lower((p.display_name)::text)), p.name, p.id, p.created, p.modified, …
```

Speed up query in managed project listing

---

app/org/maproulette/controllers/api/UserController.scala
app/org/maproulette/session/dal/UserDAL.scala
conf/apiv2.routes

Add custom date ranges for user metrics:
- For tasks: start, end
- For Reviewed tasks: reviewStart, reviewEnd
- For As Reviewer: reviewerStart, reviewerEnd
Note: Month duration is still supported. We could
deprecate month duration values and the client could
return the same data by doing the start/end calculations
themeselves.

Support custom dates for user metrics.

---

app/org/maproulette/controllers/api/UserController.scala
app/org/maproulette/session/SessionManager.scala
app/org/maproulette/session/dal/UserDAL.scala

* Remove requirement that requesting user has read access to target user
being fetched by OSM id, bringing it in line with requirements for
fetching a user by internal id
* Fixes security errors when trying to add managers via OSM id to a
project

Don't require permission to fetch user by OSM id

---

app/org/maproulette/controllers/OSMChangesetController.scala
app/org/maproulette/controllers/api/TaskController.scala
app/org/maproulette/provider/osm/ChangeObjects.scala
app/org/maproulette/provider/osm/ChangesetProvider.scala
conf/apiv2.routes

* Add support for general suggested fix that include geometry
and tag changes
* For now, creation of nodes is the only supported geometry fix
* Preserve old tag-specific suggested fixes and API endpoints for
backward compatibility
* Add two new API endpoints for general suggested fixes: POST
`/change/test` to test a change and POST
`/task/:taskId/suggestedFix/apply` to apply a change to a task and
submit to OSM

Support geometry changes in suggested fixes

---

app/org/maproulette/models/dal/mixin/SearchParametersMixin.scala
app/org/maproulette/session/SearchParameters.scala
app/org/maproulette/session/TaskPropertySearch.scala

Add support for "missing" and "exists" task property search types. (ie: "building" exists or "building" missing)

Add task property filters search types 'exists' and 'missing'

---

app/org/maproulette/provider/ChallengeProvider.scala

* When determining the task name, explicitly convert numeric feature ids
to strings instead of simply always running the feature id through
JsValue.toString to normalize it, as that was causing quotes to be added
into string values (e.g.  `node/1234` was becoming `"node/1234"`)

Fix quotes being stored in task names

---

app/org/maproulette/models/dal/TaskDAL.scala
conf/evolutions/default/57.sql

* Rebuild tasks would always change status back to created
for all tasks. Change to not update status for tasks that
have been mofiied since the reset interval
* Fix task_review ending up with empty rows when a task
with a review request is set back to created.

Fix rebuild tasks erroneously updating status

---

app/org/maproulette/models/dal/TaskReviewDAL.scala

* If a task is rejected in review and immediately viewed by the
mapper they would still see it as awaiting review until cache
is refreshed. Wrong cacheManager was being updated.

Fix caching on setTaskReviewStatus

---

app/org/maproulette/models/dal/TaskDAL.scala

If the task status has changed following a review rejection,
notify the reviewer that a re-review is needed.

Notify reviewer of re-review on task status change

---

app/org/maproulette/models/Challenge.scala
app/org/maproulette/models/dal/ChallengeDAL.scala
app/org/maproulette/models/dal/mixin/SearchParametersMixin.scala
app/org/maproulette/session/SearchParameters.scala
conf/evolutions/default/58.sql

* Add 'requires_local' column to challenges
* Default is to not return requiresLocal challenges when
searching.
* Local challenges not included in featured/popular/new
* SearchParameter cLocal will search on 'requires_local':
0 - Exclude local
1 - Include local
2 - Return only local

Add 'requires_local' column to challenges

---

app/org/maproulette/models/dal/TaskDAL.scala
app/org/maproulette/models/dal/TaskReviewDAL.scala
app/org/maproulette/session/dal/UserDAL.scala

If database and server are running on separate machines and
the machines have different time then the time spent calculation
would be off -- change time spent calculations to only use
db times.

Fix time spent calculation to only use db time not server time

---

app/org/maproulette/models/TaskLogEntry.scala
app/org/maproulette/models/dal/TaskHistoryDAL.scala
conf/evolutions/default/59.sql

* When doing an update of the task through the stored procedure,
add an entry into the status actions table.
* When fetching task history include update actions as well so
that it can be shown when an admin updates a task.

Add status action entry on task update

---

app/org/maproulette/controllers/api/TaskController.scala
app/org/maproulette/models/dal/TaskDAL.scala

If a challenge is 'finished' but a new task is added, the status
needs to be set back to 'ready'

Update challenge status after adding new task

---

app/org/maproulette/framework/repository/UserRepository.scala
app/org/maproulette/framework/service/ProjectService.scala
test/org/maproulette/framework/UserSpec.scala
test/org/maproulette/framework/util/FrameworkHelper.scala

This is simply to fix the issue where None is sent to the function getUsersManagingProject. Also updated some of the users spec tests to handle this use case.

Fixing issue when filter on get managing users set to None

---

app/org/maproulette/models/dal/TaskDAL.scala

Remove created/updated task from cache after database update
since it may have incomplete data.

Remove updated task from cache after update

---

app/org/maproulette/controllers/api/TaskController.scala

IllegalAccessError when attempting to remove a review request on a
task with no review request.

Fix error when attempting to remove review when no review

---

app/org/maproulette/controllers/api/TaskController.scala
conf/route/v2.api

* Remove API endpoint previously used to apply suggested fixes
containing simple geometry fixes, as going forward these will be handled
through the upcoming "cooperative challenges" functionality
* Application of suggested fixes containing tag fixes uses a different
API endpoint and is unchanged

Remove `/task/:taskId/suggestedFix/apply` API

---

app/org/maproulette/controllers/api/ChallengeController.scala
app/org/maproulette/controllers/api/TaskController.scala
app/org/maproulette/framework/model/Challenge.scala
app/org/maproulette/framework/repository/ChallengeRepository.scala
app/org/maproulette/models/ClusteredPoint.scala
app/org/maproulette/models/Task.scala
app/org/maproulette/models/dal/ChallengeDAL.scala
app/org/maproulette/models/dal/TaskBundleDAL.scala
app/org/maproulette/models/dal/TaskClusterDAL.scala
app/org/maproulette/models/dal/TaskDAL.scala
app/org/maproulette/models/dal/TaskReviewDAL.scala
app/org/maproulette/models/dal/VirtualChallengeDAL.scala
conf/evolutions/default/61.sql
conf/v2_route/task.api
docs/tag_changes.md
postman/maproulette2.postman_collection.json

* Rename suggested fixes and associated columns and fields to
"cooperative" variants
* Add support for v2 of cooperative challenge data format
* Continue to support legacy v1 format for existing suggested-fix
challenges
* Support two types of cooperative challenge to start: "tag fix" type
(formerly quick fix, behaves like v1 suggested fixes) and new
change-file type that allows a change file to be associated with the
cooperative task
* Add Challenge.COOPERATIVE_TYPE_* constants to track the types of
cooperative challenge, and store type in cooperative_type column
(formerly has_suggested_fix) on the challenge table, tracking the actual
type instead of just whether or not it is cooperative
* Add `task/:id/cooperative/change` API endpoint for retrieving change
file XML associated with a …

Change suggested fixes to cooperative challenges

---

app/org/maproulette/controllers/api/TaskController.scala
conf/v2_route/task.api

* Update the `task/:id/cooperative/change` API to accept a filename that
is now used when serving the cooperative XML change content
* This provides maximum flexibility for integrating with editors that
look for a filename portion in the URL and use it for hints as to the
format of the downloaded change XML

Let client specify filename for XML change files

---

app/org/maproulette/framework/psql/Paging.scala
app/org/maproulette/framework/psql/Query.scala
app/org/maproulette/framework/psql/SQLUtils.scala
app/org/maproulette/framework/psql/filter/Filter.scala
app/org/maproulette/framework/psql/filter/Operator.scala
app/org/maproulette/framework/psql/filter/Parameter.scala
app/org/maproulette/framework/service/ProjectService.scala
app/org/maproulette/framework/service/UserMetricService.scala
app/org/maproulette/framework/service/UserService.scala
app/org/maproulette/utils/Utils.scala
test/org/maproulette/framework/psql/FilterOperatorSpec.scala
test/org/maproulette/framework/psql/FilterParameterSpec.scala
test/org/maproulette/framework/psql/FilterSpec.scala
test/org/maproulette/framework/psql/PagingSpec.scala
test/org/maproulette/framework/psql/QuerySpec.scala

- Needed to add a random prefix to named parameters so that if you are using the same column for multiple queries that there is no clash. 
- Also cleaned up the Query building case classes a bit to try make them a little less confusing.
- Added conditional for filter group in case you want to exclude/include an entire filter group based on some condition.

Adding random prefix to named parameters

---

app/org/maproulette/framework/psql/Query.scala
app/org/maproulette/framework/psql/filter/Operator.scala
app/org/maproulette/framework/psql/filter/Parameter.scala

The subqueryfilter added
- Ability to ignore the "WHERE" clause
- Fixes the filter such that if the key is empty it will still include the filter sql value correctly.

Updating SubQueryFilter

---

app/org/maproulette/framework/service/ProjectService.scala
test/org/maproulette/framework/ProjectSpec.scala

* Change ProjectService to use a project's existing virtual status when
updating a project rather than simply ommiting it, as that would cause
the virtual status to be updated to the default value of false
* Add unit test verifying that ProjectService doesn't update virtual
status
* Fixes osmlab/maproulette3#1207

Don't change virtual status of project on update

---

app/org/maproulette/controllers/api/TaskReviewController.scala
app/org/maproulette/framework/controller/TaskReviewController.scala
app/org/maproulette/framework/model/SavedTasks.scala
app/org/maproulette/framework/repository/ChallengeListingRepository.scala
app/org/maproulette/framework/service/ChallengeListingService.scala
app/org/maproulette/framework/service/ServiceHelper.scala
app/org/maproulette/framework/service/ServiceManager.scala
app/org/maproulette/models/dal/TaskReviewDAL.scala
app/org/maproulette/models/utils/DALHelper.scala
conf/v2_route/challenge.api
conf/v2_route/task.api
test/org/maproulette/framework/ChallengeListingSpec.scala
test/org/maproulette/framework/FrameworkMasterSuite.scala
test/org/maproulette/framework/util/FrameworkHelper.scala
test/org/maproulette/utils/TestSpec.scala

Add api '/review/challenges' which will fetch challenges that have tasks that have reviews/review requests. From this list, the front end will be able to narrow down the reviews to be returned to the user by challenge (or even by project) when fetching the full list of reviews.

Add api to fetch list of challenges for review

---

app/org/maproulette/framework/psql/Query.scala
app/org/maproulette/framework/repository/ChallengeRepository.scala
app/org/maproulette/framework/service/ProjectService.scala

* Populate `virtualParents` field in challenges retrieved through the
new framework. This requires adding a join into the basic challenges
query
* Support an optional default Grouping in Query class that allows an
overrideable default grouping to be specified for base queries that
require a group by
* Populate the `requiresLocal` field in challenges
* Fixes osmlab/maproulette3#1208

Populate challenge virtualParents, requiresLocal

---

app/org/maproulette/framework/psql/Query.scala
app/org/maproulette/framework/service/CommentService.scala
test/org/maproulette/framework/util/TestDatabase.scala

This PR improves the performance of the specific query executed when you call the find function in the CommentService it was executing this query against the database:
```sql
SELECT * FROM task_comments
INNER JOIN users ON users.osm_id = task_comments.osm_id
WHERE task_comments.project_id IN (<PROJECT_IDS>) OR 
1 IN (SELECT 1 FROM unnest(ARRAY[<PROJECT_IDS>]) AS pIds
WHERE pIds IN (SELECT virtual_project_challenges.project_id FROM virtual_project_challenges
WHERE virtual_project_challenges.challenge_id = task_comments.challenge_id)) OR 
task_comments.project_id IN (<PROJECT_IDS>) 
ORDER BY task_comments.project_id,task_comments.challenge_id,task_comments.created DESC 
LIMIT 10 OFFSET 0
```
which would take roughly 35 seconds to complete. This PR updates it so that it will execute this …

Improving Comments query

---

app/org/maproulette/framework/service/ServiceHelper.scala

Query was still using usergroup table name as "ug" instead of new constant Group.TABLE_USER_GROUP

Fix user group table name on permission query.

---

app/org/maproulette/framework/repository/TaskReviewRepository.scala

Expire old task reviews based on mapped_on instead of modified.

Change expire task reviews to use mapped_on instead of modified

---

app/org/maproulette/framework/service/UserMetricService.scala
test/org/maproulette/framework/service/UserMetricsServiceSpec.scala

* User metrics attemping to use table "sa1" instead of letting
new table naming be appended automatically
* User metrics date clause calculation ingoring time durations
of -1 which should represent "all time"
* Created simple test that just exercises the method

Fix user metrics

---

app/org/maproulette/framework/service/ProjectService.scala
app/org/maproulette/models/dal/ChallengeDAL.scala

* Change sql queries when fetching "hot", "new" and "featured"
* In fetching projects list to not retrieve all projects if
given a list of empty ids.

Improve sql performance of 'preferred' api

---

app/org/maproulette/framework/repository/UserRepository.scala
app/org/maproulette/framework/service/UserMetricService.scala
app/org/maproulette/models/dal/TaskDAL.scala

* When calculating user metrics avg time spent exclude skipped tasks
* Don't update user metrics 'total_time_spent' and 'total_tasks_with_time'
fields if task is skipped
* Fix bug when taskDAL.setTaskStatus was calculating completedTimeSpent

Exclude task skip times in user metrics time spent

---

app/org/maproulette/controllers/api/TaskController.scala
app/org/maproulette/controllers/api/TaskReviewController.scala
app/org/maproulette/framework/model/Tag.scala
app/org/maproulette/framework/repository/TagRepository.scala
app/org/maproulette/framework/service/TagService.scala
app/org/maproulette/models/dal/TaskReviewDAL.scala
app/org/maproulette/models/dal/mixin/SearchParametersMixin.scala
conf/v2_route/review.api
conf/v2_route/task.api
test/org/maproulette/framework/service/TagServiceSpec.scala

* When fetching tasks in bounding box add optional flag
to also include tag data
* When fetching reviewNeeded or reviewed tasks add
optional flag to also include tag data
* Add support for searching by task tags ('tt') when
fetching review tasks and bounded/clustered tasks.

Add ability to retrieve tags when fetching task lists

---

app/org/maproulette/controllers/api/TaskController.scala
conf/evolutions/default/62.sql

When skipping a task and not adding any tags, an empty tag was
being inserted for the task.

Clean up empty task tags

---

app/org/maproulette/models/dal/TaskDAL.scala

This is fix error "No User found using id [-1] to check read access" on attempt to change task status when review was requested but nobody has reviewed it yet.
In case when new record is created in `task_review` table then `reviewed_by is null` initially. After that if user tries to change task status, error `No User found using id [-1] to check read access` will occur. This is because we are trying to add a notification for an unknown user.

fix issue 'no user found using id [-1]' if try to change status

---

app/org/maproulette/controllers/api/ChallengeController.scala
app/org/maproulette/controllers/api/TaskController.scala
app/org/maproulette/controllers/api/TaskReviewController.scala
app/org/maproulette/controllers/api/VirtualChallengeController.scala
app/org/maproulette/data/DataManager.scala
app/org/maproulette/framework/controller/TaskReviewController.scala
app/org/maproulette/framework/model/TaskReview.scala
app/org/maproulette/framework/service/TaskReviewService.scala
app/org/maproulette/models/dal/ChallengeDAL.scala
app/org/maproulette/models/dal/TaskDAL.scala
app/org/maproulette/models/dal/TaskReviewDAL.scala
app/org/maproulette/models/dal/VirtualChallengeDAL.scala
app/org/maproulette/models/dal/mixin/SearchParametersMixin.scala
app/org/maproulette/session/SearchParameters.scala
conf/v2_route/review.api
test/org/maproulette/framework/service/TaskReviewServiceSpec.scala
test/org/maproulette/framework/util/FrameworkHelper.scala

Add api to export mapper review metrics as a csv. Supports
the same search parameters as getting all review metrics.
GET     /tasks/review/mappers/export
Also, created sub class on SearchParameters (SearchTaskParameters and SearchReviewParameters) to get around scala 22 parameter limit.

Add api to export mapper review metrics CSV

---

app/org/maproulette/models/dal/ChallengeDAL.scala

* Change item type used in permission check performed prior to applying
updated priority rules from TaskType to ChallengeType, as the implicit
id passed down is a challenge id and not a task id. The old check would
end up load a task matching the challenge id and ultimately check
permissions against that task's parent project, leading to arbitrary
outcomes for non-superusers that could prevent updated priority rules
from being applied
* Fixes osmlab/maproulette3#1110

Fix permission check when applying priority rules

---

app/org/maproulette/controllers/api/DataController.scala
app/org/maproulette/data/ActionManager.scala
app/org/maproulette/framework/controller/FollowController.scala
app/org/maproulette/framework/graphql/schemas/MRSchemaTypes.scala
app/org/maproulette/framework/graphql/schemas/UserSchema.scala
app/org/maproulette/framework/model/Group.scala
app/org/maproulette/framework/model/User.scala
app/org/maproulette/framework/repository/GroupMemberRepository.scala
app/org/maproulette/framework/repository/GroupRepository.scala
app/org/maproulette/framework/repository/UserRepository.scala
app/org/maproulette/framework/service/FollowService.scala
app/org/maproulette/framework/service/GroupService.scala
app/org/maproulette/framework/service/ServiceManager.scala
app/org/maproulette/framework/service/TeamService.scala
app/org/maproulette/framework/service/UserService.scala
app/org/maproulette/provider/websockets/WebSocketActor.scala
app/org/maproulette/provider/websockets/WebSocketMessages.scala
build.sbt
conf/evolutions/default/64.sql
conf/v2_route/data.api
conf/v2_route/follow.api
postman/maproulette2.postman_collection.json
test/org/maproulette/framework/repository/GroupMemberRepositorySpec.scala
test/org/maproulette/framework/service/FollowServiceSpec.scala
test/org/maproulette/framework/service/UserServiceSpec.scala
test/org/maproulette/utils/TestSpec.scala

* Allow users to follow other users, using Groups to keep track of who a
user is following and who is following them
* Dynamically generate "following" and "followers" groups as needed for
a user when they begin following or are initially followed, respectively
* Allow users to block individual followers
* Add a new allows_following user field that can be used to disallow all
following of a user
* Fix bug in Teams that caused non-team groups to get picked up in some
situations
* Minor enhancements to Groups service

Support following of users

---

app/org/maproulette/controllers/api/ChallengeController.scala

When creating a challenge, apply priority rules again after
creating tasks so that location will be present for any
bounds check.

Apply bounds priority rules on challenge create

---

app/org/maproulette/provider/ChallengeProvider.scala

This reverts commit d0f8f90744f7eb6185a1354ef94511c6fcdcbee5.
* Allowing single-line LxL resulted in the backend sometimes treating
standard challenges as LxL, which matters because in LxL the
FeatureCollection is treated as a single task with multiple features
rather than as a Challenge with multiple Tasks
* I'll make another stab at fixing the single-line LxL bug in the near
future by adding support for RFC 7464 for streaming JSON, which would
provide an explicit indicator as to when a single-line chunk is intended
to be treated as line-by-line (and would be good to support anyway as a
standard)

Revert "Allow single task with line-by-line format GeoJSON"

---

app/org/maproulette/controllers/api/ChallengeController.scala
app/org/maproulette/provider/ChallengeProvider.scala

Tasks are being built as a future on challenge create so the
updating of the task priorities must be done in this future
so it happens when they are done.

Moved where updateTaskPriorities is being called into future buildTasks

---

app/org/maproulette/framework/controller/TaskReviewController.scala
app/org/maproulette/framework/mixins/SearchParametersMixin.scala
app/org/maproulette/framework/model/Challenge.scala
app/org/maproulette/framework/psql/filter/Operator.scala
app/org/maproulette/framework/service/TaskReviewService.scala
app/org/maproulette/models/Task.scala
app/org/maproulette/models/dal/TaskReviewDAL.scala
app/org/maproulette/models/dal/mixin/SearchParametersMixin.scala
app/org/maproulette/session/SearchParameters.scala
conf/v2_route/review.api
test/org/maproulette/framework/mixins/SearchParametersMixinSpec.scala
test/org/maproulette/framework/psql/FilterOperatorSpec.scala

* Add new api  /tasks/review/nearby/:proximityId which supports
passing search parameters to determine which tasks require
review and are closest to the given proximityId task.
* Also refactored SearchParametersMixin to use new query framework 
as a first step to moving Tasks and TaskReview into new framework

Add support for fetch nearby review tasks.

---

app/org/maproulette/framework/mixins/SearchParametersMixin.scala
test/org/maproulette/framework/mixins/SearchParametersMixinSpec.scala

Method SearchParametersMixin.filterTaskReviewStatus must wrap
query sql in parenthesis because of the OR condition.

Add parenthesis to filterTaskReviewStatus

---

app/org/maproulette/framework/controller/TaskController.scala
app/org/maproulette/framework/repository/TaskRepository.scala
app/org/maproulette/framework/service/TaskService.scala
app/org/maproulette/models/dal/TaskDAL.scala
build.sbt
conf/v2_route/task.api
test/org/maproulette/framework/FrameworkMasterSuite.scala
test/org/maproulette/framework/repository/TaskRepositorySpec.scala

* Allow attachments on task FeatureCollection so that additional data
can be attached to a task, such as reference layers for use during
editing, links to relevant street-level imagery, data for consumption by
external processes, etc.
* Add API endpoint for retrieving the complete JSON representation of a
task attachment, including its raw data and metadata
* Add API endpoint for downloading task attachment data as a file,
decoded if necessary and with the proper mime type (for use with editors
importing reference layers)
* Fix missing `"type": "FeatureCollection"` on task geojson
* Fix typo in TaskRepository.scala filename
* Create TaskRepositorySpec

Allow tasks to have attachments

---

conf/evolutions/default/66.sql

There is a possiblity that until maproulette/maproulette2#728
was applied if the server and database had different times than
a negative timestamp could be saved for a task's
completed_time_spent. If there were enough negative timestamps
then average time per task would be negative.

Add evolution to remove any negative timestamps

---

app/org/maproulette/framework/mixins/SearchParametersMixin.scala
app/org/maproulette/framework/psql/filter/Filter.scala
test/org/maproulette/framework/mixins/ReviewSearchMixinSpec.scala
test/org/maproulette/framework/mixins/SearchParametersMixinSpec.scala
test/org/maproulette/framework/psql/FilterParameterSpec.scala
test/org/maproulette/framework/psql/FilterSpec.scala
test/org/maproulette/framework/psql/QuerySpec.scala

There are cases where a filter group with an OR condition
would not be wrapped in parenthesis and thus cause an
incorrect search. To be on the safe side wrap all OR
filter groups with ( )
fixes osmlab/maproulette3#1297

Add parens when building an 'OR' filter group

---

app/org/maproulette/framework/service/LeaderboardService.scala
app/org/maproulette/session/SearchParameters.scala

After refactor, code was looking at wrong url parameter names for 'start' and 'end' dates.

Fix custom date range search for leaderboard

---

app/org/maproulette/controllers/api/ChallengeController.scala
app/org/maproulette/models/dal/ChallengeDAL.scala
app/org/maproulette/utils/Utils.scala
conf/v2_route/challenge.api
conf/v2_route/project.api

When exporting challenge csv and geoson allow for an optional
timezone offset that will convert mappedOn and reviewedAt dates

Add timezone value for exporting csv and geojson

---

app/org/maproulette/controllers/api/TaskController.scala
app/org/maproulette/framework/controller/TagController.scala
app/org/maproulette/framework/graphql/schemas/TagSchema.scala
app/org/maproulette/framework/mixins/SearchParametersMixin.scala
app/org/maproulette/framework/model/Challenge.scala
app/org/maproulette/framework/model/TaskReview.scala
app/org/maproulette/framework/repository/ChallengeRepository.scala
app/org/maproulette/framework/repository/TaskReviewRepository.scala
app/org/maproulette/framework/service/LeaderboardService.scala
app/org/maproulette/framework/service/TagService.scala
app/org/maproulette/models/dal/ChallengeDAL.scala
conf/evolutions/default/67.sql

* Add preferredReviewTags to challenge which are the tags
the challenge owner prefers to be used during review
* Add limitTags and limitReviewTags to Challenge which
indicates the tags should be limited exclusively to the
preferred list.
* Add tagType field to return with tag metrics
* When calling setTaskReviewStatus with tags, the tags
will be stored as 'review' tags.
* Tag metrics api to accept an array (a comma string)
of tag types (ie. "tasks,review").

Add preferredReviewTags field to Challenge

---

app/org/maproulette/models/utils/ChallengeFormatters.scala
app/org/maproulette/session/SearchParameters.scala

* Challenge creation was requiring 'limitTags' and 'limitReviewTags'
* VirtualChallenge creation was missing leaderboardParams

Fix challenge creation requiring optional fields

---

app/org/maproulette/controllers/api/TaskBundleController.scala
app/org/maproulette/controllers/api/TaskController.scala
app/org/maproulette/framework/service/UserMetricService.scala
app/org/maproulette/models/Task.scala
app/org/maproulette/models/dal/TaskDAL.scala
conf/v2_route/task.api
test/org/maproulette/framework/service/UserMetricsServiceSpec.scala
test/org/maproulette/models/TaskSpec.scala

When user is revising a rejected task (or task bundle), allow
the user to change the task status by passing in a new task status
to setTaskReviewStatus

Allow task status to be changed during review revision

---

app/org/maproulette/models/dal/TaskClusterDAL.scala
app/org/maproulette/session/SearchParameters.scala

* Add `tExcl` search parameter for specifying id(s) of tasks to
be explicitly excluded from search results

Allow specific tasks to be excluded from search

---

app/org/maproulette/framework/graphql/schemas/MRSchemaTypes.scala
app/org/maproulette/framework/graphql/schemas/UserSchema.scala
app/org/maproulette/framework/model/User.scala
app/org/maproulette/framework/repository/UserRepository.scala
app/org/maproulette/framework/service/UserService.scala
conf/evolutions/default/68.sql
test/org/maproulette/framework/repository/UserRepositorySpec.scala

* Create new user_basemaps table and move existing custom
basemaps into new table
* When updating a user allow for customBasemaps to be specified
in JSON
* When returning a user return customBasemaps as an array of json
objects

Add support for multiple custom basemaps

---

conf/evolutions/default/68.sql

When migrating to custom basemaps do not migrate empty urls.

Check for empty urls when migration to custom basemaps

---

app/org/maproulette/framework/service/UserMetricService.scala

Change user metrics date search to search on StatusActions.created
instead of Tasks.created field.

Fix user metrics date range returning wrong results

---

app/org/maproulette/framework/controller/UserController.scala
app/org/maproulette/framework/service/UserService.scala
conf/v2_route/user.api
test/org/maproulette/framework/service/UserServiceSpec.scala

* Allow a taskId parameter to be passed in when searching for users
that will return those who have participated (commented or changed
status) in that task. Username is optional in this case.
eg. ```/api/v2/users/find?tid=2326765&username=c```

Support searching for users based on task id

---

app/org/maproulette/models/dal/TaskDAL.scala
conf/evolutions/default/69.sql

* When tasks are being rebuilt if the task status and mapper are
not changing then the mapped_on should not change also
Add to the SQL stored procedure update_task:
```
--
-- Only update a null mapped_on if we are resetting task status back to created
--
IF task_mapped_on IS NOT NULL THEN
UPDATE tasks SET mapped_on = task_mapped_on WHERE id = update_id;;
ELSE
IF new_status = 0 THEN
UPDATE tasks SET mapped_on = task_mapped_on WHERE id = update_id;;
END IF;;
END IF;;
```
* When tasks are bulk updated, if the status is being set back to
created we also need to clear the mapper, bundling, form data and review request.

Fix mapped_on being cleared on task rebuild

---

app/org/maproulette/framework/model/Challenge.scala
app/org/maproulette/framework/repository/ChallengeRepository.scala
app/org/maproulette/models/dal/ChallengeDAL.scala
app/org/maproulette/provider/ChallengeProvider.scala
conf/evolutions/default/70.sql

* Add overpass_target_type to challenge
* When processing an overpass query during challenge creationg,
if provided an overpass_target_type then verify that all the
overpass elements are of that type - otherwise set the
challenge has failed and report an error message.

Support validating target type on overpass queries

---

app/org/maproulette/controllers/api/ChallengeController.scala
app/org/maproulette/controllers/api/TaskController.scala
app/org/maproulette/controllers/api/TaskReviewController.scala
app/org/maproulette/framework/controller/TaskReviewController.scala
app/org/maproulette/framework/mixins/LeaderboardMixin.scala
app/org/maproulette/framework/mixins/SearchParametersMixin.scala
app/org/maproulette/framework/model/Leaderboard.scala
app/org/maproulette/framework/model/TaskReview.scala
app/org/maproulette/framework/repository/LeaderboardRepository.scala
app/org/maproulette/framework/repository/ProjectRepository.scala
app/org/maproulette/framework/repository/TaskReviewRepository.scala
app/org/maproulette/framework/service/LeaderboardService.scala
app/org/maproulette/framework/service/UserMetricService.scala
app/org/maproulette/framework/service/UserService.scala
app/org/maproulette/models/ClusteredPoint.scala
app/org/maproulette/models/Task.scala
app/org/maproulette/models/dal/ChallengeDAL.scala
app/org/maproulette/models/dal/TaskClusterDAL.scala
app/org/maproulette/models/dal/TaskDAL.scala
app/org/maproulette/models/dal/TaskReviewDAL.scala
app/org/maproulette/models/dal/VirtualChallengeDAL.scala
app/org/maproulette/provider/ChallengeProvider.scala
conf/evolutions/default/70.sql
test/org/maproulette/framework/mixins/SearchParametersMixinSpec.scala

* Add to database task_review: 'additional_reviewers' and
to task_review_history: 'original_reviewer'
* Support 'additionalReviewers' to be returned when fetching
any task data that includes review data.
* Convert review metrics to fetch from task_review_history to
better match expected metrics and include metric for
'additionalReviews'
* Convert reviewer 'leaderboard' to fetch review counts from
task_review_history and also include how many reviews were
'additionalReviews'
* When returning review metrics also include breakdown by review status
* Fix bug around updating task_review_history: In setTaskReviewStatus
the 'started_at' time for the task_review_history should be the
task's review current 'claimed_at' time. Also include db evolution
to fix the latest entries for a task in …

Add support for returning additional reviewers

---

app/org/maproulette/models/dal/TaskReviewDAL.scala
conf/evolutions/default/72.sql

* Fix case where reviewer was being assigned as mapper in case
of re-review in the task_review table
* Fix any data messed up by this bug by referencing task_review_history

Fix bug where reviewer cannot re-review a task

---

conf/application.conf

When doing an overpass query we let the user override the timeout
in their query. This timeout only overrides the request timeout
and will still be restricted by the idle timeout. By changing the idle timeout
to an hour in the conf, it will allow longer overpass queries to
run with overridden timeouts but as the default request timeout
in play is 2 minutes it will still enforce that restriction
normally.
See "configuring timeouts" in: https://www.playframework.com/documentation/2.6.x/ScalaWS
Closes #842

set play idle timeout in conf to 1 hour

---

app/org/maproulette/framework/controller/UserController.scala
app/org/maproulette/framework/mixins/ParentProjectMixin.scala

* When returning saved challenges json return with parent
project data so that front-end can reference parent project
name, info, etc.

Add in parent data to saved challenges json

---

conf/evolutions/default/73.sql

When creating a task in the SQL create_update_task function, honor
the status passed in. The status was only being set correctly in
cases of an update not an insert.
```
IF (task_status IS NULL) THEN
-- default to created
new_task_task_status := 0;;
ELSE
-- set task status to passed in status
new_task_task_status := task_status;;
END IF;;
```
This change will allow "status" to be set in the JSON passed in the 
create task API -- eg. this might be used to have the task start off 'disabled' and
thereby retain data from certain jobs to ensure accurate metrics.

Allow status to be defined in create task api

---

app/org/maproulette/framework/mixins/TaskParserMixin.scala

ParentId being returned was project grandparent not challenge parent
of task.

Fix wrong parent returned from start review

---

app/org/maproulette/controllers/api/TaskController.scala
app/org/maproulette/framework/mixins/Locking.scala
app/org/maproulette/framework/repository/TaskReviewRepository.scala
app/org/maproulette/models/dal/mixin/Locking.scala

This will allow the consumer of lockItem to indicate in the error
message who currently holds the lock.

Changed Locking.lockItem to return user id holding the lock.

---

app/org/maproulette/controllers/api/ChallengeController.scala
conf/v2_route/challenge.api

- Add support for optional filename to be specified when exporting
challenge GeoJSON via API

Allow custom filename for challenge GeoJSON export

---

test/org/maproulette/framework/util/TestDatabase.scala

Allows customization of the test database connection details via the `MR_TEST_DB_{HOST,NAME,PASSWORD,PORT,USER}` environment variables.

Test Database Settings from Environment

---

app/org/maproulette/framework/model/User.scala
app/org/maproulette/framework/model/UserMetrics.scala
app/org/maproulette/framework/repository/UserRepository.scala
app/org/maproulette/framework/service/AchievementService.scala
app/org/maproulette/framework/service/ServiceManager.scala
app/org/maproulette/framework/service/TaskReviewService.scala
app/org/maproulette/models/dal/ChallengeDAL.scala
app/org/maproulette/models/dal/TaskDAL.scala
app/org/maproulette/provider/websockets/WebSocketActor.scala
app/org/maproulette/provider/websockets/WebSocketMessages.scala
conf/evolutions/default/75.sql
test/org/maproulette/framework/FrameworkMasterSuite.scala
test/org/maproulette/framework/repository/UserRepositorySpec.scala
test/org/maproulette/framework/service/AchievementServiceSpec.scala
test/org/maproulette/framework/service/TaskClusterServiceSpec.scala
test/org/maproulette/utils/TestSpec.scala

- Add support for Achievements, which are awarded to users for various
notable actions/events, such as fixing their first task or crossing a
major points threshold
- Add migration that retroactively awards (most) achievements that would
have been earned in the past
- Achievements are simply represented as an array of int constants on
the user_metrics table, and are pulled into the User object for easy
reference by clients
- A new AchievementService manages the awarding of achievements as
appropriate when certain major events occur, such as task completion,
task review, challenge completion, etc.
- Websocket messages are transmitted to subscribed clients when users
earn new achievements

Add support for Achievements/Badges

---

app/org/maproulette/models/dal/ChallengeDAL.scala
app/org/maproulette/provider/ChallengeProvider.scala

If after building/rebuilding challenge from an overpass query, mark as finished if there are no incomplete tasks.
Closes osmlab/maproulette3#986

Mark challenge finished when overpass query returns no tasks

---

app/org/maproulette/framework/mixins/SearchParametersMixin.scala
test/org/maproulette/framework/mixins/SearchParametersMixinSpec.scala

* SearchParamtersMixin was pulling back wrong field when applying
filters for challenge tags
Fixes issue osmlab/maproulette3#1514

Fix search by challenge tags in task cluster search

---

app/org/maproulette/data/DataManager.scala
app/org/maproulette/framework/repository/TaskClusterRepository.scala
app/org/maproulette/framework/repository/TaskReviewMetricsRepository.scala
app/org/maproulette/framework/repository/TaskReviewRepository.scala
app/org/maproulette/framework/service/TaskClusterService.scala
app/org/maproulette/framework/service/TaskReviewMetricsService.scala
app/org/maproulette/framework/service/TaskReviewService.scala

* Include only 'row_num' from select when needed (in nextTaskReview only)
and exclude from all other review queries to improve performance
* Use subselect to determine if tasks are locked instead of LEFT JOIN
* Improve query when getting challenge summary by using a WITH clause
to narrow tasks table to only tasks in relevant challenge
* Improve fetching tasks in bounding box query by usign a WITH clause
to narrows tasks table to only tasks in challenge
* Improve review metrics queries by using challenge ids to limit
tasks in a WITH clause when possible.

Improve performance of review queries

---

app/org/maproulette/data/DataManager.scala
app/org/maproulette/framework/mixins/TaskFilterMixin.scala
app/org/maproulette/framework/repository/TaskClusterRepository.scala
app/org/maproulette/framework/repository/TaskReviewMetricsRepository.scala
app/org/maproulette/framework/repository/TaskReviewRepository.scala
app/org/maproulette/framework/service/TaskClusterService.scala
app/org/maproulette/framework/service/TaskReviewService.scala
conf/evolutions/default/77.sql

* Revert DataManager to no longer have "with"
* Fix ambigious 'reviewed_at' sort in review queries
* Remove 'with' in TaskClusterRepository and remove inner join on locked
* Remove 'with' in TaskReviewRepository
* Change TaskFilterMixin.add filter locked to use subselect instead of
join on locked table (as query does not always needed to join on locked)

Revert some overly optimistic optimizations

---

app/org/maproulette/framework/repository/TaskReviewRepository.scala
app/org/maproulette/framework/service/TaskReviewService.scala

When fetching next task to review, a task id can provided
so that the task following (based on criteria) will be returned.
The query to determine the row number was pulling back the full
set of results when only the actual task needed to be returned.
Fixed query by wrapping in another select filtering by task id.

Improve performance of next review task query

---

app/org/maproulette/data/DataManager.scala
app/org/maproulette/data/SnapshotManager.scala

When doing a project challenge summary query, if given only one
project and the project is not virtual, then do not include additional
subselect finding virtual project challenges.

Optimize project challenge summary query

---

app/org/maproulette/framework/graphql/schemas/TagSchema.scala
app/org/maproulette/framework/mixins/TagsControllerMixin.scala
app/org/maproulette/framework/service/TagService.scala
app/org/maproulette/models/dal/mixin/TagDALMixin.scala

When retrieving a tag by name it must have a tag type as there
can be multiple tags of the same name but of different types (challenges/tasks)

Fix when retrieving a tag by name it needs a tag type

---

app/org/maproulette/framework/mixins/SearchParametersMixin.scala
app/org/maproulette/framework/psql/SQLUtils.scala
test/org/maproulette/framework/service/TagServiceSpec.scala

When searching challenges/mappers/reviewers/projects and
using an apostrophe, the single quote needs to be escaped

Fix searching challenges with apostrophe causes SQL error

---

app/org/maproulette/framework/service/TaskReviewService.scala

When asking to fetch reviewed tasks, allow non-reviewes to fetch
tasks they mapped that have been reviewed.

Allow reviewed tasks to be fetched if user is the mapper

---

app/org/maproulette/controllers/CRUDController.scala
app/org/maproulette/models/utils/ChallengeFormatters.scala

My original implementation of the "isArchived" json insert in the CRUDController was incorrect.  Knowing about the Challenge Formatter now, I relocated the "isArchived" parameter to the Challenge specific formatters so that Tasks are not affected, since they also use the CRUDController.  Projects require "isArchived" as well but this logic is located elsewhere, and is unaffected.
Refactors https://github.com/maproulette/maproulette2/pull/890/files#diff-de464fb49f0929f7f712b05119d821bad5535eec31cd3305ec03f6fdd5bbb831R94
Resolves https://github.com/maproulette/maproulette2/issues/895

relocate isArchived JSON insert to ChallengeReads

---

conf/application.conf

* Allows customization of Akka's listening via `MR_AKKA_{HOST,PORT}` environment variables.  This is convenient for running tests at the same time as a running development instance.
* Default Akka to safely listen only on 127.0.0.1 instead of all bound addresses.  Cluster advertisement should be opt-in, not opt-out -- otherwise it's a potential security issue (I wish malicious cluster joining wasn't a thing).

Akka Settings from Environment

---

app/org/maproulette/controllers/ParentController.scala

The `api/v2/challenge/3684/children?limit=#&page=#` endpoint was using the `page` parameter as an `offset` in the service, instead of converting the page number to the proper offset value.

distinguish page from offset

---

app/org/maproulette/framework/repository/ChallengeRepository.scala
app/org/maproulette/models/dal/ChallengeDAL.scala

I *think* this should fix https://github.com/osmlab/maproulette3/issues/1622 by not relying upon `changeset_url` being in the request.

Fix https://github.com/osmlab/maproulette3/issues/1622: changeset_url is required

---

app/org/maproulette/controllers/api/ChallengeController.scala
app/org/maproulette/models/utils/ChallengeFormatters.scala

In some challenge creation user flows, the frontend is not providing a changesetUrl value of true or false, so we need to add the changesetUrl to the challengeFormatters

add changesetUrl to challenge formatters

---

app/org/maproulette/controllers/ParentController.scala
app/org/maproulette/models/dal/ChallengeDAL.scala

This is a continuance of https://github.com/maproulette/maproulette2/pull/897 where we need to distinguish page from offset for our API users.  The terminology seems to change between our routes and controllers/services.
I verified that this change does not break any frontend usages.

distinguish page from offset for /challenge "listChildren" services

---

app/org/maproulette/framework/mixins/Locking.scala
app/org/maproulette/framework/repository/TaskReviewRepository.scala
app/org/maproulette/models/dal/TaskDAL.scala

As a result of https://github.com/osmlab/maproulette3/pull/1631, this PR improves the user-friendliness of the lock messages for task status update services.  I also removed the task ids from the messages for a couple of the services since some tasks are in bundles and don't match up with the task id in the URL, potentially confusing the user.

improve user-friendliness of lock error messages

---

app/org/maproulette/models/dal/ChallengeDAL.scala
app/org/maproulette/session/SearchParameters.scala

This will allow challenge query results to be filtered by `archived=true/false`;
Supports https://github.com/osmlab/maproulette3/pull/1639

add "archived" query param to challenge extendedFind

---

app/org/maproulette/framework/repository/TaskReviewRepository.scala

In some scenarios, review duration is broken because review_started_at is being unknowingly nullified.  By setting review_started_at during claimTaskReview, this should prevent a race condition between two endpoints that is un-claiming the task review before the task is actually reviewed.
This bug fix is preferential to swapping the order of the two endpoints (`/next` and `/task/review`) due to a comment found in the frontend code (https://github.com/osmlab/maproulette3/blob/main/src/components/HOCs/WithTaskReview/WithTaskReview.js#L56).

revise behavior of review_started_at

---

app/org/maproulette/controllers/api/ChallengeController.scala
app/org/maproulette/models/dal/ChallengeDAL.scala
conf/v2_route/challenge.api

This new endpoint allows multiple challenges to be archived or unarchived simultaneously

add bulk archive api

---

app/org/maproulette/Config.scala
app/org/maproulette/framework/model/Challenge.scala
app/org/maproulette/framework/repository/ChallengeRepository.scala
app/org/maproulette/framework/service/ChallengeService.scala
app/org/maproulette/jobs/Scheduler.scala
app/org/maproulette/jobs/SchedulerActor.scala
app/org/maproulette/models/dal/ChallengeDAL.scala
app/org/maproulette/models/utils/ChallengeFormatters.scala
conf/application.conf
conf/evolutions/default/84.sql

Resolves https://github.com/osmlab/maproulette3/issues/686.
Added a scheduler to predetermine task completion percentage for challenges and the number of tasks remaining, and added these data-points to the challenge table.  This allows a challenge query to have context of its completion metrics in order to not have to drill down to the task table every query.
To be released with https://github.com/osmlab/maproulette3/pull/1642

Add capability to sort by challenge completion

---

app/org/maproulette/framework/service/NotificationService.scala

Resolves https://github.com/osmlab/maproulette3/issues/1630
To be released with https://github.com/osmlab/maproulette3/pull/1643
The issue pertains to challenge-level comments, which were mistakenly populating the taskId column with the challengeId.  This column should instead just be nullified.

Fix challenge-level comment notifications

---

app/org/maproulette/framework/mixins/SearchParametersMixin.scala
app/org/maproulette/framework/model/Challenge.scala
app/org/maproulette/session/SearchParameters.scala

The taskCluster services need to filter out archived challenges' task nodes appropriately.
To be released with: https://github.com/osmlab/maproulette3/pull/1646

fix taskCluster archive filtering

---

app/org/maproulette/controllers/api/ChallengeController.scala
app/org/maproulette/provider/ChallengeProvider.scala

Calling `.size` on an iterator mutates and empties out the iterator.  Need to create a separate variable to determine task count.
Resolves https://github.com/osmlab/maproulette3/issues/1651

Task length bug fix

---

app/org/maproulette/framework/model/User.scala
app/org/maproulette/framework/repository/UserRepository.scala
app/org/maproulette/framework/service/UserService.scala
conf/evolutions/default/86.sql

This will add a "See Tag Fix Suggestions" user setting, allowing tag fix widgets to be disabled so user only sees a normal task edit interface.
Resolves https://github.com/osmlab/maproulette3/issues/1650
To be released with https://github.com/osmlab/maproulette3/pull/1667

See Tag Fix Suggestions User Setting

---

app/org/maproulette/jobs/SchedulerActor.scala

adding additional filtering to updateLocations to speed up the service.  Challenges outside of discoverability shouldn't need this update.

add more restriction to updateLocations

---

project/plugins.sbt

The sbt plugin "com.iheart:sbt-play-swagger" plugin dependency needs to be updated since the 0.9.1 versions have been removed from maven, likely due to a long outstanding CVE <https://nvd.nist.gov/vuln/detail/CVE-2017-18640>.
We know that the (unpatched) build worked Jan 11 and failed Jan 12. 
The build error message:
```
[error] sbt.librarymanagement.ResolveException: Error downloading com.iheart:play-swagger_2.13:0.9.1-PLAY2.8
[error]   Not found
[error]   Not found
[error]   not found: /root/.ivy2/local/com.iheart/play-swagger_2.13/0.9.1-PLAY2.8/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/iheart/play-swagger_2.13/0.9.1-PLAY2.8/play-swagger_2.13-0.9.1-PLAY2.8.pom
```

Fix build: Update to sbt-play-swagger 0.10.6

---

app/org/maproulette/models/dal/ChallengeDAL.scala

Fixes https://github.com/osmlab/maproulette3/issues/1698
The updateTaskPriorities method checks for valid priority rules before proceeding.  But if there are no priority rules on the challenge, and if the user changes the default priority, there's an unaccounted for edge case.  I added an override for editChallenge flow so tasks will be updated if the defaultPriority is changed.

add an override valid priority rules parameter

---

app/org/maproulette/framework/controller/TaskBundleController.scala

For bundled task reviews, tags need to be applied to tasks instead of the bundle id.

fix id reference in setBundleTaskReviewStatus

---

app/org/maproulette/models/dal/TaskDAL.scala
conf/v2_route/challenge.api

Since all tasks in a challenge have the same parent id, sorting by parent id is unreliable when using page/limit parameters of the extract endpoint.  Also, offset is properly converted from page now.
To be released with https://github.com/osmlab/maproulette3/pull/1714

change sort of challenge tasks extract

---

app/org/maproulette/controllers/api/TaskController.scala

For Task Model needs, errorTags need to be preset in the request body before validation and creation

preset errorTags for Task model

---

README.md
app/org/maproulette/filters/Filters.scala
app/org/maproulette/filters/HttpLoggingFilter.scala
app/org/maproulette/metrics/Metrics.scala
build.sbt
conf/application.conf
conf/dev.conf.example
conf/logback-dev.xml

Create HttpLoggingFilter logging filter to provide an http request log at the service side. The HttpLoggingFilter is enabled by default within application.conf but will create no output until logback is set to the debug or trace levels.
Verified that the gh action logs don't print anything different than before (the http log filter is noop at info level)
This is what the trace log looks like this in the intellij console:
> 21:13:41,477 [debug] [application-akka.actor.default-dispatcher-19] o.m.f.HttpLoggingFilter.$anonfun$apply$1(HttpLoggingFilter.scala:39) - id=161 org.maproulette.controllers.api.ChallengeController.listChildren: 'GET /api/v2/challenge/1139/tasks?limit=10&page=0' took 17ms and returned 200
> 21:13:41,478 [trace] [application-akka.actor.default-dispatcher-19] …

Create HttpLoggingFilter to log http requests

---

conf/application.conf

this feature needs additional checks for OPTION calls.  disabling for now.

disable HttpLoggingFilter

---

app/org/maproulette/provider/ChallengeProvider.scala

Challenges submitted via remoteJson don't assign priority rules correctly because an updatePriorities method was missing after the creation process is complete.  Creation and Edit flows should be resolved with this implementation.

add updateTaskPriorities method at end of remoteJson flow

---

app/org/maproulette/Config.scala
app/org/maproulette/models/dal/TaskDAL.scala

Some later-flow task data is being affected when a completed task has no `completed_time_spent`.  This configuration will ensure the field is filled with a configurable amount as a last resort.

add condition to fill completedTime if one isn't provided

---

conf/swagger.yml

Remove unnecessary `info.version` from swagger.yml and allow the
play-swagger plugin to use the build's version (from build.sbt).
This has no visual change as both versions (build.sbt and swagger.yml)
were both 4.0.0, and in the future deployments can set a version.
See here for reference https://github.com/iheartradio/play-swagger#step-2
> Note that info.version is intentionally left out, playSwagger will automatically fillin the build version of the project. However if the version is set here it will be honored. You can also dynamically generate the version string in build file using the swaggerAPIVersion setting.

Use build.sbt 'version' for swagger api version

---

.github/workflows/scala.yml
README.md
conf/swagger.yml

Since the scala API is what provides the swagger docs there is no need to allow swagger to send requests to a different backend. This patch purges the API_HOST variable and the swagger docs will now, by default, send the request to the host where it (the API serving swagger) is running.
If the API and Docs are separated into different hosts in the future, use this approach https://github.com/iheartradio/play-swagger#how-do-i-use-a-different-host-for-different-environment

Remove the API_HOST var from swagger.yml

---

CONTRIBUTING

to remind users submitting issues that this is the backend repository.

adding CONTRIBUTING stub 

---

build.sbt
test/org/maproulette/framework/service/FollowServiceSpec.scala
test/org/maproulette/framework/service/UserServiceSpec.scala

The updates will resolve these issues (identified by snyk docker scan)
```
Issues to fix by upgrading:
Upgrade com.fasterxml.jackson.core:jackson-databind@2.11.4 to com.fasterxml.jackson.core:jackson-databind@2.12.6.1 to fix
✗ Denial of Service (DoS) [Medium Severity][https://snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-2326698] in com.fasterxml.jackson.core:jackson-databind@2.11.4
introduced by com.fasterxml.jackson.core:jackson-databind@2.11.4 and 1 other path(s)
✗ Denial of Service (DoS) [High Severity][https://snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-2421244] in com.fasterxml.jackson.core:jackson-databind@2.11.4
introduced by com.fasterxml.jackson.core:jackson-databind@2.11.4 and 1 other path(s)
Upgrade org.postgresql:postgresql@42.2.10 to org.postgresql:postgresql@42.3.3 to …
```

Update many runtime dependencies

---

app/org/maproulette/framework/repository/TaskReviewRepository.scala

review time is affected by users visiting the review screen but not completing a review.  the original `review_started_at` will be retained in this case

add condition for 'review_started_at'

---

build.sbt
project/build.properties
project/plugins.sbt

Sbt updates:
- sbt: 1.6.2 to 1.7.1
- com.typesafe.play:sbt-plugin: 2.8.15 to 2.8.16
Dependency updates:
- org.postgresql:postgresql: 42.3.4 to 42.4.2
- joda-time:joda-time: 2.10.14 to 2.11.1

Update sbt, joda, postgres dependencies

---

app/org/maproulette/controllers/api/TaskController.scala
app/org/maproulette/framework/model/Challenge.scala

Going to modify the bulk task status update endpoint to resolve immediately and allow tasks to be updated in a background process.  The challenge will be placed in a Building status until the process is complete.
Resolves https://github.com/osmlab/maproulette3/issues/1764, but the endpoint background process will still take the same amount of time.  This fix just allows the UI to respond to the process without throwing a frontend timeout error.
To be released with https://github.com/osmlab/maproulette3/pull/1812

modify bulk task status update into a build flow

---

.github/workflows/scala.yml
app/org/maproulette/Config.scala
app/org/maproulette/cache/BasicCache.scala
app/org/maproulette/cache/Cache.scala
app/org/maproulette/cache/CacheManager.scala
app/org/maproulette/cache/CaffeineCache.scala
app/org/maproulette/cache/RedisCache.scala
build.sbt
test/org/maproulette/cache/CacheSpec.scala

This is the implementation of a `CaffeineCache` (caffeine is a highly performant in-memory cache) that can be used based on the conf. The `BasicCache` was shown to be a limiter in several profiles and lacks a priority queue for item expiry.
Use the more performant cache by setting `maproulette.caching.type = "caffeine"` in the conf file. At this time the default will remain the BasicCache until this gets more testing.

Create the CaffeineCache implementation

---

app/org/maproulette/models/dal/TaskDAL.scala

Managing task statuses on the admin pages currently does not appropriately update the mappedOn date.  MappedOn will now update accordingly, even in bulkUpdates

modify mappedOn date depending on task status

---

build.sbt
project/plugins.sbt

Bintray and atlassian are not needed, and snapshot jars should be avoided.

Use only sonatypeOss releases resolver

---

build.sbt
project/plugins.sbt

The sbt plugin org.scalastyle:scalastyle-sbt-plugin is deprecated and replaced by [com.beautiful-scala:sbt-scalastyle](https://github.com/beautiful-scala/scalastyle).

scalastyle: Switch to com.beautiful-scala:sbt-scalastyle

---

conf/v2_route/bundle.api
conf/v2_route/leaderboard.api
conf/v2_route/user.api

There were some routes with '##' for their documentation instead of '###' (2 vs 3 hashes), causing the docs to not be included in the swagger-ui and placing them in the 'generated' tag grouping.
The 'generated' tag is now empty :-)

Fix typos in routes files

---

conf/application.conf
conf/dev.conf.example

The `maproulette.caching.type` can be set via conf changes or by setting MR_CACHING_TYPE=<cacheType> env variable.

Support setting cache type based on env MR_CACHING_TYPE

---

app/org/maproulette/cache/Cache.scala
app/org/maproulette/models/dal/ChallengeDAL.scala
app/org/maproulette/models/dal/TaskDAL.scala

The `withOptionCaching` calls are designed to be given an ID, and if that ID isn't in the cache it will call the database. There are cases where the ID was not provided and it would always ping the database and update the cache entry.

Provide missing IDs to withOptionCaching

---

app/controllers/AuthController.scala
app/org/maproulette/controllers/OSMChangesetController.scala
app/org/maproulette/controllers/api/ChallengeController.scala
app/org/maproulette/controllers/api/TaskController.scala
app/org/maproulette/exception/MPExceptionUtil.scala
app/org/maproulette/framework/controller/ChallengeSnapshotController.scala
app/org/maproulette/framework/controller/UserController.scala
app/org/maproulette/framework/psql/filter/Parameter.scala
app/org/maproulette/framework/service/ChallengeService.scala
app/org/maproulette/jobs/SchedulerActor.scala
app/org/maproulette/models/dal/TaskDAL.scala
app/org/maproulette/provider/KeepRightProvider.scala
app/org/maproulette/provider/osm/ChangesetProvider.scala
app/org/maproulette/provider/osm/objects/ObjectProvider.scala
app/org/maproulette/provider/websockets/WebSocketProvider.scala
app/org/maproulette/session/SessionManager.scala
test/org/maproulette/cache/CacheSpec.scala
test/org/maproulette/framework/psql/FilterParameterSpec.scala
test/org/maproulette/framework/psql/FilterSpec.scala
test/org/maproulette/framework/psql/QuerySpec.scala
test/org/maproulette/framework/repository/CommentRepositorySpec.scala
test/org/maproulette/framework/service/CommentServiceSpec.scala
test/org/maproulette/framework/service/TaskBundleServiceSpec.scala

In the spirit of reducing compile warnings to see actual issues, this patch resolves many issues with the "Auto-application to `()` is deprecated" warning. These fixes were auto-applied by using the `scala-rewrites` plugins for `sbt-scalafix` and, for now, scalafix won't be configured to check for this issue during CI.
The full warning looks like this:
Auto-application to `()` is deprecated. Supply the empty argument list `()` explicitly to invoke method unbundleTasks,
[warn] or remove the empty argument list from its definition (Java-defined methods are exempt).
[warn] In Scala 3, an unapplied method like this will be eta-expanded into a function.
[warn]       this.service.unbundleTasks(User.superUser, bundle.bundleId, List(task2.id))
There were some version issues with the plugin were …

Fix warnings for "Auto-application to `()` is deprecated"

---

app/org/maproulette/framework/service/NotificationService.scala

Challenge comments were comparing the commenter's userId with the challenge owner's osm id.  The service was updated to locate the challenge owner's user id.
To be released with https://github.com/osmlab/maproulette3/pull/1861

retrieve challengeOwner id for challenge comments

---

app/org/maproulette/framework/controller/TaskBundleController.scala
app/org/maproulette/framework/service/CommentService.scala
app/org/maproulette/framework/service/TaskReviewService.scala

In review/revise flows, when submitting a task bundle, mentioning a user will cause duplicate notifications.  Adding variables to prevent duplicates.

prevent duplicate notifications in task bundles

---

app/org/maproulette/framework/controller/NotificationController.scala
conf/v2_route/notification.api

If a user has many notifications and tries to delete them all at once, the URL paramter notificationIds can surpass the length that is allowed.
Moving notificaitonIds in both the delete and markRead services to the json payload of the requests.
Resolves https://github.com/maproulette/maproulette3/issues/1569
To be released with https://github.com/maproulette/maproulette3/pull/1887

move notificationIds to json in services

---

.github/workflows/scala.yml
app/org/maproulette/Config.scala
conf/application.conf

The cache has been sufficiently tested and caffeine is now the default. Admins can override this with `maproulette.caching.type` in the conf or MR_CACHING_TYPE env.

Set caffeine as the default cache type

---

.github/workflows/scala.yml
README.md
test/org/maproulette/cache/CacheSpec.scala

The dev setup needs to suggest using postgis:13-3.3 so that it gets more exposure and test time. Postgres 11 is EOL in less than a year.

README show to use postgis:13-3.3

---

app/org/maproulette/Config.scala
app/org/maproulette/controllers/CRUDController.scala
app/org/maproulette/controllers/api/ChallengeController.scala
app/org/maproulette/controllers/api/TaskController.scala
app/org/maproulette/controllers/api/VirtualChallengeController.scala
app/org/maproulette/provider/ChallengeProvider.scala
conf/application.conf

Allow for overriding the max tasks per challenge using conf key `maproulette.task.max_tasks_per_challenge`.

Support conf overrides of max tasks per challenge

---

app/org/maproulette/controllers/CRUDController.scala
app/org/maproulette/controllers/api/ChallengeController.scala
app/org/maproulette/provider/ChallengeProvider.scala

This resolves a bug where a `POST /api/v2/tasks` would silently fail to create tasks after exceeding the maximum number of tasks per challenge.
The code will now throw an exception, resulting in HTTP 400 for clients. Note that tasks may be created and saved in the database before the excess triggers the exception.
A test of this using 1000 max tasks and a maproulette-java-client upload of around 2000 tasks does now fail with an exception:
maproulette-java-client logs:
```
[main] DEBUG org.maproulette.client.connection.MapRouletteConnection - Request: POST /api/v2/tasks
org.maproulette.client.exception.MapRouletteRuntimeException: org.maproulette.client.exception.MapRouletteException: Invalid response status code 400 - {"status":"KO","message":"Challenges cannot exceed 1000 tasks"}
``` …

Enforce max task count for POST /api/v2/tasks

---

.github/workflows/scala.yml
conf/application.conf
conf/dev.conf.example

There are some redundancies between the application.conf and the dev.conf, and some variables should be overridable via env.
- Support setting database username from env `MR_DATABASE_USERNAME`
- Support setting database password from env `MR_DATABASE_PASSWORD`
- Support setting openstreemap server from env `MR_OSM_SERVER`
- Move akka logging configuration to application.conf

Simplify the application.conf and dev.conf.example

---

build.sbt
project/plugins.sbt
test/org/maproulette/info/BuildInfoSpec.scala

Integrate the BuildInfo sbt plugin into the project. This will generate `org.maproulette.info.BuildInfo` and include useful build-time information such as the jdk version, jdk vendor, sbt version, etc.
This information will be useful in creating an endpoint to show compiletime/runtime metadata of maproulette, to validate deployment state and investigate issues.
Example:
```
/** This object was generated by sbt-buildinfo. */
case object BuildInfo {
val name: String = "MapRouletteAPI"
val version: String = "4.0.0"
val scalaVersion: String = "2.13.10"
val sbtVersion: String = "1.7.2"
val buildDate: String = "2023-01-16"
val javaVersion: String = "11.0.17"
val javaVendor: String = "Eclipse Adoptium"
```

Generate `BuildInfo.scala` with useful build-time data

---

app/org/maproulette/controllers/api/DataController.scala

Require users to be authenticated when using these endpoints:
- /api/v2/data/challenge/:challengeId
- /api/v2/data/challenge/:challengeId/propertyKeys
- /api/v2/data/challenge/summary
- /api/v2/data/project/summary

Require authN for routes in DataController.scala

---

app/org/maproulette/provider/EmailProvider.scala

**Issue**
Incorrect link reference to unsubscribe option in the footer of email notifications
**Approach / Solution**
Fixed the link to point to the correct area on the user profile in email settings.
**Resolves:**
https://github.com/maproulette/maproulette3/issues/1930

fixed the base url for users to update their email preferences

---

conf/logback-dev.xml

Logging the play evolutions when running in a dev environment is very helpful, and this makes it the default.

Dev mode: log play.api.db.evolutions at debug level

---

postman/README.md

Currently the links are broken, resulting in 404 errors in Github when reading the Postman documentation on https://github.com/maproulette/maproulette-backend/blob/dev/postman/README.md.

Fix links to Postman collection

---

app/org/maproulette/exception/MPExceptionUtil.scala

Whenever a request fails authN, this log entry is created at the Error level:
[scala-execution-context-global-1871] o.m.e.MPExceptionUtil$.manageException(MPExceptionUtil.scala:79) - Authorization failed (server replied with a 401). This can happen if the consumer key was not correct or the signatures did not match.
This is not useful for day-to-day monitoring so it's annoying at the least, and at the worst a runaway script etc could cause the service to have issues (logging does take compute time, after all).
Resolve this by logging authN issues at `debug`. Developers will have no issues and we'll see less annoyance with prod logs.

Log NotAuthorized at the debug level instead of Error

---

app/org/maproulette/Config.scala
app/org/maproulette/framework/repository/ChallengeRepository.scala
app/org/maproulette/framework/service/ChallengeService.scala
app/org/maproulette/jobs/Scheduler.scala
app/org/maproulette/jobs/SchedulerActor.scala
conf/application.conf
conf/evolutions/default/92.sql

This commit changes how the challenge completion percentage is updated. This new approach uses a single SQL query to update all challenges and will complete much faster than the previous.
The new query uses two subqueries to separate the computation of total tasks and completed tasks where, specifically, it makes use of the index on 'tasks.status'.
Resolves #1043 and there's more technical comments there.

Improve performance of calculating completion percentage in challenges

---

app/org/maproulette/framework/controller/TaskReviewController.scala
app/org/maproulette/framework/mixins/TaskParserMixin.scala
app/org/maproulette/framework/model/TaskReview.scala
app/org/maproulette/framework/repository/TaskHistoryRepository.scala
app/org/maproulette/framework/repository/TaskReviewRepository.scala
app/org/maproulette/framework/service/TaskReviewService.scala
build.sbt
conf/v2_route/review.api

Sets an endpoint to be used by the front end housing all the variables needed for the review table CSV.  Reused the getTaskWithReviewParser, and implementation of a new endpoint. Uses existing configuration for filtering, and sorting.

Add Review Table CSV

---

app/org/maproulette/framework/controller/TaskReviewController.scala
conf/v2_route/review.api

Implemented to prevent people from using the backend directly to request a CSV of the review table endpoint with multiple multiple project ids.

Add barrier against multiple project ids

---

app/org/maproulette/framework/mixins/TaskParserMixin.scala
app/org/maproulette/framework/repository/TaskReviewRepository.scala

This resolves NULLs getting introduced into the database by fetching the values. A sample request and its generated sql query are below:
```sql
[debug] [application-akka.actor.default-dispatcher-21] o.m.f.HttpLoggingFilter.$anonfun$apply$1(HttpLoggingFilter.scala:39) - id=118 org.maproulette.framework.controller.TaskReviewController.extractReviewTableData: 'GET /api/v2/tasks/review/reviewTable/export?&reviewStatus=0,1,2,3,4,5,6,7,-1&challengeId=1&projectIds=2&metaReviewStatus=-2,0,1,2,3,6&&status=0,1,2,3,4,5,6,9&&priority=0,1,2&&sortBy=mapped_on&direction=ASC&displayedColumns=Internal%20Id,Review%20Status,Mapper,Challenge,Project,Mapped%20On,Reviewer,Reviewed%20On,Status,Priority,Actions,Additional%20Reviewers&invertedFilters=' took 13ms and returned 200
[info] …
```

Eliminate use of 'null' in TaskReviewRepository query and improve readability

---

build.sbt
project/plugins.sbt

Git tags are used to identify releases of the MapRoulette backend. This commit adds a few useful git and version settings in the response of route /api/v2/service/info.
The algorithm to determine the version is described by [sbt-git in their manual](https://github.com/sbt/sbt-git#versioning-with-git), and we use git describe. Here is the snippet from the readme:
The git plugin will now autogenerate your version using the following rules, in order:
1. Looks at version-property setting (default to `project.version`), and checks the `sys.props` to see if this has a value.  If so, use it.
2. Otherwise, looks at the project tags. The first to match the `gitTagToVersionNumberSetting` is used to assign the version.  The default is to look for tags that begin with `v` and a number, and use the …

Include project version from git in /api/v2/service/info

---

app/org/maproulette/framework/controller/TaskReviewController.scala
app/org/maproulette/framework/mixins/TaskParserMixin.scala
app/org/maproulette/framework/model/TaskReview.scala
app/org/maproulette/framework/repository/TaskHistoryRepository.scala
app/org/maproulette/framework/repository/TaskReviewRepository.scala

Add configuration for 3 new columns in the all review related tasks table, and implement them in the review table csv. The columns added are the Feature Ids, challenge ids, and project ids.

Add columns to review table

---

app/org/maproulette/framework/service/TaskBundleService.scala
app/org/maproulette/models/dal/TaskDAL.scala
test/org/maproulette/framework/service/TaskBundleServiceSpec.scala

Resolves issue: https://github.com/maproulette/maproulette3/issues/2062
Backend support for: https://github.com/maproulette/maproulette3/pull/2090
Makes it so a user can now bundle cooperative tasks, but also makes it so that they cant bundle cooperative tasks with other   task types like tag fix or other non cooperative tasks.

add cooperative task bundling rules

---

app/org/maproulette/framework/repository/NotificationSubscriptionRepository.scala

Team and Follow options are included in UI settings but were not present in subscription upsert function, making the settings non-functional. Added to upsert function.

added absent team and follow subscriptions to subscription options

---

app/controllers/AuthController.scala
app/org/maproulette/Config.scala
conf/application.conf

This allows for customization of the OSM OAuth2 scope via the conf (osm.oauth2Scope) or an environment variable (MR_OSM_OAUTH2SCOPE). At times the oauth2 scope needs reduced, for example a local dev or staging environment, to avoid accidentally publishing test data to OSM.

Support configurable OSM OAuth2 scope

---

README.md
app/org/maproulette/provider/ChallengeProvider.scala
conf/application.conf
conf/swagger.yml
docs/challenge_api.md

A few URLs were using 'http' instead of 'https'. The URLs would upgrade to TLS but it's a good habit to use HTTPS by default and not depend on the connection upgrade.

Use https in a few URLs

---

app/org/maproulette/models/dal/ChallengeDAL.scala
conf/evolutions/default/94.sql

resolves: https://github.com/maproulette/maproulette3/issues/2150

remove unique name constraint on virtual challenges

---

app/org/maproulette/Config.scala

During testing I see that an empty super.accounts causes an empty string to be added to the super accounts list. Minor tweak here to filter those out.

Allow for an empty 'maproulette.super.accounts' in the config

---

.github/workflows/scala.yml
README.md

This patch fixes a few minor annoyances with the readme and GH action logs.

Fix build badge in README and use GH actions/setup-java@v3

---

app/org/maproulette/exception/MPExceptionUtil.scala

When a request results in an HTTP 403 Forbidden or 404 NotFound, it's logged at an Error level and emits a full stack trace. That's not necessary and this patch changes it to a warning without the full stack trace.

MPExceptionUtil: Log http 403 Forbidden, 404 NotFound, at WARN level without stack

---

app/org/maproulette/Config.scala
app/org/maproulette/framework/controller/NotificationController.scala
conf/v2_route/notification.api

resolves https://github.com/maproulette/maproulette3/issues/2157
frontend work: https://github.com/maproulette/maproulette3/pull/2179

add system notices endpoint

---

app/org/maproulette/framework/controller/UserController.scala
app/org/maproulette/framework/service/GrantService.scala
app/org/maproulette/framework/service/UserService.scala
app/org/maproulette/jobs/Bootstrap.scala
app/org/maproulette/permissions/Permission.scala
conf/v2_route/user.api
test/org/maproulette/utils/TestSpec.scala

Create endpoints and service startup code to support adding/removing superuser roles via the API. Only existing superuser are authorized to make the calls.
Check user grants to determine if they're a superuser:
- Javascript
- `const isSuperUser = data.grants.some(grant => grant.role === -1);`
- Curl
- `curl -s -H "apiKey: $apiKey" -X GET 'http://localhost:9000/api/v2/user/whoami' | jq '{userId: .id, grants: [.grants[] | select(.role == -1)]}'`
Get the current superusers:
`curl -i -H "apiKey: $apiKey" -X GET 'http://localhost:9000/api/v2/superusers'`
Show that a super cannot demote themselves:
```sh
$ curl -s -i -H "apiKey: $apiKey" -X DELETE 'http://localhost:9000/api/v2/superuser/2'
HTTP/1.1 403 Forbidden
Vary: Origin
Date: Fri, 24 Nov 2023 19:40:06 GMT
Content-Type: application/json …
```

Support adding/removing superuser role via API

---

app/org/maproulette/filters/Filters.scala
app/org/maproulette/filters/HttpLoggingFilter.scala
conf/application.conf
conf/dev.conf.example
conf/logback-dev.xml
conf/logback.xml

MapRoulette will log requests to an access log appender and include a generated `maproulette-request-id` log marker and include it in the response header for clients to debug future issues. Note that clients are responsible for providing the `maproulette-request-id` in issues.
This change also includes minor fixes to 
- remove deprecated logger references from application.conf (resolving #1085) and 
- update to use an async log appender (resolving #1083) 
Here's what the updated logger output looks like in intellij (logback-dev.xml) loading the /dashboard for a logged in user. The response header `maproulette-request-id` exists and it does match the logs
This is what it looks like on staging (logback.xml) loading the /dashboard for a logged in user. The response header …

Create 'maproulette-request-id' for http requests

---

app/org/maproulette/framework/controller/CommentController.scala
app/org/maproulette/framework/service/CommentService.scala
conf/v2_route/comment.api

Frontend: https://github.com/maproulette/maproulette3/pull/2199
Issue fixed: 
When a user submitted a url with an attached comment including many spaces, using the majority of the character limit of the comment box, the URL encoder would replace every space with “%20”. This would enable there to be more characters in the url than what was displayed in the comment input box. The issue with this is that there is a 2048 character limit to urls, so those extra characters added over every space would often surpass this limit causing the comment to not be saved.
Changes:
Old route to add a comment to Task
`POST    /task/:id/comment/?comment=Example%20Comment&actionId=2 `
New route
`POST    /task/:id/comment/?actionId=2`
Old route to add comment to each Task in Bundle
`POST …

Move comments parameters into Request Body

---

app/org/maproulette/jobs/SchedulerActor.scala

Modified the 'updateLocations' task to enhance database efficiency. The recurring task now uses a transaction per iteration instead of one for the entire task, eliminating manual commits. Cache removals are also now done with each transaction, avoiding extra database lookups.
The main point here is to reduce contention. I don't expect much change to the overall speed of the scheduled task. Validation is to check the 'finished run' time (ofc check for exceptions as well):
- `docker logs maproulette-api | grep "Task 'Updating locations': Finished run"`
- or `journalctl -u docker --since "today" CONTAINER_NAME=maproulette-api | grep "Task 'Updating locations': Finished run"`
Metrics Before change: 
- Staging is consistent ~45s before the change. Prod ranges to around 50s to 90s.

Improve 'updateLocations' Task for Database Efficiency

---

app/org/maproulette/jobs/SchedulerActor.scala

The initial approach to refreshing the country leaderboard, which involved deleting all entries at once, led to data unavailability and HTTP 502 errors (due to hitting the 75s http request timeout) for users during updates. We've revised the process to sequentially delete and rebuild entries for each country and time duration. This adjustment ensures that leaderboard data remains accessible to users while updates for other countries are in progress.

Enhance Country Leaderboard Availability During Refresh

---

app/org/maproulette/jobs/SchedulerActor.scala

The initial approach to refreshing the leaderboard, which involved deleting all entries at once, led to data unavailability for users during updates. We've revised the process to sequentially delete and rebuild entries for each time duration. This adjustment helps to ensure that leaderboard data remains accessible to users while updates for other durations are in progress.

Enhance Leaderboard Availability During Refresh

---

build.sbt
project/plugins.sbt

Project `com.iheart:sbt-play-swagger` has been migrated to a new repository, so update to use the new name `io.github.play-swagger:sbt-play-swagger:1.6.2`. Also update org.webjars:swagger-ui from 4.14.3 to 5.10.3.

Migrate to io.github.play-swagger and update swagger-ui

---

app/org/maproulette/framework/repository/TaskBundleRepository.scala

There was an issue where multiple users could add the same task into their bundle, and this would cause problems on submission. The first user to submit their bundle had no issue but any other user that had bundled the same task would would get a "Bundle Failed"  due to that task being officially in a bundle because of that first users submission. To prevent this issue, in this commit we made it so tasks were locked on bundle, and bundles would fail to create if they try to bundle with that now locked task, or any other locked task.

add unlocked tasks only restriction to bundling and lock tasks on bundle

---

app/org/maproulette/framework/service/LeaderboardService.scala
test/org/maproulette/framework/service/LeaderboardServiceSpec.scala

Due to the extensive computational demand of dynamic queries for various MapRoulette leaderboards — including those for global standings, project-specific, challenge-specific, and country-specific rankings — system stability issues have been observed.
This patch disables the execution of dynamic leaderboard calculations. Requests triggering a dynamic query now result in an HTTP 400 response.
There was a presumption in the leaderboard code that every user was in the pre-generated leaderboard, and if they were not it would regen the entire thing, for all users, dynamically and per request. So it quickly overwhelmed the DB backend when there were a handful of "new" MapRoulette users to the site. This was especially unfortunate for group mapping parties.
The below leaderboards will not …

Improve stability by disabling dynamic leaderboard queries

---

app/org/maproulette/provider/ChallengeProvider.scala

When using overpass queries, there are 3 object types: relation, ways, and nodes. Relations are not yet supported, so this PR adds support for relations in overpass queries. Relations are a list of nodes and/or ways and/or relations in one object.

add support for relations in overpass queries

---

app/org/maproulette/models/dal/TaskDAL.scala

Tickets resolved by this pr: https://github.com/maproulette/maproulette3/issues/2292, https://github.com/maproulette/maproulette3/issues/2018
The reason why users where running into a looping issue with tasks marked as too hard was because the time interval that made it so that tasks marked with mappable status were invisible was based on the value of the "create" column in the task table, which was reset after as a task was set to created or skipped but not too hard since the too hard status is passed through the completion steps instead of the "reset to mappable" steps. To resolve this issue i made the 1 hour interval based on the mapped_on date. I also added some order sorting so that if a user marked a task as too_hard or skipped it that those tasks would be the last option to be …

fix nearby task looping too hard tasks issue

---

app/org/maproulette/framework/controller/TaskBundleController.scala
app/org/maproulette/framework/mixins/SearchParametersMixin.scala
app/org/maproulette/framework/repository/TaskBundleRepository.scala
app/org/maproulette/framework/service/TaskBundleService.scala
app/org/maproulette/session/SearchParameters.scala
conf/v2_route/bundle.api
test/org/maproulette/framework/service/TaskBundleServiceSpec.scala

Frontend: https://github.com/maproulette/maproulette3/pull/2291
Changes:
-----------------------------------------------------------------------------------------
This was implemented to lock all tasks in the bundle in certain contexts. For example, when a user goes to review a bundle, lockedTasks will be set to true so that all the tasks in the bundle the reviewer is reviewing will be locked.
Old route to to fetch a task bundle
`GET     /taskBundle/:id`
New route
`GET     /taskBundle/:id?lockedTasks=boolean`
This new route was implemented to reset bundles if a user redirects away from the bundle after making changes and no submission. From a backend percpective, this endpoint sets the bundle to include only the provided taskIds in the taskIds param, and set those tasks status and review …

add resetTaskBundle endpoint

---

build.sbt

This commit updates the versions of the following dependencies in build.sbt:
- anorm and anorm-postgres from 2.6.10 to 2.7.0
- postgresql from 42.5.0 to 42.7.3
- postgis-jdbc from 2021.1.0 to 2023.1.0
The upgrade of these dependencies ensures that we are using the latest stable releases, which include various improvements and bug fixes. The URLs for the release notes of postgresql and postgis-jdbc have been added for easy reference.
This change is part of the ongoing effort to keep the project dependencies up-to-date.

Upgrade anorm, postgresql, and postgis-jdbc dependencies

---

app/org/maproulette/framework/repository/UserRepository.scala
build.sbt

- Update the JTS (Java Topology Suite) dependency from `com.vividsolutions:jts:1.13` to `org.locationtech.jts:jts-core:1.19.0` due to the package's move to the Eclipse Foundation as LocationTech.
- Update`org.wololo:jts2geojson` to 0.18.1, which has a dependency on jts-core:1.18.1.
This resolves #1082

Migrate JTS package from vividsolutions to Eclipse Foundation

---

build.sbt
project/build.properties
project/plugins.sbt

The play 2.8 branch is EOL by May 31 2024. MapRoulette need to use a newer version and the first step is to update to the latest 2.8 and then step to 2.9.
See here for more details <https://www.playframework.com/documentation/3.0.x/Migration29>. This is a step in concluding #1079.

Update to the latest Play 2.8.x

---

.github/workflows/scala.yml
build.sbt
project/build.properties
project/plugins.sbt

Update sbt, plugins, and other dependencies to support running with Play 2.9 because Play 2.8 is out of support at the end of May 2024.
Folks that run MapRoulette locally or in some environment will need to update the APPLICATION_SECRET if it's not at least 32 bytes. This is detailed in issue <https://github.com/maproulette/maproulette-backend/issues/1117> and also <https://www.playframework.com/documentation/3.0.x/ApplicationSecret>
For more information about Play 2.9, see here <https://www.playframework.com/documentation/2.9.x/Highlights29>.
Specifically the updates are:
- `build.properties` sbt version is updated from `1.7.2` to `1.9.9`
- `project/plugins.sbt` Play sbt plugin is updated from `2.8.21` to `2.9.3`.
- `build.sbt` supporting dependencies
- `sangria-play-json` 2.0.1 -> …

Update to Play 2.9

---

conf/application.conf

Remove application.conf 'db.default.hikaricp.connectionTestQuery' to allow the driver to use the Connection.isValid() API, which improves performance.
[The HikariCP documentation](https://github.com/brettwooldridge/HikariCP) strongly recommends that we do not set `connectionTestQuery`:
> If your driver supports JDBC4 we strongly recommend not setting this property. This is for "legacy" drivers that do not support the JDBC4 Connection.isValid() API. This is the query that will be executed just before a connection is given to you from the pool to validate that the connection to the database is still alive. Again, try running the pool without this property, HikariCP will log an error if your driver is not JDBC4 compliant to let you know. Default: none

Perf: Remove 'connectionTestQuery' from application.conf

---

.github/workflows/scala.yml

The main changes here are to use the setup-java sbt cache and to create PostGRES databases of versions 13-3.3 and 16-3.4.

Update GH Action versions and test against PostGIS 13-3.3 and 16-3.4

---

.github/workflows/scala.yml

This is a testing only change -- MapRoulette runtime will remain at Java 11.
With Play framework 3.x planning to stop supporting Java 11, we're adding Java 17 support to MapRoulette-backend. The recent upgrade to Play 2.9 has helped us overcome earlier issues with Java 17. However, Java 21 is not supported yet (the compile fails).
This update keeps Java 11 support while adding Java 17, ensuring our code works with both versions.

Introduce Java 17 to MapRoulette-backend CI tests

---

app/org/maproulette/provider/osm/objects/VersionedObjects.scala

Issue Resolved: https://github.com/maproulette/maproulette3/issues/2344
In our changeset provider, we utilize a custom versioned object for constructing changesets for nodes, ways, and relations. However, the versioned object for relations previously employed a way wrapper, as illustrated below:
```xml
<way>{content}</way>
```
This resulted in OpenStreetMap searching for a way with the relation ID, leading to the error message:
`
https://www.openstreetmap.org/api/0.6/changeset/{changesetId}/upload failed with status code 412 (Precondition failed: Way {wayId} must have at least one node)
`
Relations necessitate a structure like so:
```xml
<relation>{content}</relation>
```
This pull request addresses this issue by implementing the required change.

fix changeset submission bug for tag fix tasks with relations

---

app/org/maproulette/framework/model/User.scala
app/org/maproulette/utils/Crypto.scala
conf/application.conf
conf/dev.conf.example

MapRoulette API had a dependency on the Play framework's application key, and this patch separates those keys. The MapRoulette secret is used to encrypt things specific to maproulette and it no longer depends on the Play application key.
Play 2.9 introduced a change where its application key must be 32 bytes or longer, and this impacted MapRoulette's cryptography with its own internal items. It's easier to manage these separately, similar to how the OSM secrets are not used to encrypt data stored within MapRoulette.

Introduce maproulette.secret.key conf and MAPROULETTE_SECRET_KEY env

---

app/org/maproulette/framework/repository/TaskBundleRepository.scala

Issue: Sometimes tasks removed from a bundle still redirect to the bundle they use to be a part of.
Reason: The backend caches task data, and in order to fully associate or disassociate a task with a bundle, the cache must be updated.
Solution: This PR adds those cache updates to all the bundle-related endpoints.

update task caching for task bundling endpoints

---

conf/application.conf
conf/dev.conf.example

In HOCON, variable substitutions are not performed if the replacement part is in quotes.
From the manual:
Substitutions are not parsed inside quoted strings. To get a string containing a substitution, you must use value concatenation with the substitution in the unquoted portion:
key : ${animal.favorite} is my favorite animal

Remove quotes around HOCON substitutions

---

app/org/maproulette/framework/repository/ChallengeRepository.scala

The scheduled MapRoulette backend task 'updateCompletionMetricsOfActiveChallenges' does not update the `challenges.tasks_remaining` metric, which appears to be its original intent. This field is used in the UI to allow users to sort challenges by the "remaining tasks". 
This PR tweaks the scheduled task to update `challenges.tasks_remaining`, along with the `challenges.completion_progress`.
Resolves: https://github.com/maproulette/maproulette3/issues/2324

update tasks_remaining column in challenge table

---

app/org/maproulette/framework/controller/UserController.scala
app/org/maproulette/framework/model/LockedTask.scala
app/org/maproulette/framework/model/LockedTaskData.scala
app/org/maproulette/framework/repository/UserSavedObjectsRepository.scala
app/org/maproulette/framework/service/UserService.scala
conf/v2_route/user.api

Adds the new endpoint: 
`GET     /user/:userId/lockedTasks?limit={Long}`
This endpoint retrieves a list of data. For each task that is locked by a user, or where the user_id in the locked table matches the requested userId, it returns the task's id, challenge id, challenge name, and the time it was locked.
Example of output:
```
[
{
"id": 50109,
"parent": 63,
"parentName": "Fix all roads in west Wichita",
"startedAt": "2024-07-30T17:56:59.650-05:00"
},
{
"id": 50207,
"parent": 63,
"parentName": "Fix all roads in west Wichita",
"startedAt": "2024-07-29T15:40:42.664-05:00"
},
{
"id": 50206,
"parent": 63,
"parentName": "Fix all roads in west Wichita",
"startedAt": "2024-07-29T15:40:42.669-05:00"
},
{
"id": 50210,
"parent": 63,
"parentName": "Fix all roads in west Wichita",
"startedAt": …
```

add `Retrieve a Users Locked Tasks` endpoint

---

app/org/maproulette/framework/repository/TaskReviewRepository.scala

Issue: Upon a second attempt to review a task, the review session has the first review session’s start time recorded under the field review_started_at. This results in incorrect, resulting high review time being calculated.
Solution: this pr removes the condition that prevent the column from being updated when a review session is started.

fix stale review_started_at column

---

app/org/maproulette/provider/ChallengeProvider.scala

Re-opening #1140 under a new branch in the main repo (rather than from my fork).
---
Fixes https://github.com/maproulette/maproulette3/issues/1908
I've made two logical changes here, which can be separated if necessary.
1. Checking the `Content-Type` returned by the Overpass API; if it's set to something other than `application/json`, mark the challenge as having failed to build, with a specific user-facing error string advising them to use `[out:json]`. overpass-api.de returns `Content-Type: application/json` for `[out:json]` queries, and `application/osm3s+xml` for `[out:xml]` queries. I believe this change is low risk.
2. Made the query rewriting code more robust, eliminating some of the currently known [pitfalls](https://github.com/maproulette/docs/pull/44). Previously rewriting would …

Improve error message when OverpassQL query mistakenly specifies [out:xml]

---

.github/workflows/scala.yml
README.md

MapRoulette is running using jdk 17, and dropping build/runtime support for jdk 11.

Update README and CI to reference jdk 17

---

app/org/maproulette/framework/mixins/TaskFilterMixin.scala
app/org/maproulette/framework/repository/TaskClusterRepository.scala
app/org/maproulette/framework/service/TaskClusterService.scala

Both the  /taskCluster endpoint and the /tasks/box/:left/:bottom/:right/:top endpoint should return the same tasks (the format of the data should be different, but the tasks themselves should be the same and the amount of tasks should be the same).
Issue: The two endpoints, when passed the same filtering parameters, would pass back different results.
Solution: Fixed the filtering conditions of these two endpoints:
`PUT     /taskCluster `
`PUT     /tasks/box/:left/:bottom/:right/:top`
More details on the solution: 
- Remove a manually added filter on enabled challenges from the taskCluster endpoint and use the built in search parameter instead.
- Fix the deleted challenges and projects filters to filter for challenges and projects that have a "false" deleted status. 
- Remove manually …

Fix deleted parent filter

---

conf/swagger.yml

I found it way to hard to collect these bits of information. This is mainly due to the fact that Google links directly to https://maproulette.org/docs/swagger-ui/index.html?url=/assets/swagger.json&docExpansion=none so that becomes the entry point when looking for the API. But also due to the fact that there is no API docs entry page in the docs which could explain some basic things. 
I finally found the info where to get the API key in https://github.com/osmlab/maproulette-python-client/tree/master?tab=readme-ov-file. I suggest to add the info where to find the API key right here; I added them in two places.
I also thing the swagger page should hint at the libraries. I did that too but without linking to them directly so only one place need to keep updates links (the docs page).
Finally, …

Swagger: How to get the API Key and other notes

---

app/org/maproulette/framework/model/Tag.scala
app/org/maproulette/framework/repository/TagRepository.scala
conf/evolutions/default/96.sql

This PR introduces a new 'active' column to the tags table, enhancing the customizability of error tags. The 'active' column allows error tags to be filtered from the available options on the frontend, while also preserving the history of past error tags for history maintenance.

Add active indicator column to tags table

---

Dockerfile
README.md
conf/application.conf

This PR adds a production-ready Dockerfile. It is similar to what's currently in https://github.com/maproulette/maproulette2-docker, except using a more conventional build workflow (building from the source code in the CWD, instead of using `git clone`).
In a future PR I'll be adding a CI step to build an image from this Dockerfile and push it to GHCR. That image will then be deployed automatically to staging, and when new releases are published, also to prod. Ultimately we won't need the maproulette2-docker repo anymore and can probably archive it.
Having official Docker images will also make it easier for anyone running their own instance of MapRoulette to keep up with new versions.

Add dockerfile

---

app/org/maproulette/framework/model/Challenge.scala
app/org/maproulette/framework/repository/ChallengeRepository.scala
app/org/maproulette/models/dal/ChallengeDAL.scala
conf/evolutions/default/97.sql

Resolves: https://github.com/maproulette/maproulette3/issues/2385
Deploy with: https://github.com/maproulette/maproulette3/pull/2494
Users can now add rapid dataset URLs to challenges via the create challenge form. The dataset url will be added to the rapid parameters in the Edit Mode window on the task inspection page.

Challenge Rapid Dataset support

---

app/org/maproulette/framework/controller/TaskController.scala
app/org/maproulette/framework/repository/TaskClusterRepository.scala
app/org/maproulette/framework/service/TaskClusterService.scala
app/org/maproulette/models/dal/ChallengeDAL.scala
conf/v2_route/task.api

The ` PUT     /tasks/box/:left/:bottom/:right/:top ` endpoint has some unneeded complexity when fetching for task markers. The reason why that endpoint was so complex is because it is also used to fetch task table data. This led to slower performance when fetching markers because paging, ordering, and sorting was applied.
Because that structure is needed for the tables but not for fetching tasks markers, I have created a new endpoint to reduce complexity: `PUT     /tasks/markers/:left/:bottom/:right/:top `.
This new endpoint exports the same task data as the previous endpoint, but doesn't query for the total task count, and also doesn't do any ordering or paging.
21771 task in view with 1001 task limit:
Old endpoint (Time to complete: ~ 1.1s-1.9s ):
New endpoint  (Time to complete: ~ …

add endpoint for fetching task markers specifically

---

app/org/maproulette/controllers/api/ChallengeController.scala
app/org/maproulette/utils/CSVEncoder.scala

Resolves: https://github.com/maproulette/maproulette3/issues/1902
This pr add the FeatureType column to the task csv export tables. The main 3 results for the column will be "Point", "LineString", and "GeometryCollection", or unknown if there is no type. Edge case scenarios were another type is used (if this is possible) will results in the type value, example: 
feature: { geometry: [{ type: "MultiLineString" }]} -> FeatureType = "MultilineString". 
Equivalents:
MapRoulette              | OSM
Point                          | Node
LineString                  | Way
GeometryCollection | Relation

add feature type to csv export

---

.github/workflows/docker-publish.yml

Works equivalently to https://github.com/maproulette/maproulette3/pull/2504 - using the GitHub API, we can trigger the maproulette-deploy repo's actions after the action in this repo finishes building and publishing a new image, in order to automatically deploy new code changes to staging.

Modify GitHub Actions workflow to trigger staging redeploy after building

---

app/org/maproulette/framework/mixins/SearchParametersMixin.scala
app/org/maproulette/framework/model/Challenge.scala
app/org/maproulette/models/dal/ChallengeDAL.scala
app/org/maproulette/session/SearchParameters.scala

Resolves: https://github.com/maproulette/maproulette3/issues/2532
Issue
The /api/v2/challenges/extendedFind endpoint was not correctly handling archived and global challenge filtering. The issue arose because the filter condition was always evaluating as false. This happened because the filter was being wrapped in Some(value) (e.g., Some(false) or Some(true)) instead of directly evaluating the value.
Fix Details
This PR updates the condition to handle the wrapped Some(value) correctly, ensuring that the filtering logic now behaves as expected. This is done by adding a default to the variable being filtered. This resolves the bug affecting archived and global challenge filtering.

fix isArchived and isGlobal filtering in extendFind endpoint

---

app/org/maproulette/framework/model/Comment.scala
app/org/maproulette/framework/model/TaskLogEntry.scala
app/org/maproulette/framework/repository/CommentRepository.scala
app/org/maproulette/framework/repository/TaskHistoryRepository.scala
conf/evolutions/default/100.sql
conf/evolutions/default/99.sql

Adding a boolean to the comments table that the frontend can use to indicate the comment was edited
To be released with: https://github.com/maproulette/maproulette3/pull/2529

add ability to edit comments and show if edited

---

app/org/maproulette/controllers/api/TaskController.scala
app/org/maproulette/framework/controller/TaskBundleController.scala
app/org/maproulette/framework/repository/TaskBundleRepository.scala
app/org/maproulette/framework/service/TaskBundleService.scala
conf/v2_route/bundle.api
conf/v2_route/task.api
test/org/maproulette/framework/service/TaskBundleServiceSpec.scala

This PR includes the following enhancements and changes:
Bundle Naming Convention:
Replaces resetTaskBundle with updateTaskBundle for better clarity and consistency in naming.
New Task Locking Endpoints:
Adds endpoints to lock, unlock, and refresh locks on multiple tasks at once. These endpoints are critical for efficiently handling task bundle locking.
Introduced new endpoints:
```
POST /task/bundle/lock
POST /task/bundle/unlock
POST /task/bundle/refresh
```

Update Bundle Naming Convention and Add Task Locking Endpoints

---

app/org/maproulette/framework/repository/TaskClusterRepository.scala
conf/evolutions/default/101.sql

This pr organizes the TaskClusterRepository.scala file, simplifies the task clusters query, and adds a new index the greatly improves the speed of task marker and cluster queries while filtering by both challengeIds and locations.
Has similar optimization results over a wider range of queries as what this pr was trying to do: https://github.com/maproulette/maproulette-backend/pull/1171

Add task (parent_id, location) index and simplify task marker/cluster queries

---

conf/evolutions/default/101.sql

This PR modifies the database migration script to use conditional creation for both the btree_gist extension and the GiST index on tasks. By adding IF NOT EXISTS clauses to both the extension creation and index creation statements, the migration will run safely on databases where these objects may have been previously created.

refactor 101.sql to handle existing index and extension

---

app/org/maproulette/jobs/SchedulerActor.scala

The is_global calculation was running on every challenge every time the scheduled action ran. This action appears to happen every minute, so this was causing latency in certain workflows and higher cpu usage. This pr moves the is_global calculation to the is stale challenge logic to limit the recalculation to only stale challenges.

move is global calculation into the stale challenge logic

---

app/org/maproulette/controllers/api/TaskController.scala
app/org/maproulette/framework/mixins/Locking.scala
app/org/maproulette/framework/model/ClusteredPoint.scala
app/org/maproulette/framework/repository/ProjectRepository.scala
app/org/maproulette/framework/repository/TaskBundleRepository.scala
app/org/maproulette/framework/repository/TaskClusterRepository.scala
app/org/maproulette/framework/service/TaskBundleService.scala
app/org/maproulette/models/dal/ChallengeDAL.scala
app/org/maproulette/models/dal/VirtualChallengeDAL.scala
conf/v2_route/task.api

Related: https://github.com/maproulette/maproulette3/pull/2619
Refactor task locking and unlocking methods for improved performance and error handling. Introduce bulk operations in TaskController and Locking mixin, and update API routes accordingly. Add 'lockedBy' field to ClusteredPoint model and adjust related DALs for consistency.

Move bundling to transactions and return lockedBy datapoint in fetch markers/clusters endpoints

---

app/org/maproulette/framework/psql/filter/Parameter.scala
app/org/maproulette/models/utils/DALHelper.scala
test/org/maproulette/framework/mixins/SearchParametersMixinSpec.scala
test/org/maproulette/framework/psql/FilterParameterSpec.scala

Resolves this error: ERROR: levenshtein argument exceeds maximum length of 255 characters
org.postgresql.util.PSQLException: ERROR: levenshtein argument exceeds maximum length of 255 characters
Appears to be caused by excessively large challenge or project names

Add limit to string length in  fuzzy search parameter sql query

---

app/org/maproulette/framework/repository/TaskBundleRepository.scala

This PR removes the automatic task locking mechanism for task bundle creation and modification. Previously, the system automatically locked tasks during bundle operations, leading to potential unexpected behavior and unnecessary task locks/unlocks. As the locking functionality for bundles has been relocated to new endpoints, it is no longer needed in the original bundle-related endpoints and can be removed.

Remove task locking from bundle creation workflow

---

app/org/maproulette/framework/controller/NotificationController.scala
app/org/maproulette/framework/repository/NotificationRepository.scala
app/org/maproulette/framework/service/NotificationService.scala
conf/v2_route/notification.api
test/org/maproulette/framework/repository/NotificationRepositorySpec.scala
test/org/maproulette/framework/service/NotificationServiceSpec.scala

Corresponding PR: https://github.com/maproulette/maproulette3/pull/2683
Adds functionality to mark user notifications as unread, providing users with better control over their notification management.
- **Endpoint**: `PUT /user/:userId/notifications/unread`
- **Request Body**: `{ "notificationIds": [1, 2, 3] }`
- **Response**: `{ "status": "OK", "message": "Notifications marked as unread" }`
- **Authorization**: Users can only modify their own notifications

Add API endpoint to mark notifications as unread

---

app/org/maproulette/framework/model/Challenge.scala
app/org/maproulette/framework/model/Task.scala
app/org/maproulette/framework/repository/ChallengeRepository.scala
app/org/maproulette/models/dal/ChallengeDAL.scala
app/org/maproulette/models/utils/ChallengeFormatters.scala
conf/evolutions/default/103.sql

Frontend implementation: https://github.com/maproulette/maproulette3/pull/2681
This PR extends MapRoulette's challenge priority system by adding **geographic bounds-based priority setting**. Now, challenge creators can also set task priorities based on whether tasks fall within specific geographic boundaries.
- **Bounds take precedence**: Geographic bounds are checked first, before property-based rules
- **Fallback to rules**: If no bounds match, the system falls back to existing property-based priority rules
- **Default priority**: If neither bounds nor rules match, uses the challenge's default priority
- Added three new nullable VARCHAR columns to the `challenges` table:
- `high_priority_bounds`
- `medium_priority_bounds` 
- `low_priority_bounds`

Add priority bounds to challenge

---

app/org/maproulette/controllers/api/TaskController.scala
app/org/maproulette/models/dal/TaskDAL.scala
app/org/maproulette/provider/websockets/WebSocketActor.scala
app/org/maproulette/provider/websockets/WebSocketMessages.scala

- Added functionality to send WebSocket messages when tasks are claimed, including challenge and project summaries.
- Implemented WebSocket notifications for each unlocked task, notifying users of the release.

Enhance TaskController to send WebSocket notifications on task claim and release

---

app/org/maproulette/controllers/api/ChallengeController.scala
app/org/maproulette/models/dal/ChallengeDAL.scala
conf/v2_route/challenge.api

Closes #1037. This allows applications to retrieve the tasks for a specific challenge and within a specific bounding box. Useful for e.g. Rapid which can be configured to show a particular challenge's tasks as markers on the screen (but only needs to fetch tasks within the current viewport).

Add `?bbox=` query parameter to `/challenge/view/:id` endpoint
